#include "hz5_contract.h"

#define HZ5_ALLOC_DESC_MAGIC UINT32_C(0x42414c48)
#define HZ5_ALLOC_DESC_ABI_VERSION UINT16_C(1)
#define HZ5_ALLOC_LANE_SPEED UINT32_C(1)
#define HZ5_ALLOC_LANE_DIAGNOSTIC UINT32_C(2)

#define HZ5_ALLOC_FEAT_DIAGNOSTIC_STATS UINT64_C(0x1)
#define HZ5_ALLOC_FEAT_P12_ROUTE_SHADOW UINT64_C(0x8)
#define HZ5_ALLOC_FEAT_P14_RETIRED_QUARANTINE UINT64_C(0x10)
#define HZ5_ALLOC_FEAT_P14_LOCKED_LOOKUP UINT64_C(0x20)
#define HZ5_ALLOC_FEAT_P23_ONE_PAGE_SC_STATS UINT64_C(0x40)
#define HZ5_ALLOC_FEAT_P25_STATS UINT64_C(0x80)

#define HZ5_ALLOC_SPEED_FORBIDDEN_MASK \
  (HZ5_ALLOC_FEAT_DIAGNOSTIC_STATS | HZ5_ALLOC_FEAT_P12_ROUTE_SHADOW | \
   HZ5_ALLOC_FEAT_P14_RETIRED_QUARANTINE | \
   HZ5_ALLOC_FEAT_P14_LOCKED_LOOKUP | \
   HZ5_ALLOC_FEAT_P23_ONE_PAGE_SC_STATS | HZ5_ALLOC_FEAT_P25_STATS)

#ifndef BENCHLAB_HZ5_SPEED_LANE
#define BENCHLAB_HZ5_SPEED_LANE 0
#endif

#ifndef BENCHLAB_HZ5_P12_ROUTE_SHADOW
#define BENCHLAB_HZ5_P12_ROUTE_SHADOW 0
#endif

#ifndef HZ5_P14_RETIRED_QUARANTINE
#define HZ5_P14_RETIRED_QUARANTINE 0
#endif

#ifndef HZ5_P14_LOCKED_LOOKUP_RELEASE
#define HZ5_P14_LOCKED_LOOKUP_RELEASE 0
#endif

#ifndef HZ5_P23_1P_SC_STATS
#define HZ5_P23_1P_SC_STATS 0
#endif

#ifndef BENCHLAB_HZ5_P25_STATS
#define BENCHLAB_HZ5_P25_STATS HZ5_DIAGNOSTIC_STATS
#endif

#if BENCHLAB_HZ5_SPEED_LANE && HZ5_DIAGNOSTIC_STATS
#error "BENCHLAB_HZ5_SPEED_LANE requires HZ5_DIAGNOSTIC_STATS=0"
#endif

#if BENCHLAB_HZ5_SPEED_LANE && BENCHLAB_HZ5_P25_STATS
#error "BENCHLAB_HZ5_SPEED_LANE requires BENCHLAB_HZ5_P25_STATS=0"
#endif

#if BENCHLAB_HZ5_SPEED_LANE && BENCHLAB_HZ5_P12_ROUTE_SHADOW
#error "BENCHLAB_HZ5_SPEED_LANE cannot enable BENCHLAB_HZ5_P12_ROUTE_SHADOW"
#endif

#if BENCHLAB_HZ5_SPEED_LANE && HZ5_P14_RETIRED_QUARANTINE
#error "BENCHLAB_HZ5_SPEED_LANE cannot enable HZ5_P14_RETIRED_QUARANTINE"
#endif

#if BENCHLAB_HZ5_SPEED_LANE && HZ5_P14_LOCKED_LOOKUP_RELEASE
#error "BENCHLAB_HZ5_SPEED_LANE cannot enable HZ5_P14_LOCKED_LOOKUP_RELEASE"
#endif

#if BENCHLAB_HZ5_SPEED_LANE && HZ5_P23_1P_SC_STATS
#error "BENCHLAB_HZ5_SPEED_LANE cannot enable HZ5_P23_1P_SC_STATS"
#endif

#if HZ5_DIAGNOSTIC_STATS
#define HZ5_DESC_DIAG_STATS_BIT HZ5_ALLOC_FEAT_DIAGNOSTIC_STATS
#else
#define HZ5_DESC_DIAG_STATS_BIT 0
#endif

#if BENCHLAB_HZ5_P12_ROUTE_SHADOW
#define HZ5_DESC_P12_BIT HZ5_ALLOC_FEAT_P12_ROUTE_SHADOW
#else
#define HZ5_DESC_P12_BIT 0
#endif

#if HZ5_P14_RETIRED_QUARANTINE
#define HZ5_DESC_P14_RETIRE_BIT HZ5_ALLOC_FEAT_P14_RETIRED_QUARANTINE
#else
#define HZ5_DESC_P14_RETIRE_BIT 0
#endif

#if HZ5_P14_LOCKED_LOOKUP_RELEASE
#define HZ5_DESC_P14_LOCKED_BIT HZ5_ALLOC_FEAT_P14_LOCKED_LOOKUP
#else
#define HZ5_DESC_P14_LOCKED_BIT 0
#endif

#if HZ5_P23_1P_SC_STATS
#define HZ5_DESC_P23_BIT HZ5_ALLOC_FEAT_P23_ONE_PAGE_SC_STATS
#else
#define HZ5_DESC_P23_BIT 0
#endif

#if BENCHLAB_HZ5_P25_STATS
#define HZ5_DESC_P25_STATS_BIT HZ5_ALLOC_FEAT_P25_STATS
#else
#define HZ5_DESC_P25_STATS_BIT 0
#endif

#define HZ5_DESC_FEATURE_MASK \
  (HZ5_DESC_DIAG_STATS_BIT | HZ5_DESC_P12_BIT | \
   HZ5_DESC_P14_RETIRE_BIT | HZ5_DESC_P14_LOCKED_BIT | \
   HZ5_DESC_P23_BIT | HZ5_DESC_P25_STATS_BIT)

#if BENCHLAB_HZ5_SPEED_LANE
#define HZ5_DESC_LANE_KIND HZ5_ALLOC_LANE_SPEED
#define HZ5_DESC_LANE_NAME "hz5-speed-lane"
#else
#define HZ5_DESC_LANE_KIND HZ5_ALLOC_LANE_DIAGNOSTIC
#define HZ5_DESC_LANE_NAME "hz5-diagnostic-or-research"
#endif

const Hz5AllocatorDescriptorV1* hz5_contract_descriptor_v1(void) {
  static const Hz5AllocatorDescriptorV1 descriptor = {
      HZ5_ALLOC_DESC_MAGIC,
      HZ5_ALLOC_DESC_ABI_VERSION,
      (uint16_t)sizeof(Hz5AllocatorDescriptorV1),
      HZ5_DESC_LANE_KIND,
      0,
      HZ5_DESC_FEATURE_MASK,
      HZ5_ALLOC_SPEED_FORBIDDEN_MASK,
      "hakozuna-hz5",
      HZ5_DESC_LANE_NAME,
      "unknown",
      "manual-contract",
      "benchlab-hz5-adapter"};
  return &descriptor;
}
