#include "hz5_contract.h"

#define HZ5_ALLOC_DESC_MAGIC UINT32_C(0x42414c48)
#define HZ5_ALLOC_DESC_ABI_VERSION UINT16_C(1)
#define HZ5_ALLOC_LANE_SPEED UINT32_C(1)
#define HZ5_ALLOC_LANE_DIAGNOSTIC UINT32_C(2)

#define HZ5_ALLOC_FEAT_DIAGNOSTIC_STATS UINT64_C(0x1)
#define HZ5_ALLOC_FEAT_P12_ROUTE_SHADOW UINT64_C(0x8)
#define HZ5_ALLOC_FEAT_P14_RETIRED_QUARANTINE UINT64_C(0x10)
#define HZ5_ALLOC_FEAT_P14_LOCKED_LOOKUP UINT64_C(0x20)
#define HZ5_ALLOC_FEAT_P23_ONE_PAGE_SC_STATS UINT64_C(0x40)
#define HZ5_ALLOC_FEAT_P25_STATS UINT64_C(0x80)

#define HZ5_ALLOC_SPEED_FORBIDDEN_MASK \
  (HZ5_ALLOC_FEAT_DIAGNOSTIC_STATS | HZ5_ALLOC_FEAT_P12_ROUTE_SHADOW | \
   HZ5_ALLOC_FEAT_P14_RETIRED_QUARANTINE | \
   HZ5_ALLOC_FEAT_P14_LOCKED_LOOKUP | \
   HZ5_ALLOC_FEAT_P23_ONE_PAGE_SC_STATS | HZ5_ALLOC_FEAT_P25_STATS)

#ifndef BENCHLAB_HZ5_SPEED_LANE
#define BENCHLAB_HZ5_SPEED_LANE 0
#endif

#ifndef BENCHLAB_HZ5_P12_ROUTE_SHADOW
#define BENCHLAB_HZ5_P12_ROUTE_SHADOW 0
#endif

#ifndef HZ5_P14_RETIRED_QUARANTINE
#define HZ5_P14_RETIRED_QUARANTINE 0
#endif

#ifndef HZ5_P14_LOCKED_LOOKUP_RELEASE
#define HZ5_P14_LOCKED_LOOKUP_RELEASE 0
#endif

#ifndef HZ5_P23_1P_SC_STATS
#define HZ5_P23_1P_SC_STATS 0
#endif

#ifndef BENCHLAB_HZ5_P25_STATS
#define BENCHLAB_HZ5_P25_STATS HZ5_DIAGNOSTIC_STATS
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P
#define BENCHLAB_HZ5_LINUX_LOCAL2P 0
#endif

#ifndef HZ5_DESC_SOURCE_COMMIT
#define HZ5_DESC_SOURCE_COMMIT "unknown"
#endif

#if BENCHLAB_HZ5_SPEED_LANE && HZ5_DIAGNOSTIC_STATS
#error "BENCHLAB_HZ5_SPEED_LANE requires HZ5_DIAGNOSTIC_STATS=0"
#endif

#if BENCHLAB_HZ5_SPEED_LANE && BENCHLAB_HZ5_P25_STATS
#error "BENCHLAB_HZ5_SPEED_LANE requires BENCHLAB_HZ5_P25_STATS=0"
#endif

#if BENCHLAB_HZ5_SPEED_LANE && BENCHLAB_HZ5_P12_ROUTE_SHADOW
#error "BENCHLAB_HZ5_SPEED_LANE cannot enable BENCHLAB_HZ5_P12_ROUTE_SHADOW"
#endif

#if BENCHLAB_HZ5_SPEED_LANE && HZ5_P14_RETIRED_QUARANTINE
#error "BENCHLAB_HZ5_SPEED_LANE cannot enable HZ5_P14_RETIRED_QUARANTINE"
#endif

#if BENCHLAB_HZ5_SPEED_LANE && HZ5_P14_LOCKED_LOOKUP_RELEASE
#error "BENCHLAB_HZ5_SPEED_LANE cannot enable HZ5_P14_LOCKED_LOOKUP_RELEASE"
#endif

#if BENCHLAB_HZ5_SPEED_LANE && HZ5_P23_1P_SC_STATS
#error "BENCHLAB_HZ5_SPEED_LANE cannot enable HZ5_P23_1P_SC_STATS"
#endif

#if HZ5_DIAGNOSTIC_STATS
#define HZ5_DESC_DIAG_STATS_BIT HZ5_ALLOC_FEAT_DIAGNOSTIC_STATS
#else
#define HZ5_DESC_DIAG_STATS_BIT 0
#endif

#if BENCHLAB_HZ5_P12_ROUTE_SHADOW
#define HZ5_DESC_P12_BIT HZ5_ALLOC_FEAT_P12_ROUTE_SHADOW
#else
#define HZ5_DESC_P12_BIT 0
#endif

#if HZ5_P14_RETIRED_QUARANTINE
#define HZ5_DESC_P14_RETIRE_BIT HZ5_ALLOC_FEAT_P14_RETIRED_QUARANTINE
#else
#define HZ5_DESC_P14_RETIRE_BIT 0
#endif

#if HZ5_P14_LOCKED_LOOKUP_RELEASE
#define HZ5_DESC_P14_LOCKED_BIT HZ5_ALLOC_FEAT_P14_LOCKED_LOOKUP
#else
#define HZ5_DESC_P14_LOCKED_BIT 0
#endif

#if HZ5_P23_1P_SC_STATS
#define HZ5_DESC_P23_BIT HZ5_ALLOC_FEAT_P23_ONE_PAGE_SC_STATS
#else
#define HZ5_DESC_P23_BIT 0
#endif

#if BENCHLAB_HZ5_P25_STATS
#define HZ5_DESC_P25_STATS_BIT HZ5_ALLOC_FEAT_P25_STATS
#else
#define HZ5_DESC_P25_STATS_BIT 0
#endif

#define HZ5_DESC_FEATURE_MASK \
  (HZ5_DESC_DIAG_STATS_BIT | HZ5_DESC_P12_BIT | \
   HZ5_DESC_P14_RETIRE_BIT | HZ5_DESC_P14_LOCKED_BIT | \
   HZ5_DESC_P23_BIT | HZ5_DESC_P25_STATS_BIT)

#if BENCHLAB_HZ5_LINUX_LOCAL2P
#define HZ5_DESC_LANE_NAME "hz5-linux-local2p"
#elif BENCHLAB_HZ5_LINUX_P25_BRIDGE_ATTR
#if BENCHLAB_HZ5_LINUX_P25_BRIDGE_ATTR_NO_CAS
#define HZ5_DESC_LANE_NAME "hz5-linux-p25attr-no-cas"
#elif BENCHLAB_HZ5_LINUX_P25_BRIDGE_ATTR_NO_COOKIE
#define HZ5_DESC_LANE_NAME "hz5-linux-p25attr-no-cookie"
#elif BENCHLAB_HZ5_LINUX_P25_BRIDGE_ATTR_READONLY_STATE
#define HZ5_DESC_LANE_NAME "hz5-linux-p25attr-readonly"
#else
#define HZ5_DESC_LANE_NAME "hz5-linux-p25attr"
#endif
#elif BENCHLAB_HZ5_LINUX_P43_PORT
#if BENCHLAB_HZ5_P43_WRAPPER_TOKEN
#if BENCHLAB_HZ5_P43_WRAPPER_TOKEN_BRIDGE
#define HZ5_DESC_LANE_NAME "hz5-linux-p43-tokenbridge"
#else
#define HZ5_DESC_LANE_NAME "hz5-linux-p43-token"
#endif
#elif BENCHLAB_HZ5_P43_DECODED_RAW_LOOKUP
#if BENCHLAB_HZ5_P43_RAW_ALLOCATED_LOOKUP_ONLY
#define HZ5_DESC_LANE_NAME "hz5-linux-p43-rawalloc"
#elif BENCHLAB_HZ5_P43_RAW_FAST_LOOKUP_ONLY
#define HZ5_DESC_LANE_NAME "hz5-linux-p43-rawfast"
#else
#define HZ5_DESC_LANE_NAME "hz5-linux-p43-rawlookup"
#endif
#elif BENCHLAB_HZ5_P43_TRUST_WRAPPER_SOURCE
#define HZ5_DESC_LANE_NAME "hz5-linux-p43-trustwrap"
#elif BENCHLAB_HZ5_P43_TRUST_FAST_LOOKUP
#define HZ5_DESC_LANE_NAME "hz5-linux-p43-trustfast"
#elif BENCHLAB_HZ5_P43_UNSAFE_NO_LOOKUP
#define HZ5_DESC_LANE_NAME "hz5-linux-p43-nolookup"
#elif !BENCHLAB_HZ5_P43_PREPARED_BRIDGE
#define HZ5_DESC_LANE_NAME "hz5-linux-p43-source"
#else
#define HZ5_DESC_LANE_NAME "hz5-linux-p43"
#endif
#elif BENCHLAB_HZ5_STANDALONE_EXACT_ONLY
#define HZ5_DESC_LANE_NAME "hz5-linux-standalone-exact"
#elif BENCHLAB_HZ5_SPEED_LANE
#define HZ5_DESC_LANE_NAME "hz5-speed-lane"
#else
#define HZ5_DESC_LANE_NAME "hz5-diagnostic-or-research"
#endif

#if BENCHLAB_HZ5_SPEED_LANE
#define HZ5_DESC_LANE_KIND HZ5_ALLOC_LANE_SPEED
#else
#define HZ5_DESC_LANE_KIND HZ5_ALLOC_LANE_DIAGNOSTIC
#endif

const Hz5AllocatorDescriptorV1* hz5_contract_descriptor_v1(void) {
  static const Hz5AllocatorDescriptorV1 descriptor = {
      HZ5_ALLOC_DESC_MAGIC,
      HZ5_ALLOC_DESC_ABI_VERSION,
      (uint16_t)sizeof(Hz5AllocatorDescriptorV1),
      HZ5_DESC_LANE_KIND,
      0,
      HZ5_DESC_FEATURE_MASK,
      HZ5_ALLOC_SPEED_FORBIDDEN_MASK,
      "hakozuna-hz5",
      HZ5_DESC_LANE_NAME,
      HZ5_DESC_SOURCE_COMMIT,
      "manual-contract",
      HZ5_DESC_LANE_NAME};
  return &descriptor;
}
