#ifndef HZ6_H
#define HZ6_H

#include "hz6_contract.h"

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct Hz6Allocator Hz6Allocator;

#ifndef HZ6_STATS_CLASS_COUNT
#define HZ6_STATS_CLASS_COUNT 16u
#endif

typedef struct Hz6StatsSnapshot {
  size_t route_valid;
  size_t route_invalid;
  size_t route_miss;
  size_t route_visibility_lookup;
  size_t route_visibility_hit;
  size_t route_visibility_hit_local_owner;
  size_t route_visibility_hit_foreign_owner;
  size_t route_visibility_miss;
  size_t route_visibility_probe_total;
  size_t route_visibility_probe_max;
  size_t transfer_push;
  size_t transfer_pop;
  size_t transfer_current;
  size_t transfer_current_max;
  size_t remote_free_attempt;
  size_t remote_free_strict_owner_block;
  size_t remote_free_transfer_fail;
  size_t route_rehome_attempt;
  size_t route_rehome_success;
  size_t route_rehome_fail;
  size_t lifecycle_owner_mismatch;
  size_t lifecycle_foreign_free_attempt;
  size_t lifecycle_foreign_free_handled;
  size_t lifecycle_foreign_free_invalid;
  size_t visible_first_attempt;
  size_t visible_first_hit;
  size_t visible_first_miss;
  size_t visible_first_visible_invalid;
  size_t visible_first_local_fallback;
  size_t visible_first_local_fallback_invalid;
  size_t visible_first_local_lookup_skipped;
  size_t negative_filter_attempt;
  size_t negative_filter_not_armed;
  size_t negative_filter_rehome_blocked;
  size_t negative_filter_skip_local;
  size_t negative_filter_maybe_local;
  size_t negative_filter_shadow_false_skip;
  size_t negative_filter_shadow_local_valid;
  size_t negative_filter_shadow_local_invalid;
  size_t negative_filter_range_probe_total;
  size_t negative_filter_range_probe_max;
  size_t shared_dir_lookup;
  size_t shared_dir_hit;
  size_t shared_dir_miss;
  size_t shared_dir_stale;
  size_t shared_dir_hit_local_allocator;
  size_t shared_dir_hit_foreign_allocator;
  size_t shared_dir_would_skip_local;
  size_t shared_dir_register;
  size_t shared_dir_unregister;
  size_t shared_dir_probe_total;
  size_t shared_dir_probe_max;
  size_t shared_dir_first_attempt;
  size_t shared_dir_first_hit;
  size_t shared_dir_first_fallback;
  size_t shared_dir_first_invalid;
  size_t source_owned_prepare;
  size_t source_owned_route_hit_local_owner;
  size_t source_owned_visibility_hit_local_owner;
  size_t source_owned_visibility_hit_foreign_owner;
  size_t source_owned_remote_free_attempt;
  size_t source_owned_release;
  size_t source_alloc;
  size_t frontcache_reuse_hit;
  size_t frontcache_reuse_invalid;
  size_t frontcache_push_by_class[HZ6_STATS_CLASS_COUNT];
  size_t frontcache_pop_empty_by_class[HZ6_STATS_CLASS_COUNT];
  size_t transfer_reuse_hit;
  size_t transfer_reuse_invalid;
  size_t source_refill_starvation;
  size_t source_refill_saturation;
  size_t source_refill_boost;
  size_t source_refill_clamp;
  size_t source_admission_open;
  size_t source_admission_boosted;
  size_t source_admission_clamped;
  size_t control_plane_normal;
  size_t control_plane_burst_supply_would_open;
  size_t control_plane_close_would_start;
  size_t source_prefill_attempt;
  size_t source_prefill_filled;
  size_t source_prefill_fallback;
  size_t front_source_prefill_attempt[HZ6_FRONT_ATTR_COUNT];
  size_t front_source_prefill_filled[HZ6_FRONT_ATTR_COUNT];
  size_t front_source_prefill_fallback[HZ6_FRONT_ATTR_COUNT];
  size_t front_source_ops_alloc;
  size_t front_source_slot_alloc;
  size_t front_source_prefill_alloc;
  size_t toy_source_prefill_call;
  size_t local2p_source_alloc;
  size_t midpage_source_alloc;
  size_t large_source_alloc;
  size_t toy_source_alloc;
  size_t front_alloc_path[HZ6_FRONT_ATTR_COUNT][HZ6_ALLOC_PATH_COUNT];
  size_t alloc_fail;
  size_t descriptor_exhausted;
  size_t route_register_fail;
  size_t source_block_exhausted;
  size_t route_active_current;
  size_t route_active_max;
  size_t descriptor_probe_total;
  size_t descriptor_probe_max;
  size_t descriptor_fail_active_max;
  size_t descriptor_fail_local_free_max;
  size_t descriptor_fail_transfer_free_max;
  size_t descriptor_fail_remote_pending_max;
  size_t descriptor_fail_central_free_max;
  size_t descriptor_fail_released_max;
  size_t descriptor_fail_orphan_max;
  size_t descriptor_fail_dead_with_ptr_max;
  size_t descriptor_fail_frontcache_total_max;
  size_t descriptor_fail_frontcache_largest_bin_max;
  size_t descriptor_fail_frontcache_nonempty_bins_max;
  size_t descriptor_frontcache_reuse_dryrun_calls;
  size_t descriptor_frontcache_reuse_requested_nonempty;
  size_t descriptor_frontcache_reuse_requested_total;
  size_t descriptor_frontcache_reuse_donor_total;
  size_t descriptor_frontcache_reuse_largest_donor_max;
  size_t descriptor_frontcache_reuse_donor_bins_max;
  size_t descriptorless_frontcache_push;
  size_t descriptorless_frontcache_pop;
  size_t descriptorless_frontcache_descriptor_fail;
  size_t descriptorless_frontcache_route_fail;
  size_t descriptorless_frontcache_invalid;
  size_t descriptorreserve_frontcache_push;
  size_t descriptorreserve_frontcache_pop;
  size_t descriptorreserve_frontcache_missing;
  size_t descriptorreserve_frontcache_invalid;
  size_t descgov_trigger_descriptor_fail;
  size_t descgov_detach_attempt;
  size_t descgov_detach_success;
  size_t descgov_detach_budget_denied;
  size_t descgov_detach_class_denied;
  size_t descgov_materialize_admit;
  size_t descgov_materialize_block_no_descriptor;
  size_t descgov_materialize_fail;
  size_t descgov_detached_current;
  size_t descgov_detached_max;
  size_t descgov_requested_class[HZ6_STATS_CLASS_COUNT];
  size_t descgov_donor_class[HZ6_STATS_CLASS_COUNT];
  size_t descgov_materialize_fail_class[HZ6_STATS_CLASS_COUNT];
  size_t frontcache_spill_dryrun_calls;
  size_t frontcache_spill_dryrun_requested_empty;
  size_t frontcache_spill_dryrun_candidate_calls;
  size_t frontcache_spill_dryrun_reclaimable_total;
  size_t frontcache_spill_dryrun_largest_donor_max;
  size_t frontcache_spill_dryrun_donor_bins_max;
  size_t frontcache_spill_attempt;
  size_t frontcache_spill_success;
  size_t frontcache_spill_no_candidate;
  size_t frontcache_spill_invalid;
  size_t frontcache_spill_retry_success;
  size_t frontcache_borrow_dryrun_calls;
  size_t frontcache_borrow_dryrun_candidate_calls;
  size_t frontcache_borrow_dryrun_candidate_total;
  size_t frontcache_borrow_dryrun_largest_candidate_max;
  size_t frontcache_borrow_attempt;
  size_t frontcache_borrow_success;
  size_t frontcache_borrow_no_candidate;
  size_t frontcache_borrow_invalid;
  size_t frontcache_cap_dryrun_push;
  size_t frontcache_cap_dryrun_over_cap;
  size_t frontcache_cap_dryrun_would_release;
  size_t frontcache_cap_dryrun_soft_cap_max;
  size_t frontcache_cap_dryrun_bin_count_max;
  size_t frontcache_cap_release;
  size_t source_run_reuse_dryrun_calls;
  size_t source_run_reuse_dryrun_candidate_calls;
  size_t source_run_reuse_dryrun_candidate_blocks_total;
  size_t source_run_reuse_dryrun_free_slots_total;
  size_t source_run_reuse_dryrun_largest_free_slots_max;
  size_t source_run_reuse_attempt;
  size_t source_run_reuse_candidate;
  size_t source_run_reuse_hit;
  size_t source_run_reuse_miss_no_block;
  size_t source_run_reuse_miss_no_slot;
  size_t source_run_reuse_reserved;
  size_t source_run_reuse_slot_fail;
  size_t source_run_reuse_descriptor_fail;
  size_t source_run_reuse_descriptor_reclaim_attempt;
  size_t source_run_reuse_descriptor_reclaim_success;
  size_t source_run_reuse_descriptor_reclaim_no_candidate;
  size_t source_run_reuse_same_class_reclaim_attempt;
  size_t source_run_reuse_same_class_reclaim_success;
  size_t source_run_reuse_same_class_reclaim_no_candidate;
  size_t source_run_reuse_route_fail;
  size_t source_run_reuse_prepare_fail;
  size_t source_run_reuse_rollback;
  size_t source_run_reuse_used_count_mismatch;
  size_t route_exact_lookup_probe_total;
  size_t route_exact_lookup_probe_max;
  size_t owner_locality_lookup;
  size_t owner_locality_hit_local_allocator;
  size_t owner_locality_hit_foreign_allocator;
  size_t owner_locality_miss;
  size_t owner_locality_register;
  size_t owner_locality_unregister;
  size_t owner_locality_probe_total;
  size_t owner_locality_probe_max;
  size_t route_lookup_probe_total;
  size_t route_lookup_probe_max;
  size_t route_register_probe_total;
  size_t route_register_probe_max;
  size_t route_unregister_probe_total;
  size_t route_unregister_probe_max;
  size_t route_register_reason_unknown;
  size_t route_register_reason_source_run_slot;
  size_t route_register_reason_direct_source;
  size_t route_register_reason_materialize;
  size_t route_register_reason_rehome;
  size_t route_unregister_reason_unknown;
  size_t route_unregister_reason_frontcache_overflow;
  size_t route_unregister_reason_cap_release;
  size_t route_unregister_reason_descriptorless_detach;
  size_t route_unregister_reason_source_slot_release;
  size_t route_unregister_reason_rehome;
  size_t route_tombstone_current;
  size_t route_tombstone_max;
  size_t route_register_used_tombstone;
  size_t route_register_full_probe_with_tombstone;
  size_t route_tombstone_compact_attempt;
  size_t route_tombstone_compact_success;
  size_t route_tombstone_compact_fail_alloc;
  size_t route_tombstone_compact_moved;
  size_t route_retained_overflow_attempt;
  size_t route_retained_overflow_success;
  size_t route_retained_overflow_fail;
  size_t source_block_probe_total;
  size_t source_block_probe_max;
  size_t source_block_fail_active_max;
  size_t source_block_fail_registered_max;
  size_t source_block_fail_ref_nonzero_max;
  size_t source_block_fail_ref_zero_max;
  size_t memory_descriptor_table_bytes;
  size_t memory_route_table_bytes;
  size_t memory_source_block_table_bytes;
  size_t memory_frontcache_table_bytes;
  size_t memory_transfer_table_bytes;
  size_t memory_ownerlocality_index_bytes;
  size_t memory_active_descriptors;
  size_t memory_local_free_descriptors;
  size_t memory_transfer_free_descriptors;
  size_t memory_remote_pending_descriptors;
  size_t memory_dead_with_ptr_descriptors;
  size_t memory_active_source_blocks;
  size_t memory_registered_source_blocks;
  size_t memory_ref_nonzero_source_blocks;
  size_t memory_source_block_payload_bytes;
  size_t memory_source_block_committed_estimate;
  size_t memory_frontcache_total;
  size_t memory_frontcache_largest_bin;
  size_t metadata_descriptor_entry_bytes;
  size_t metadata_descriptor_thin_hot_entry_bytes;
  size_t metadata_descriptor_thin_hot_table_bytes;
  size_t metadata_descriptor_thin_hot_savings_bytes;
  size_t metadata_descriptor_ownerless_hot_entry_bytes;
  size_t metadata_descriptor_ownerless_hot_table_bytes;
  size_t metadata_descriptor_ownerless_hot_savings_bytes;
  size_t metadata_descriptor_owner16_hot_entry_bytes;
  size_t metadata_descriptor_owner16_hot_table_bytes;
  size_t metadata_descriptor_owner16_hot_savings_bytes;
  size_t metadata_route_entry_bytes;
  size_t metadata_route_slim_entry_bytes;
  size_t metadata_route_slim_table_bytes;
  size_t metadata_route_slim_savings_bytes;
  size_t metadata_source_block_entry_bytes;
  size_t metadata_source_block_slim_entry_bytes;
  size_t metadata_source_block_slim_table_bytes;
  size_t metadata_source_block_slim_savings_bytes;
  size_t metadata_frontcache_entry_bytes;
  size_t metadata_frontcache_slim_entry_bytes;
  size_t metadata_frontcache_slim_table_bytes;
  size_t metadata_frontcache_slim_savings_bytes;
  size_t large_span_central_push;
  size_t large_span_central_pop;
  size_t large_span_source_alloc;
} Hz6StatsSnapshot;

void hz6_allocator_init(Hz6Allocator* allocator);

void hz6_allocator_destroy(Hz6Allocator* allocator);

void* hz6_malloc(Hz6Allocator* allocator, size_t size);

void hz6_free(Hz6Allocator* allocator, void* ptr);

int hz6_free_remote(Hz6Allocator* allocator, void* ptr);

int hz6_owns(Hz6Allocator* allocator, const void* ptr);

Hz6StatsSnapshot hz6_stats_snapshot(const Hz6Allocator* allocator);

#ifdef __cplusplus
}
#endif

#endif
