#ifndef HZ6_CONFIG_H
#define HZ6_CONFIG_H

#include <stddef.h>

#ifndef HZ6_ROUTE_TABLE_CAPACITY
#define HZ6_ROUTE_TABLE_CAPACITY ((size_t)64)
#endif

#ifndef HZ6_ROUTE_PAGE_GRANULARITY
#define HZ6_ROUTE_PAGE_GRANULARITY ((size_t)4096)
#endif

#ifndef HZ6_TRANSFER_CACHE_CAPACITY
#define HZ6_TRANSFER_CACHE_CAPACITY ((size_t)64)
#endif

#ifndef HZ6_LARGE_SPAN_CENTRAL_CLASS_BYTES_CAP
#define HZ6_LARGE_SPAN_CENTRAL_CLASS_BYTES_CAP \
  ((size_t)8u * 1024u * 1024u)
#endif

#ifndef HZ6_LARGE_SPAN_CENTRAL_GLOBAL_BYTES_CAP
#define HZ6_LARGE_SPAN_CENTRAL_GLOBAL_BYTES_CAP \
  HZ6_LARGE_SPAN_CENTRAL_CLASS_BYTES_CAP
#endif

#ifndef HZ6_TRANSFER_SHARD_COUNT
#define HZ6_TRANSFER_SHARD_COUNT ((size_t)4)
#endif

#ifndef HZ6_OBJECT_DESCRIPTOR_CAPACITY
#define HZ6_OBJECT_DESCRIPTOR_CAPACITY ((size_t)64)
#endif

#ifndef HZ6_ALLOCATOR_VISIBILITY_CAPACITY
#define HZ6_ALLOCATOR_VISIBILITY_CAPACITY ((size_t)256)
#endif

#ifndef HZ6_SOURCE_BLOCK_CAPACITY
#define HZ6_SOURCE_BLOCK_CAPACITY ((size_t)16)
#endif

#ifndef HZ6_SOURCE_RUN_MAX_SLOTS
#define HZ6_SOURCE_RUN_MAX_SLOTS ((size_t)4096)
#endif

#ifndef HZ6_SOURCE_RUN_BITMAP_WORDS
#define HZ6_SOURCE_RUN_BITMAP_WORDS \
  ((size_t)((HZ6_SOURCE_RUN_MAX_SLOTS + 63u) / 64u))
#endif

#ifndef HZ6_SOURCE_RUN_REUSE_L1
#define HZ6_SOURCE_RUN_REUSE_L1 0
#endif

#ifndef HZ6_SOURCE_RUN_SLOT_LOOKUP_L1
#define HZ6_SOURCE_RUN_SLOT_LOOKUP_L1 0
#endif

#ifndef HZ6_SOURCE_RUN_RECLAIM_DESCRIPTOR_L1
#define HZ6_SOURCE_RUN_RECLAIM_DESCRIPTOR_L1 0
#endif

#ifndef HZ6_SOURCE_RUN_RECLAIM_SAME_CLASS_L1
#define HZ6_SOURCE_RUN_RECLAIM_SAME_CLASS_L1 0
#endif

#ifndef HZ6_SOURCE_BLOCK_ROUTE_DRYRUN_L1
#define HZ6_SOURCE_BLOCK_ROUTE_DRYRUN_L1 0
#endif

#ifndef HZ6_SOURCE_BLOCK_ROUTE_SLOT_DESCRIPTOR_MAP_L1
#define HZ6_SOURCE_BLOCK_ROUTE_SLOT_DESCRIPTOR_MAP_L1 0
#endif

#ifndef HZ6_SOURCE_BLOCK_ROUTE_RANGE_INDEX_L1
#define HZ6_SOURCE_BLOCK_ROUTE_RANGE_INDEX_L1 0
#endif

#ifndef HZ6_SOURCE_BLOCK_ROUTE_RANGE_INDEX_GRANULARITY
#define HZ6_SOURCE_BLOCK_ROUTE_RANGE_INDEX_GRANULARITY ((size_t)4096)
#endif

#ifndef HZ6_SOURCE_BLOCK_ROUTE_RANGE_INDEX_CAPACITY
#define HZ6_SOURCE_BLOCK_ROUTE_RANGE_INDEX_CAPACITY \
  ((size_t)(HZ6_SOURCE_BLOCK_CAPACITY * 16u))
#endif

#ifndef HZ6_SOURCE_BLOCK_NO_ROUTE_BACKPTR_L1
#define HZ6_SOURCE_BLOCK_NO_ROUTE_BACKPTR_L1 0
#endif

#ifndef HZ6_SOURCE_BLOCK_PACKED_FLAGS_L1
#define HZ6_SOURCE_BLOCK_PACKED_FLAGS_L1 0
#endif

#ifndef HZ6_DESCRIPTORLESS_FRONTCACHE_L1
#define HZ6_DESCRIPTORLESS_FRONTCACHE_L1 0
#endif

#ifndef HZ6_DESCRIPTOR_MATERIALIZE_RESERVE_L1
#define HZ6_DESCRIPTOR_MATERIALIZE_RESERVE_L1 0
#endif

#ifndef HZ6_DESCRIPTORLESS_OVER_CAP_ONLY_L1
#define HZ6_DESCRIPTORLESS_OVER_CAP_ONLY_L1 0
#endif

#ifndef HZ6_DESCRIPTOR_COLD_GOV_L1
#define HZ6_DESCRIPTOR_COLD_GOV_L1 0
#endif

#ifndef HZ6_DESCRIPTOR_AVAIL_COUNT_L1
#define HZ6_DESCRIPTOR_AVAIL_COUNT_L1 0
#endif

#ifndef HZ6_THIN_DESCRIPTOR_L1
#define HZ6_THIN_DESCRIPTOR_L1 0
#endif

#ifndef HZ6_DESCRIPTOR_NO_BACKPTR_L1
#define HZ6_DESCRIPTOR_NO_BACKPTR_L1 0
#endif

#ifndef HZ6_DESCRIPTOR_SIDE_OWNER16_L1
#define HZ6_DESCRIPTOR_SIDE_OWNER16_L1 0
#endif

#ifndef HZ6_DESCRIPTOR_STORAGE_OWNER16_L1
#define HZ6_DESCRIPTOR_STORAGE_OWNER16_L1 0
#endif

#ifndef HZ6_OWNER_SOURCE_SIDE_META_DRYRUN
#define HZ6_OWNER_SOURCE_SIDE_META_DRYRUN 0
#endif

#ifndef HZ6_OWNER_SOURCE_SIDE_META_L2
#define HZ6_OWNER_SOURCE_SIDE_META_L2 0
#endif

#ifndef HZ6_DESCRIPTOR_COLD_SOURCE_CAPACITY
#if HZ6_THIN_DESCRIPTOR_L1
#define HZ6_DESCRIPTOR_COLD_SOURCE_CAPACITY ((size_t)4096)
#else
#define HZ6_DESCRIPTOR_COLD_SOURCE_CAPACITY ((size_t)0)
#endif
#endif

#ifndef HZ6_DESCRIPTOR_COLD_GOV_DETACH_BUDGET
#define HZ6_DESCRIPTOR_COLD_GOV_DETACH_BUDGET ((size_t)256)
#endif

#ifndef HZ6_SOURCE_ADMISSION_NO_STARVATION_BOOST
#define HZ6_SOURCE_ADMISSION_NO_STARVATION_BOOST 0
#endif

#ifndef HZ6_ROUTE_TOMBSTONE_COMPACT_L1
#define HZ6_ROUTE_TOMBSTONE_COMPACT_L1 0
#endif

#ifndef HZ6_ROUTE_TOMBSTONE_COMPACT_MIN
#define HZ6_ROUTE_TOMBSTONE_COMPACT_MIN ((size_t)1024)
#endif

#ifndef HZ6_ROUTE_RETAINED_OVERFLOW_L1
#define HZ6_ROUTE_RETAINED_OVERFLOW_L1 0
#endif

#ifndef HZ6_ROUTE_DOUBLE_HASH_L1
#define HZ6_ROUTE_DOUBLE_HASH_L1 0
#endif

#ifndef HZ6_ROUTE_HASH_XOR_FOLD_L1
#define HZ6_ROUTE_HASH_XOR_FOLD_L1 0
#endif

#ifndef HZ6_ROUTE_LINEAR_WRAP_L1
#define HZ6_ROUTE_LINEAR_WRAP_L1 0
#endif

#ifndef HZ6_ROUTE_LOOP_CARRY_L1
#define HZ6_ROUTE_LOOP_CARRY_L1 0
#endif

#ifndef HZ6_ROUTE_PACKED_META_L1
#define HZ6_ROUTE_PACKED_META_L1 0
#endif

#ifndef HZ6_ROUTE_BYTES16_MINUS1_L2
#define HZ6_ROUTE_BYTES16_MINUS1_L2 0
#endif

#ifndef HZ6_FRONT_CACHE_CLASS_COUNT
#define HZ6_FRONT_CACHE_CLASS_COUNT 16u
#endif

#ifndef HZ6_FRONT_CACHE_BIN_CAPACITY
#define HZ6_FRONT_CACHE_BIN_CAPACITY ((size_t)8)
#endif

#ifndef HZ6_DIAGNOSTIC_PROBES
#define HZ6_DIAGNOSTIC_PROBES 0
#endif

#ifndef HZ6_TOY_SMALL_HOTPATH_DIAG_L1
#define HZ6_TOY_SMALL_HOTPATH_DIAG_L1 0
#endif

#ifndef HZ6_TOY_SMALL_ACTIVE_FREE_MAP_L1
#define HZ6_TOY_SMALL_ACTIVE_FREE_MAP_L1 0
#endif

#ifndef HZ6_TOY_SMALL_ACTIVE_FREE_MAP_CAPACITY
#define HZ6_TOY_SMALL_ACTIVE_FREE_MAP_CAPACITY ((size_t)8192)
#endif

#ifndef HZ6_TOY_SMALL_ACTIVE_FREE_MAP_PROBE_LIMIT
#define HZ6_TOY_SMALL_ACTIVE_FREE_MAP_PROBE_LIMIT ((size_t)4)
#endif

#ifndef HZ6_VISIBLE_FIRST_FREE_L1
#define HZ6_VISIBLE_FIRST_FREE_L1 0
#endif

#ifndef HZ6_NEGATIVE_FILTER_L1
#define HZ6_NEGATIVE_FILTER_L1 0
#endif

#ifndef HZ6_SHARED_ROUTE_DIRECTORY_L1
#define HZ6_SHARED_ROUTE_DIRECTORY_L1 0
#endif

#ifndef HZ6_SHARED_ROUTE_DIRECTORY_FIRST_L1
#define HZ6_SHARED_ROUTE_DIRECTORY_FIRST_L1 0
#endif

#ifndef HZ6_ELASTIC_ROUTE_OVERFLOW_L1
#define HZ6_ELASTIC_ROUTE_OVERFLOW_L1 0
#endif

#ifndef HZ6_ELASTIC_DESCRIPTOR_OVERFLOW_L1
#define HZ6_ELASTIC_DESCRIPTOR_OVERFLOW_L1 0
#endif

#ifndef HZ6_ELASTIC_SOURCE_BLOCK_OVERFLOW_L1
#define HZ6_ELASTIC_SOURCE_BLOCK_OVERFLOW_L1 0
#endif

#ifndef HZ6_ELASTIC_SOURCE_BLOCK_LOCALIZE_DRYRUN_L1
#define HZ6_ELASTIC_SOURCE_BLOCK_LOCALIZE_DRYRUN_L1 0
#endif

#ifndef HZ6_ELASTIC_SOURCE_RUN_LOCALITY_DRYRUN_L1
#define HZ6_ELASTIC_SOURCE_RUN_LOCALITY_DRYRUN_L1 0
#endif

#ifndef HZ6_ELASTIC_DEPOT_SOURCE_RUN_META_L1
#define HZ6_ELASTIC_DEPOT_SOURCE_RUN_META_L1 0
#endif

#ifndef HZ6_ELASTIC_SLOT_OWNER_LOCALITY_DRYRUN_L1
#define HZ6_ELASTIC_SLOT_OWNER_LOCALITY_DRYRUN_L1 0
#endif

#ifndef HZ6_ELASTIC_SLOT_OWNER_SPARSE_META_L1
#define HZ6_ELASTIC_SLOT_OWNER_SPARSE_META_L1 0
#endif

#ifndef HZ6_ELASTIC_SLOT_OWNER_CONSUMER_DRYRUN_L1
#define HZ6_ELASTIC_SLOT_OWNER_CONSUMER_DRYRUN_L1 0
#endif

#ifndef HZ6_ELASTIC_SLOT_OWNER_LOGICAL_FASTPATH_L1
#define HZ6_ELASTIC_SLOT_OWNER_LOGICAL_FASTPATH_L1 0
#endif

#ifndef HZ6_ELASTIC_DEPOT_DRAIN_DRYRUN_L1
#define HZ6_ELASTIC_DEPOT_DRAIN_DRYRUN_L1 0
#endif

#ifndef HZ6_ELASTIC_DEPOT_SLOT_LOCALIZE_L1
#define HZ6_ELASTIC_DEPOT_SLOT_LOCALIZE_L1 0
#endif

#ifndef HZ6_ELASTIC_DEPOT_SLOT_TRANSFER_SCOPED_L1
#define HZ6_ELASTIC_DEPOT_SLOT_TRANSFER_SCOPED_L1 0
#endif

#ifndef HZ6_ELASTIC_DEPOT_DESCRIPTOR_REHOME_DRYRUN_L1
#define HZ6_ELASTIC_DEPOT_DESCRIPTOR_REHOME_DRYRUN_L1 0
#endif

#ifndef HZ6_ELASTIC_DEPOT_ROUTE_REPLACE_DRYRUN_L1
#define HZ6_ELASTIC_DEPOT_ROUTE_REPLACE_DRYRUN_L1 0
#endif

#ifndef HZ6_ELASTIC_DEPOT_DESCRIPTOR_REHOME_L1
#define HZ6_ELASTIC_DEPOT_DESCRIPTOR_REHOME_L1 0
#endif

#ifndef HZ6_ELASTIC_DEPOT_DESCRIPTOR_REHOME_BUDGET_L1
#define HZ6_ELASTIC_DEPOT_DESCRIPTOR_REHOME_BUDGET_L1 0
#endif

#ifndef HZ6_ELASTIC_DEPOT_DESCRIPTOR_REHOME_BUDGET
#define HZ6_ELASTIC_DEPOT_DESCRIPTOR_REHOME_BUDGET ((size_t)2048)
#endif

#ifndef HZ6_OWNER_EQUAL_CALLSITE_DRYRUN_L1
#define HZ6_OWNER_EQUAL_CALLSITE_DRYRUN_L1 0
#endif

#ifndef HZ6_FREE_LOCAL_CACHE_OWNER_PREDICATE_DRYRUN_L0
#define HZ6_FREE_LOCAL_CACHE_OWNER_PREDICATE_DRYRUN_L0 0
#endif

#ifndef HZ6_DEPOT_DESCRIPTOR_OWNER_EQUAL_FASTPATH_L1
#define HZ6_DEPOT_DESCRIPTOR_OWNER_EQUAL_FASTPATH_L1 0
#endif

#ifndef HZ6_DESCRIPTOR_DEPOT_OWNER_DIRECT_FASTPATH_L1
#define HZ6_DESCRIPTOR_DEPOT_OWNER_DIRECT_FASTPATH_L1 0
#endif

#ifndef HZ6_ELASTIC_SLOT_OWNER_SPARSE_CAPACITY
#define HZ6_ELASTIC_SLOT_OWNER_SPARSE_CAPACITY ((size_t)131072)
#endif

#ifndef HZ6_ELASTIC_DESCRIPTOR_DEPOT_CAPACITY
#define HZ6_ELASTIC_DESCRIPTOR_DEPOT_CAPACITY ((size_t)196608)
#endif

#ifndef HZ6_ELASTIC_SOURCE_BLOCK_DEPOT_CAPACITY
#define HZ6_ELASTIC_SOURCE_BLOCK_DEPOT_CAPACITY ((size_t)16384)
#endif

#ifndef HZ6_SHARED_ROUTE_DIRECTORY_CAPACITY
#define HZ6_SHARED_ROUTE_DIRECTORY_CAPACITY ((size_t)262144)
#endif

#ifndef HZ6_OWNER_LOCALITY_INDEX_CAPACITY
#define HZ6_OWNER_LOCALITY_INDEX_CAPACITY HZ6_SHARED_ROUTE_DIRECTORY_CAPACITY
#endif

#ifndef HZ6_OWNER_LOCALITY_INDEX_L1
#define HZ6_OWNER_LOCALITY_INDEX_L1 0
#endif

#ifndef HZ6_LOCAL_EXACT_FIRST_FREE_L1
#define HZ6_LOCAL_EXACT_FIRST_FREE_L1 0
#endif

#ifndef HZ6_LOCAL_CACHE_DIRECT_FREE_L1
#define HZ6_LOCAL_CACHE_DIRECT_FREE_L1 0
#endif

#ifndef HZ6_LOCAL_CACHE_DIRECT_ALLOC_L1
#define HZ6_LOCAL_CACHE_DIRECT_ALLOC_L1 0
#endif

#ifndef HZ6_LOCAL_CACHE_DIRECT_REUSE_L1
#define HZ6_LOCAL_CACHE_DIRECT_REUSE_L1 0
#endif

#ifndef HZ6_LOCAL_CACHE_DIRECT_MAX_CLASS
#define HZ6_LOCAL_CACHE_DIRECT_MAX_CLASS HZ6_FRONT_CACHE_CLASS_COUNT
#endif

#ifndef HZ6_LOCAL_CACHE_TRUSTED_OWNER_L1
/* Candidate-only same-allocator local-cache shortcut.  Callers must already be
 * on an allocator-owned frontcache path or have checked local ownership. */
#define HZ6_LOCAL_CACHE_TRUSTED_OWNER_L1 0
#endif

#ifndef HZ6_SAME_OWNER_FAST_L1
#define HZ6_SAME_OWNER_FAST_L1 0
#endif

#ifndef HZ6_FRONTCACHE_SPILL_ON_DESCRIPTOR_EXHAUSTION
#define HZ6_FRONTCACHE_SPILL_ON_DESCRIPTOR_EXHAUSTION 0
#endif

#ifndef HZ6_FRONTCACHE_BORROW_LARGER_ON_CLASS_MISS
#define HZ6_FRONTCACHE_BORROW_LARGER_ON_CLASS_MISS 0
#endif

#ifndef HZ6_FRONTCACHE_CAP_ON_FREE
#define HZ6_FRONTCACHE_CAP_ON_FREE 0
#endif

#ifndef HZ6_SOURCE_BLOCK_ACTIVATION_ROUTE_REPAIR_L1
/* Diagnostic-only repair probe.  Do not promote as-is: the current repair path
 * is intentionally narrow and registers repaired source-run slots as TOY. */
#define HZ6_SOURCE_BLOCK_ACTIVATION_ROUTE_REPAIR_L1 0
#endif

#ifndef HZ6_SOURCE_BLOCK_RELEASE_LIVE_GUARD_L1
/* Diagnostic-only lifetime guard for source-block release investigations. */
#define HZ6_SOURCE_BLOCK_RELEASE_LIVE_GUARD_L1 0
#endif

#ifndef HZ6_SOURCE_BLOCK_ROUTE_BEHAVIOR_L1
/* Experimental source-run free route shortcut.  Requires range-index and
 * slot-descriptor map; exact route remains the fallback/control path. */
#define HZ6_SOURCE_BLOCK_ROUTE_BEHAVIOR_L1 0
#endif

#ifndef HZ6_SOURCE_BLOCK_ROUTE_SLOT_DESCRIPTOR_MAP_DYNAMIC_L1
/* Store source-run slot descriptor maps only for active runs instead of
 * embedding HZ6_SOURCE_RUN_MAX_SLOTS entries in every source block. */
#define HZ6_SOURCE_BLOCK_ROUTE_SLOT_DESCRIPTOR_MAP_DYNAMIC_L1 0
#endif

#ifndef HZ6_FRONTCACHE_PACKED_META_L1
#define HZ6_FRONTCACHE_PACKED_META_L1 0
#endif

#endif
