#ifndef HZ6_CONFIG_H
#define HZ6_CONFIG_H

#include <stddef.h>

#ifndef HZ6_ROUTE_TABLE_CAPACITY
#define HZ6_ROUTE_TABLE_CAPACITY ((size_t)64)
#endif

#ifndef HZ6_ROUTE_PAGE_GRANULARITY
#define HZ6_ROUTE_PAGE_GRANULARITY ((size_t)4096)
#endif

#ifndef HZ6_TRANSFER_CACHE_CAPACITY
#define HZ6_TRANSFER_CACHE_CAPACITY ((size_t)64)
#endif

#ifndef HZ6_TRANSFER_SHARD_COUNT
#define HZ6_TRANSFER_SHARD_COUNT ((size_t)4)
#endif

#ifndef HZ6_OBJECT_DESCRIPTOR_CAPACITY
#define HZ6_OBJECT_DESCRIPTOR_CAPACITY ((size_t)64)
#endif

#ifndef HZ6_ALLOCATOR_VISIBILITY_CAPACITY
#define HZ6_ALLOCATOR_VISIBILITY_CAPACITY ((size_t)256)
#endif

#ifndef HZ6_SOURCE_BLOCK_CAPACITY
#define HZ6_SOURCE_BLOCK_CAPACITY ((size_t)16)
#endif

#ifndef HZ6_SOURCE_RUN_MAX_SLOTS
#define HZ6_SOURCE_RUN_MAX_SLOTS ((size_t)4096)
#endif

#ifndef HZ6_SOURCE_RUN_BITMAP_WORDS
#define HZ6_SOURCE_RUN_BITMAP_WORDS \
  ((size_t)((HZ6_SOURCE_RUN_MAX_SLOTS + 63u) / 64u))
#endif

#ifndef HZ6_SOURCE_RUN_REUSE_L1
#define HZ6_SOURCE_RUN_REUSE_L1 0
#endif

#ifndef HZ6_SOURCE_RUN_RECLAIM_DESCRIPTOR_L1
#define HZ6_SOURCE_RUN_RECLAIM_DESCRIPTOR_L1 0
#endif

#ifndef HZ6_SOURCE_RUN_RECLAIM_SAME_CLASS_L1
#define HZ6_SOURCE_RUN_RECLAIM_SAME_CLASS_L1 0
#endif

#ifndef HZ6_DESCRIPTORLESS_FRONTCACHE_L1
#define HZ6_DESCRIPTORLESS_FRONTCACHE_L1 0
#endif

#ifndef HZ6_DESCRIPTOR_MATERIALIZE_RESERVE_L1
#define HZ6_DESCRIPTOR_MATERIALIZE_RESERVE_L1 0
#endif

#ifndef HZ6_DESCRIPTORLESS_OVER_CAP_ONLY_L1
#define HZ6_DESCRIPTORLESS_OVER_CAP_ONLY_L1 0
#endif

#ifndef HZ6_DESCRIPTOR_COLD_GOV_L1
#define HZ6_DESCRIPTOR_COLD_GOV_L1 0
#endif

#ifndef HZ6_DESCRIPTOR_COLD_GOV_DETACH_BUDGET
#define HZ6_DESCRIPTOR_COLD_GOV_DETACH_BUDGET ((size_t)256)
#endif

#ifndef HZ6_SOURCE_ADMISSION_NO_STARVATION_BOOST
#define HZ6_SOURCE_ADMISSION_NO_STARVATION_BOOST 0
#endif

#ifndef HZ6_FRONT_CACHE_CLASS_COUNT
#define HZ6_FRONT_CACHE_CLASS_COUNT 16u
#endif

#ifndef HZ6_FRONT_CACHE_BIN_CAPACITY
#define HZ6_FRONT_CACHE_BIN_CAPACITY ((size_t)8)
#endif

#ifndef HZ6_DIAGNOSTIC_PROBES
#define HZ6_DIAGNOSTIC_PROBES 0
#endif

#ifndef HZ6_VISIBLE_FIRST_FREE_L1
#define HZ6_VISIBLE_FIRST_FREE_L1 0
#endif

#ifndef HZ6_NEGATIVE_FILTER_L1
#define HZ6_NEGATIVE_FILTER_L1 0
#endif

#ifndef HZ6_SHARED_ROUTE_DIRECTORY_L1
#define HZ6_SHARED_ROUTE_DIRECTORY_L1 0
#endif

#ifndef HZ6_SHARED_ROUTE_DIRECTORY_FIRST_L1
#define HZ6_SHARED_ROUTE_DIRECTORY_FIRST_L1 0
#endif

#ifndef HZ6_SHARED_ROUTE_DIRECTORY_CAPACITY
#define HZ6_SHARED_ROUTE_DIRECTORY_CAPACITY ((size_t)262144)
#endif

#ifndef HZ6_OWNER_LOCALITY_INDEX_CAPACITY
#define HZ6_OWNER_LOCALITY_INDEX_CAPACITY HZ6_SHARED_ROUTE_DIRECTORY_CAPACITY
#endif

#ifndef HZ6_OWNER_LOCALITY_INDEX_L1
#define HZ6_OWNER_LOCALITY_INDEX_L1 0
#endif

#ifndef HZ6_FRONTCACHE_SPILL_ON_DESCRIPTOR_EXHAUSTION
#define HZ6_FRONTCACHE_SPILL_ON_DESCRIPTOR_EXHAUSTION 0
#endif

#ifndef HZ6_FRONTCACHE_BORROW_LARGER_ON_CLASS_MISS
#define HZ6_FRONTCACHE_BORROW_LARGER_ON_CLASS_MISS 0
#endif

#ifndef HZ6_FRONTCACHE_CAP_ON_FREE
#define HZ6_FRONTCACHE_CAP_ON_FREE 0
#endif

#endif
