#ifndef HZ6_CONFIG_H
#define HZ6_CONFIG_H

#include <stddef.h>

#ifndef HZ6_ROUTE_TABLE_CAPACITY
#define HZ6_ROUTE_TABLE_CAPACITY ((size_t)64)
#endif

#ifndef HZ6_ROUTE_PAGE_GRANULARITY
#define HZ6_ROUTE_PAGE_GRANULARITY ((size_t)4096)
#endif

#ifndef HZ6_TRANSFER_CACHE_CAPACITY
#define HZ6_TRANSFER_CACHE_CAPACITY ((size_t)64)
#endif

#ifndef HZ6_TRANSFER_SHARD_COUNT
#define HZ6_TRANSFER_SHARD_COUNT ((size_t)4)
#endif

#ifndef HZ6_OBJECT_DESCRIPTOR_CAPACITY
#define HZ6_OBJECT_DESCRIPTOR_CAPACITY ((size_t)64)
#endif

#ifndef HZ6_ALLOCATOR_VISIBILITY_CAPACITY
#define HZ6_ALLOCATOR_VISIBILITY_CAPACITY ((size_t)256)
#endif

#ifndef HZ6_SOURCE_BLOCK_CAPACITY
#define HZ6_SOURCE_BLOCK_CAPACITY ((size_t)16)
#endif

#ifndef HZ6_FRONT_CACHE_CLASS_COUNT
#define HZ6_FRONT_CACHE_CLASS_COUNT 16u
#endif

#ifndef HZ6_FRONT_CACHE_BIN_CAPACITY
#define HZ6_FRONT_CACHE_BIN_CAPACITY ((size_t)8)
#endif

#ifndef HZ6_DIAGNOSTIC_PROBES
#define HZ6_DIAGNOSTIC_PROBES 0
#endif

#ifndef HZ6_FRONTCACHE_SPILL_ON_DESCRIPTOR_EXHAUSTION
#define HZ6_FRONTCACHE_SPILL_ON_DESCRIPTOR_EXHAUSTION 0
#endif

#endif
