#ifndef HZ5_POLICY_CONFIG_H
#define HZ5_POLICY_CONFIG_H

#ifndef HZ5_POLICY_PAGE_SIZE
#define HZ5_POLICY_PAGE_SIZE ((size_t)4096)
#endif

#ifndef HZ5_POLICY_MIN_ALIGN
#define HZ5_POLICY_MIN_ALIGN ((size_t)16)
#endif

#ifndef BENCHLAB_HZ5_P16_WRAPPER_64K_A8192
#define BENCHLAB_HZ5_P16_WRAPPER_64K_A8192 0
#endif

#ifndef BENCHLAB_HZ5_P17_PAGEBIN_64K_A8192
#define BENCHLAB_HZ5_P17_PAGEBIN_64K_A8192 0
#endif

#ifndef BENCHLAB_HZ5_P24_RAW64K_A8192
#define BENCHLAB_HZ5_P24_RAW64K_A8192 0
#endif

#ifndef BENCHLAB_HZ5_P25_HZ4LOWPAGE64K_A8192
#define BENCHLAB_HZ5_P25_HZ4LOWPAGE64K_A8192 0
#endif

#ifndef BENCHLAB_HZ5_P25_SPAN_CACHE64K_A8192
#define BENCHLAB_HZ5_P25_SPAN_CACHE64K_A8192 0
#endif

#ifndef BENCHLAB_HZ5_P43_UNSAFE_NO_LOOKUP
#define BENCHLAB_HZ5_P43_UNSAFE_NO_LOOKUP 0
#endif

#ifndef BENCHLAB_HZ5_P43_TRUST_WRAPPER_SOURCE
#define BENCHLAB_HZ5_P43_TRUST_WRAPPER_SOURCE 0
#endif

#ifndef BENCHLAB_HZ5_P43_DECODED_RAW_LOOKUP
#define BENCHLAB_HZ5_P43_DECODED_RAW_LOOKUP 0
#endif

#ifndef BENCHLAB_HZ5_P43_WRAPPER_TOKEN
#define BENCHLAB_HZ5_P43_WRAPPER_TOKEN 0
#endif

#ifndef BENCHLAB_HZ5_P43_WRAPPER_TOKEN_BRIDGE
#define BENCHLAB_HZ5_P43_WRAPPER_TOKEN_BRIDGE 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_P25_BRIDGE_ATTR
#define BENCHLAB_HZ5_LINUX_P25_BRIDGE_ATTR 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P
#define BENCHLAB_HZ5_LINUX_LOCAL2P 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_SMALLFRONT_S1
#define BENCHLAB_HZ5_LINUX_SMALLFRONT_S1 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P_TLS_PACKED
#define BENCHLAB_HZ5_LINUX_LOCAL2P_TLS_PACKED 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P_DIRECT_ROUTE
#define BENCHLAB_HZ5_LINUX_LOCAL2P_DIRECT_ROUTE 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P_DIRECT_INIT
#define BENCHLAB_HZ5_LINUX_LOCAL2P_DIRECT_INIT 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P_RAW_BYTES
#define BENCHLAB_HZ5_LINUX_LOCAL2P_RAW_BYTES ((size_t)131072)
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P_ALIGN
#define BENCHLAB_HZ5_LINUX_LOCAL2P_ALIGN ((size_t)8192)
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P_TLS_CAP
#define BENCHLAB_HZ5_LINUX_LOCAL2P_TLS_CAP ((size_t)1)
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P_GLOBAL_CAP
#define BENCHLAB_HZ5_LINUX_LOCAL2P_GLOBAL_CAP ((size_t)1024)
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P_NO_COOKIE
#define BENCHLAB_HZ5_LINUX_LOCAL2P_NO_COOKIE 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P_NO_CAS
#define BENCHLAB_HZ5_LINUX_LOCAL2P_NO_CAS 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P_OWNER_INBOX
#define BENCHLAB_HZ5_LINUX_LOCAL2P_OWNER_INBOX 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P_REMOTE_BATCH
#define BENCHLAB_HZ5_LINUX_LOCAL2P_REMOTE_BATCH 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P_REMOTE_BATCH_CAP
#define BENCHLAB_HZ5_LINUX_LOCAL2P_REMOTE_BATCH_CAP 16u
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P_OBJECT_NODE
#define BENCHLAB_HZ5_LINUX_LOCAL2P_OBJECT_NODE 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P_SAME_OWNER_FAST_STATE
#define BENCHLAB_HZ5_LINUX_LOCAL2P_SAME_OWNER_FAST_STATE 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P_ROUTE_COOKIE
#define BENCHLAB_HZ5_LINUX_LOCAL2P_ROUTE_COOKIE 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P_REUSE_STATE_ONLY
#define BENCHLAB_HZ5_LINUX_LOCAL2P_REUSE_STATE_ONLY 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P_SLIM_CHECK
#define BENCHLAB_HZ5_LINUX_LOCAL2P_SLIM_CHECK 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P_FAST_COOKIE
#define BENCHLAB_HZ5_LINUX_LOCAL2P_FAST_COOKIE 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P_FREE_FIRST
#define BENCHLAB_HZ5_LINUX_LOCAL2P_FREE_FIRST 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P_TLS_FAST_RETURN
#define BENCHLAB_HZ5_LINUX_LOCAL2P_TLS_FAST_RETURN 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P_SINGLE_SLOT_TLS
#define BENCHLAB_HZ5_LINUX_LOCAL2P_SINGLE_SLOT_TLS 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P_LOCAL_OVERFLOW_GLOBAL
#define BENCHLAB_HZ5_LINUX_LOCAL2P_LOCAL_OVERFLOW_GLOBAL 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_LOCAL2P_RETAIN_ARRAY
#define BENCHLAB_HZ5_LINUX_LOCAL2P_RETAIN_ARRAY 0
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P
#define BENCHLAB_HZ5_WIN_LOCAL2P 0
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_RAW_BYTES
#define BENCHLAB_HZ5_WIN_LOCAL2P_RAW_BYTES ((size_t)131072)
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_ALIGN
#define BENCHLAB_HZ5_WIN_LOCAL2P_ALIGN ((size_t)8192)
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_TLS_CAP
#define BENCHLAB_HZ5_WIN_LOCAL2P_TLS_CAP ((size_t)1)
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_GLOBAL_CAP
#define BENCHLAB_HZ5_WIN_LOCAL2P_GLOBAL_CAP ((size_t)1024)
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_DIRECT_ROUTE
#define BENCHLAB_HZ5_WIN_LOCAL2P_DIRECT_ROUTE 1
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_REMOTE_BATCH
#define BENCHLAB_HZ5_WIN_LOCAL2P_REMOTE_BATCH 0
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_RETAIN_ARRAY
#define BENCHLAB_HZ5_WIN_LOCAL2P_RETAIN_ARRAY 0
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_FAST_COOKIE
#define BENCHLAB_HZ5_WIN_LOCAL2P_FAST_COOKIE 0
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_OBJECT_NODE
#define BENCHLAB_HZ5_WIN_LOCAL2P_OBJECT_NODE 0
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_SAME_OWNER_FAST_STATE
#define BENCHLAB_HZ5_WIN_LOCAL2P_SAME_OWNER_FAST_STATE 0
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_ROUTE_COOKIE
#define BENCHLAB_HZ5_WIN_LOCAL2P_ROUTE_COOKIE 0
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_ROUTE_HEADER_GUARD
#define BENCHLAB_HZ5_WIN_LOCAL2P_ROUTE_HEADER_GUARD 0
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_SIDECAR_ROUTE
#define BENCHLAB_HZ5_WIN_LOCAL2P_SIDECAR_ROUTE 0
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_SIDECAR_FIRST
#define BENCHLAB_HZ5_WIN_LOCAL2P_SIDECAR_FIRST 0
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_SIDECAR_DIRECT_TABLE
#define BENCHLAB_HZ5_WIN_LOCAL2P_SIDECAR_DIRECT_TABLE 0
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_SIDECAR_ASSOC_TABLE
#define BENCHLAB_HZ5_WIN_LOCAL2P_SIDECAR_ASSOC_TABLE 0
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_SIDECAR_ASSOC_WAYS
#define BENCHLAB_HZ5_WIN_LOCAL2P_SIDECAR_ASSOC_WAYS 4u
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_SIDECAR_TABLE_SIZE
#define BENCHLAB_HZ5_WIN_LOCAL2P_SIDECAR_TABLE_SIZE 4096u
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_SIDECAR_METADATA_ONLY
#define BENCHLAB_HZ5_WIN_LOCAL2P_SIDECAR_METADATA_ONLY 0
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_REUSE_STATE_ONLY
#define BENCHLAB_HZ5_WIN_LOCAL2P_REUSE_STATE_ONLY 0
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_TLS_FAST_RETURN
#define BENCHLAB_HZ5_WIN_LOCAL2P_TLS_FAST_RETURN 0
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_REMOTE_BATCH_CAP
#define BENCHLAB_HZ5_WIN_LOCAL2P_REMOTE_BATCH_CAP 16u
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_REMOTE_BATCH_SLOTS
#define BENCHLAB_HZ5_WIN_LOCAL2P_REMOTE_BATCH_SLOTS 1u
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_REMOTE_BATCH_SWITCH_FLUSH_MIN
#define BENCHLAB_HZ5_WIN_LOCAL2P_REMOTE_BATCH_SWITCH_FLUSH_MIN 0u
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_REMOTE_OWNER_GATE
#define BENCHLAB_HZ5_WIN_LOCAL2P_REMOTE_OWNER_GATE 0
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_REMOTE_DIRECT_INDEX
#define BENCHLAB_HZ5_WIN_LOCAL2P_REMOTE_DIRECT_INDEX 0
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_REMOTE_ASSOC_LRU
#define BENCHLAB_HZ5_WIN_LOCAL2P_REMOTE_ASSOC_LRU 0
#endif

#ifndef BENCHLAB_HZ5_WIN_LOCAL2P_INBOX_FAST_ACTIVATE
#define BENCHLAB_HZ5_WIN_LOCAL2P_INBOX_FAST_ACTIVATE 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_P25_BRIDGE_ATTR_NO_CAS
#define BENCHLAB_HZ5_LINUX_P25_BRIDGE_ATTR_NO_CAS 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_P25_BRIDGE_ATTR_NO_COOKIE
#define BENCHLAB_HZ5_LINUX_P25_BRIDGE_ATTR_NO_COOKIE 0
#endif

#ifndef BENCHLAB_HZ5_LINUX_P25_BRIDGE_ATTR_READONLY_STATE
#define BENCHLAB_HZ5_LINUX_P25_BRIDGE_ATTR_READONLY_STATE 0
#endif

#ifndef BENCHLAB_HZ5_P43_PREPARED_RELEASE
#define BENCHLAB_HZ5_P43_PREPARED_RELEASE 0
#endif

#ifndef BENCHLAB_HZ5_P43_PREPARED_BRIDGE
#define BENCHLAB_HZ5_P43_PREPARED_BRIDGE 0
#endif

#define HZ5_POLICY_P43_PREPARED_ANY \
  (BENCHLAB_HZ5_P43_PREPARED_RELEASE || \
   BENCHLAB_HZ5_P43_PREPARED_BRIDGE)

#ifndef BENCHLAB_HZ5_NO_HZ3_FALLBACK
#define BENCHLAB_HZ5_NO_HZ3_FALLBACK 0
#endif

#ifndef BENCHLAB_HZ5_LAZY_HZ3_FALLBACK
#define BENCHLAB_HZ5_LAZY_HZ3_FALLBACK 0
#endif

#ifndef BENCHLAB_HZ5_STANDALONE_EXACT_ONLY
#define BENCHLAB_HZ5_STANDALONE_EXACT_ONLY 0
#endif

#ifndef BENCHLAB_HZ5_P12_ROUTE_SHADOW
#define BENCHLAB_HZ5_P12_ROUTE_SHADOW 0
#endif

#endif
