#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT_DIR="${OUT_DIR:-${ROOT_DIR}/hakozuna-hz6/out/linux/hz6_preload}"
CC_BIN="${CC:-cc}"
HZ6_DIR="${ROOT_DIR}/hakozuna-hz6"
HZ6_EXTRA_CFLAGS="${HZ6_EXTRA_CFLAGS:-}"
HZ6_PRELOAD_DEFAULT_CFLAGS="${HZ6_PRELOAD_DEFAULT_CFLAGS:-}"
HZ6_PRELOAD_ENABLE_MIDPAGE_BOUNDARY="${HZ6_PRELOAD_ENABLE_MIDPAGE_BOUNDARY:-1}"

HZ6_PRELOAD_SELECTED_CFLAGS=(
  -DHZ6_ROUTE_TABLE_CAPACITY=65536
  -DHZ6_OBJECT_DESCRIPTOR_CAPACITY=16384
  -DHZ6_SOURCE_BLOCK_CAPACITY=2048
  -DHZ6_FRONT_CACHE_BIN_CAPACITY=4096
  -DHZ6_TOY_SMALL_ACTIVE_FREE_MAP_CAPACITY=32768
  -DHZ6_TOY_SOURCE_BLOCK_BYTES=65536
  -DHZ6_MIDPAGE_RUN_BYTES=262144
  -DHZ6_MIDPAGE_ACTIVE_FREE_MAP_L2=1
  -DHZ6_MIDPAGE_ACTIVE_FREE_MAP_EXTERNAL_L2=1
  -DHZ6_MIDPAGE_ACTIVE_FREE_MAP_UNALIGNED_L2=1
  -DHZ6_MIDPAGE_ACTIVE_FREE_MAP_CAPACITY=16384
  -DHZ6_MIDPAGE_ACTIVE_FREE_MAP_PROBE_LIMIT=4
  -DHZ6_MIDPAGE_ALLOC_DESCRIPTOR_OUT_L1=1
  -DHZ6_PRELOAD_REALLOC_IN_PLACE_L1=1
  -DHZ6_LINUX_MMAP_RETAIN_L1=1
  -DHZ6_LINUX_MMAP_RETAIN_64K_STACK_L1=1
  -DHZ6_TOY_FULL_BLOCK_PREFILL_L1=1
  -DHZ6_TOY_FULL_BLOCK_PREFILL_MAX_SLOTS=128
  -DHZ6_ROUTE_TOMBSTONE_COMPACT_L1=1
  -DHZ6_ROUTE_HASH_XOR_FOLD_L1=1
  -DHZ6_ROUTE_LINEAR_WRAP_L1=1
  -DHZ6_ROUTE_LOOP_CARRY_L1=1

  # Explicit no-go/control defaults. Override with HZ6_EXTRA_CFLAGS for A/B.
  -DHZ6_LINUX_MMAP_RETAIN_TLS_L1=0
  -DHZ6_SOURCE_RUN_REUSE_L1=0
  -DHZ6_ROUTE_PACKED_META_L1=0
  -DHZ6_PRELOAD_FAST_FREE_L1=0
)

if [[ "${HZ6_PRELOAD_ENABLE_MIDPAGE_BOUNDARY}" -ne 0 ]]; then
  HZ6_PRELOAD_SELECTED_CFLAGS+=(
    -DHZ6_PRELOAD_MIDPAGE_MALLOC_SKIP_TRANSFER_L1=1
    -DHZ6_PRELOAD_MIDPAGE_MALLOC_BOUNDARY_NOINLINE_L1=1
  )
fi

mkdir -p "$OUT_DIR"

source "${HZ6_DIR}/linux/hz6_sources.sh"
HZ6_INCLUDES=("${HZ6_COMMON_INCLUDES[@]}" "${HZ6_DIR}/preload")

HZ6_PRELOAD_SOURCES=(
  "${HZ6_DIR}/preload/hz6_preload.c"
  "${HZ6_DIR}/preload/hz6_preload_real.c"
)
PRELOAD_SO="${OUT_DIR}/libhakozuna_hz6_preload.so"

HZ6_INCLUDE_FLAGS=()
for include_dir in "${HZ6_INCLUDES[@]}"; do
  HZ6_INCLUDE_FLAGS+=("-I${include_dir}")
done

HZ6_EXTRA_CFLAGS_ARRAY=()
if [[ -n "${HZ6_PRELOAD_DEFAULT_CFLAGS}" ]]; then
  # shellcheck disable=SC2206
  HZ6_EXTRA_CFLAGS_ARRAY=(${HZ6_PRELOAD_DEFAULT_CFLAGS})
else
  HZ6_EXTRA_CFLAGS_ARRAY=("${HZ6_PRELOAD_SELECTED_CFLAGS[@]}")
fi
if [[ -n "${HZ6_EXTRA_CFLAGS}" ]]; then
  # shellcheck disable=SC2206
  HZ6_EXTRA_CFLAGS_ARRAY+=(${HZ6_EXTRA_CFLAGS})
fi

command -v "$CC_BIN" >/dev/null 2>&1 || {
  echo "compiler not found in PATH: $CC_BIN" >&2
  exit 1
}

echo "[linux][hz6] building preload: ${PRELOAD_SO}"
"$CC_BIN" -std=c11 -Wall -Wextra -Werror -O2 -fPIC -shared \
  -D_GNU_SOURCE -D_POSIX_C_SOURCE=200809L -ftls-model=initial-exec \
  -fno-builtin \
  "${HZ6_EXTRA_CFLAGS_ARRAY[@]}" \
  "${HZ6_INCLUDE_FLAGS[@]}" \
  "${HZ6_LIB_SOURCES[@]}" \
  "${HZ6_PRELOAD_SOURCES[@]}" \
  -ldl -pthread \
  -o "$PRELOAD_SO"
echo "[linux][hz6] preload output: ${PRELOAD_SO}"
