#!/usr/bin/env bash

HZ6_PRELOAD_SELECTED_BASE_CFLAGS=(
  -DHZ6_ROUTE_TABLE_CAPACITY=32768
  -DHZ6_TRANSFER_CACHE_CAPACITY=256
  -DHZ6_PROFILE_SPEED_TRANSFER_CAPACITY=256
  -DHZ6_PROFILE_REMOTE_TRANSFER_CAPACITY=256
  -DHZ6_OBJECT_DESCRIPTOR_CAPACITY=8192
  -DHZ6_SOURCE_BLOCK_CAPACITY=1024
  -DHZ6_FRONT_CACHE_BIN_CAPACITY=4096
  -DHZ6_FRONT_CACHE_CLASS_STORAGE_TRIM_L1=1
  -DHZ6_FRONT_CACHE_CLASS4_STORAGE_CAPACITY=8192
  -DHZ6_FRONT_CACHE_CLASS5_STORAGE_CAPACITY=4096
  -DHZ6_TOY_SMALL_ACTIVE_FREE_MAP_CAPACITY=16384
  -DHZ6_TOY_SOURCE_BLOCK_BYTES=65536
  -DHZ6_MIDPAGE_RUN_BYTES=786432
  -DHZ6_MIDPAGE_32K_RUN_BYTES=2097152
  -DHZ6_MIDPAGE_ACTIVE_FREE_MAP_L2=1
  -DHZ6_MIDPAGE_ACTIVE_FREE_MAP_EXTERNAL_L2=1
  -DHZ6_MIDPAGE_ACTIVE_FREE_MAP_UNALIGNED_L2=1
  -DHZ6_MIDPAGE_ACTIVE_FREE_MAP_CAPACITY=8192
  -DHZ6_MIDPAGE_ACTIVE_FREE_MAP_PROBE_LIMIT=4
  -DHZ6_MIDPAGE_ACTIVE_MAP_MASK_INDEX_L1=1
  -DHZ6_MIDPAGE_ACTIVE_MAP_REGISTER_FAST_SLOT_L1=1
  -DHZ6_MIDPAGE_ALLOC_DESCRIPTOR_OUT_L1=1
  -DHZ6_PRELOAD_REALLOC_IN_PLACE_L1=1
  -DHZ6_LINUX_MMAP_RETAIN_L1=1
  -DHZ6_LINUX_MMAP_RETAIN_64K_STACK_L1=1
  -DHZ6_TOY_FULL_BLOCK_PREFILL_L1=1
  -DHZ6_TOY_FULL_BLOCK_PREFILL_MAX_SLOTS=128
  -DHZ6_TOY_ACTIVE_MAP_FREE_FAST_SLOT_L1=1
  -DHZ6_ROUTE_TOMBSTONE_COMPACT_L1=1
  -DHZ6_ROUTE_DOMAIN_SYNC_L1=1
  -DHZ6_ROUTE_DOMAIN_RWLOCK_L1=1
  -DHZ6_ROUTE_DOMAIN_RWLOCK_READER_GATE_L1=0
  -DHZ6_ROUTE_DOMAIN_SPIN_PAUSE_L1=0
  -DHZ6_ROUTE_COMPACT_DEFER_REMOTE_L1=1
  -DHZ6_ROUTE_VISIBLE_AFTER_LOCAL_MISS_L1=1
  -DHZ6_ROUTE_VISIBLE_EXACT_ONLY_L1=1
  -DHZ6_SHARED_ROUTE_DIRECTORY_L1=1
  -DHZ6_SHARED_ROUTE_DIRECTORY_SEQ_SNAPSHOT_L1=1
  -DHZ6_SHARED_ROUTE_DIRECTORY_MANDATORY_L1=1
  -DHZ6_SHARED_ROUTE_DIRECTORY_TOMBSTONE_MAINTENANCE_L1=1
  -DHZ6_SHARED_ROUTE_DIRECTORY_LOCK_SHARDS=256
  -DHZ6_ROUTE_REHOME_REGISTER_BEFORE_UNREGISTER_L1=0
  -DHZ6_ROUTE_REHOME_TRANSFER_OWNER_L1=1
  -DHZ6_REMOTE_FREE_REHOME_BEFORE_TRANSFER_L1=1
  -DHZ6_REMOTE_FREE_ROUTE_RESOLVE_L1=1
  -DHZ6_REMOTE_FREE_RESOLVE_SHARED_FIRST_L1=1
  -DHZ6_REMOTE_FREE_RESOLVE_SHARED_RETRY_LIMIT=3
  -DHZ6_REMOTE_FREE_RESOLVE_LOCAL_EXACT_ONLY_L1=0
  -DHZ6_PRELOAD_FOREIGN_RESOLVED_DISPATCH_L1=1
  -DHZ6_REMOTE_FREE_COMMIT_OBSERVE_L1=1
  -DHZ6_REMOTE_FREE_COMMIT_L1=1
  -DHZ6_REMOTE_FREE_STATUS_DISPATCH_L1=1
  -DHZ6_REMOTE_FREE_BACKPRESSURE_ORIGIN_TRANSFER_L1=1
  -DHZ6_REMOTE_FREE_BACKPRESSURE_ORIGIN_TRANSFER_STRIDE=2
  -DHZ6_ROUTE_HASH_XOR_FOLD_L1=1
  -DHZ6_ROUTE_LINEAR_WRAP_L1=1
  -DHZ6_ROUTE_LOOP_CARRY_L1=1
  -DHZ6_PRELOAD_FREE_MIDPAGE_CURRENT_BIAS_FIRST_L1=1
  -DHZ6_PRELOAD_PHASE_COUNT_COMPILED_OUT_L1=1
  -DHZ6_PRELOAD_MIDPAGE_DIRECT_CLASS_L1=1
  -DHZ6_PRELOAD_TOY_MALLOC_DIRECT_CLASS_L1=1
  -DHZ6_PRELOAD_TOY_MALLOC_DIRECT_CLASS_FAST_REUSE_L1=1
  -DHZ6_PRELOAD_TOY_MALLOC_DIRECT_CLASS_MAX_BYTES=4096
  -DHZ6_PRELOAD_BOUNDARY_TRUSTED_OWNER_L1=1
  -DHZ6_DIRECT_LOCAL_REUSE_RAW_POP_L1=1
  -DHZ6_MIDPAGE_DIRECT_LOCAL_REUSE_TRUSTED_CLASS_L1=1

  # Explicit no-go/control defaults. Override with runner variants for A/B.
  -DHZ6_LINUX_MMAP_RETAIN_TLS_L1=0
  -DHZ6_SOURCE_RUN_REUSE_L1=0
  -DHZ6_ROUTE_PACKED_META_L1=0
  -DHZ6_PRELOAD_FAST_FREE_L1=0
  -DHZ6_MIDPAGE_ACTIVE_MAP_FREE_FAST_SLOT_L1=0
  -DHZ6_MIDPAGE_ACTIVE_MAP_FREE_FAST_SLOT_CURRENT_BIAS_L1=0
  -DHZ6_PRELOAD_CALLOC_REAL_FALLBACK_L1=0
  -DHZ6_PRELOAD_CALLOC_REAL_FREE_SKIP_L1=0
)

HZ6_PRELOAD_MIDPAGE_BOUNDARY_CFLAGS=(
  -DHZ6_PRELOAD_MIDPAGE_MALLOC_SKIP_TRANSFER_L1=1
  -DHZ6_PRELOAD_MIDPAGE_MALLOC_BOUNDARY_NOINLINE_L1=1
)

hz6_preload_effective_selected_cflags() {
  local -n out_ref="$1"
  local enable_midpage_boundary="${2:-1}"
  out_ref=("${HZ6_PRELOAD_SELECTED_BASE_CFLAGS[@]}")
  if [[ "$enable_midpage_boundary" -ne 0 ]]; then
    out_ref+=("${HZ6_PRELOAD_MIDPAGE_BOUNDARY_CFLAGS[@]}")
  fi
}

hz6_preload_preserve_phase_counters() {
  local -n phase_flags_ref="$1"
  hz6_preload_replace_define phase_flags_ref HZ6_PRELOAD_PHASE_COUNT_COMPILED_OUT_L1 0
}

hz6_preload_preserve_phase_counters_when_observing() {
  local -n phase_observe_flags_ref="$1"
  local enable_stats="${2:-0}"
  local enable_diagnostics="${3:-0}"
  if [[ "$enable_stats" -ne 0 || "$enable_diagnostics" -ne 0 ]]; then
    hz6_preload_preserve_phase_counters phase_observe_flags_ref
  fi
}

hz6_preload_replace_define() {
  local -n flags_ref="$1"
  local macro="$2"
  local value="$3"
  local define="-D${macro}=${value}"
  local i
  for i in "${!flags_ref[@]}"; do
    if [[ "${flags_ref[$i]}" == "-D${macro}="* ]]; then
      flags_ref[$i]="$define"
      return
    fi
  done
  flags_ref+=("$define")
}

hz6_preload_join_flags() {
  local out=""
  local flag
  for flag in "$@"; do
    out+="${flag} "
  done
  printf '%s' "$out"
}
