    if (stats.shared_dir_tombstone_current >
        shared_dir_tombstone_current) {
      shared_dir_tombstone_current = stats.shared_dir_tombstone_current;
    }
    if (stats.shared_dir_tombstone_max > shared_dir_tombstone_max) {
      shared_dir_tombstone_max = stats.shared_dir_tombstone_max;
    }
    if (stats.shared_dir_register_used_tombstone >
        shared_dir_register_used_tombstone) {
      shared_dir_register_used_tombstone =
          stats.shared_dir_register_used_tombstone;
    }
    if (stats.shared_dir_maintenance_attempt >
        shared_dir_maintenance_attempt) {
      shared_dir_maintenance_attempt = stats.shared_dir_maintenance_attempt;
    }
    if (stats.shared_dir_maintenance_success >
        shared_dir_maintenance_success) {
      shared_dir_maintenance_success = stats.shared_dir_maintenance_success;
    }
    if (stats.shared_dir_maintenance_cleared >
        shared_dir_maintenance_cleared) {
      shared_dir_maintenance_cleared = stats.shared_dir_maintenance_cleared;
    }
