clean:
	rm -f $(ROOT)/libhakozuna_hz8_preload.so $(ROOT)/libhakozuna_hz8_preload_mediumnolazy.so $(ROOT)/libhakozuna_hz8_preload_medium64k2.so $(ROOT)/libhakozuna_hz8_preload_mediumchunk.so $(ROOT)/libhakozuna_hz8_preload_mediummadvfree.so $(ROOT)/libhakozuna_hz8_preload_mediumlazy.so $(ROOT)/libhakozuna_hz8_preload_keeprefill.so $(ROOT)/h8_smoke $(ROOT)/h8_smoke_mediumupper48 $(ROOT)/h8_safety_stress $(ROOT)/h8_medium_lazy_saturation $(ROOT)/h8_preload_smoke $(ROOT)/h8_bench $(ROOT)/h8_bench_medium64k2 $(ROOT)/h8_bench_mediumchunk $(ROOT)/h8_bench_mediumshardchunk $(ROOT)/h8_bench_mediumupper48 $(ROOT)/h8_bench_mediumv12_48k2 $(ROOT)/h8_bench_mediumfreecache $(ROOT)/h8_bench_mediumrefillhint $(ROOT)/h8_bench_mediumrefillcandidate $(ROOT)/h8_bench_mediumavailable $(ROOT)/h8_bench_mediumdemand64 $(ROOT)/h8_bench_mediumlocalfasttier $(ROOT)/h8_bench_hz9mediumlocalmagshadow $(ROOT)/h8_bench_release $(ROOT)/h8_bench_release_audit $(ROOT)/h8_bench_release_upper1p5 $(ROOT)/h8_bench_release_upper3072 $(ROOT)/h8_bench_release_mediumnolazy $(ROOT)/h8_bench_release_mediumfreecache $(ROOT)/h8_bench_release_mediumrefillhint $(ROOT)/h8_bench_release_mediumrefillcandidate $(ROOT)/h8_bench_release_mediumavailable $(ROOT)/h8_bench_release_mediumavailableinline $(ROOT)/h8_bench_release_mediumdemand64 $(ROOT)/h8_bench_release_mediumlocalfasttier $(ROOT)/h8_bench_release_mediumkeeprefillempty $(ROOT)/h8_bench_release_hz9mediumlocalmagshadow $(ROOT)/h8_bench_release_mediumceiling_noslotstate $(ROOT)/h8_bench_release_mediumceiling_freepending $(ROOT)/h8_bench_release_mediumceiling_combined $(ROOT)/h8_bench_release_mediummadvfree $(ROOT)/h8_bench_release_mediumlazy $(ROOT)/h8_bench_release_medium64k2 $(ROOT)/h8_bench_release_mediumchunk $(ROOT)/h8_bench_release_mediumshardchunk $(ROOT)/h8_bench_release_mediumupper48 $(ROOT)/h8_bench_release_mediumv12_48k2 $(ROOT)/h8_remote_micro $(ROOT)/h8_remote_micro_release
	rm -f $(ROOT)/h8_smoke_hz9mediumlocalmag $(ROOT)/h8_hz9_slab_route_smoke $(ROOT)/h8_hz9_slab_page_smoke $(ROOT)/h8_bench_hz9mediumlocalmag $(ROOT)/h8_bench_hz9mediumtlscache $(ROOT)/h8_bench_hz9mediumtlscache_gated $(ROOT)/h8_bench_hz9mediumslabshadow $(ROOT)/h8_bench_hz9mediumslabpage $(ROOT)/h8_bench_hz9mediumslabpage_classes $(ROOT)/h8_bench_hz9mediumslabpage_adaptive $(ROOT)/h8_bench_hz9mediumslabpage_cap6 $(ROOT)/h8_bench_hz9mediumslabpage_cap8 $(ROOT)/h8_bench_release_hz9mediumlocalmag $(ROOT)/h8_bench_release_hz9mediumtlscache $(ROOT)/h8_bench_release_hz9mediumtlscache_gated $(ROOT)/h8_bench_release_hz9mediumslabshadow $(ROOT)/h8_bench_release_hz9mediumslabpage $(ROOT)/h8_bench_release_hz9mediumslabpage_classes $(ROOT)/h8_bench_release_hz9mediumslabpage_classes_min3 $(ROOT)/h8_bench_release_hz9mediumslabpage_classes_min4 $(ROOT)/h8_bench_release_hz9mediumslabpage_adaptive $(ROOT)/h8_bench_release_hz9mediumslabpage_adaptive_min5 $(ROOT)/h8_bench_release_hz9mediumslabpage_adaptive_layout32 $(ROOT)/h8_bench_release_hz9mediumslabpage_adaptive_entry $(ROOT)/h8_bench_release_hz9mediumslabpage_cap6 $(ROOT)/h8_bench_release_hz9mediumslabpage_cap8 $(ROOT)/h8_bench_release_hz9mediumlocalmag_min2 $(ROOT)/h8_bench_release_hz9mediumlocalmag_min5 $(ROOT)/h8_bench_release_hz9mediumlocalmag_disabled $(ROOT)/h8_bench_release_hz9mediumlocalmag_unsafe_tlsonly
	rm -f $(ROOT)/h8_bench_hz9mediumtlscache_remoteclass $(ROOT)/h8_bench_release_hz9mediumtlscache_remoteclass
	rm -f $(ROOT)/libhakozuna_hz8_preload_largedirectdefault.so $(ROOT)/h8_bench_release_largedirectdefault
	rm -f $(ROOT)/libhakozuna_hz8_preload_largedirectmmap.so $(ROOT)/h8_bench_release_largedirectmmap
	rm -f $(ROOT)/libhakozuna_hz8_preload_largedirectpurgecache.so $(ROOT)/h8_bench_release_largedirectpurgecache
	rm -f $(ROOT)/libhakozuna_hz8_preload_largedirectrecyclecache.so $(ROOT)/h8_bench_release_largedirectrecyclecache
	rm -f $(ROOT)/libhakozuna_hz8_preload_largedirecthotcoldshadow.so $(ROOT)/h8_bench_release_largedirecthotcoldshadow
	rm -f $(ROOT)/libhakozuna_hz8_preload_largedirecthotcoldcache.so $(ROOT)/h8_bench_release_largedirecthotcoldcache
	rm -f $(ROOT)/libhakozuna_hz8_preload_largedirectshardedhotshadow.so $(ROOT)/h8_bench_release_largedirectshardedhotshadow
	rm -f $(ROOT)/libhakozuna_hz8_preload_largedirectshardedhotcache.so $(ROOT)/h8_bench_release_largedirectshardedhotcache
	rm -f $(ROOT)/h8_smoke_largedirect $(ROOT)/h8_bench_activefulldefer8 $(ROOT)/h8_bench_defer4mediumcapacity $(ROOT)/h8_bench_defer4mediumcapacity_largedirect $(ROOT)/h8_bench_defer4mediumcapacity_largedirect_refillhint
	rm -f $(ROOT)/h8_bench_defer8mediumcapacity $(ROOT)/h8_bench_mediumcapacitybudget $(ROOT)/h8_bench_mediumkeeprefillempty $(ROOT)/h8_bench_remoteactivefullbudget $(ROOT)/h8_bench_release_largedirectshardedhot128_32 $(ROOT)/h8_bench_release_largedirectshardedhot128_64 $(ROOT)/h8_bench_release_largedirectshardedhot192_32
	rm -f $(ROOT)/h8_hz9_* $(ROOT)/h8_bench_hz9* $(ROOT)/h8_bench_release_hz9* $(ROOT)/h8_safety_stress_hz9*
