[CmdletBinding()]
param(
    [string]$SourceRoot,
    [string]$OutDir,
    [string]$CompilerPath,
    [switch]$ClientCpp,
    [string]$TranslationUnit
)

$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $PSScriptRoot
$CompatIncludeRoot = Join-Path $RepoRoot "win\memtier\include"
$MemcachedCompatIncludeRoot = Join-Path $RepoRoot "win\memcached\include"

if (-not $SourceRoot) {
    $SourceRoot = Join-Path $RepoRoot "private\bench-assets\windows\memcached\client\memtier_benchmark-2.2.1"
}
if (-not $OutDir) {
    $OutDir = Join-Path $RepoRoot "private\raw-results\windows\memcached\client_probe"
}
if (-not $CompilerPath) {
    $CompilerPath = "C:\LLVM-18\bin\clang-cl.exe"
}

if (-not (Test-Path $SourceRoot)) {
    throw "memtier source root not found: $SourceRoot"
}
if (-not (Test-Path $OutDir)) {
    New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
}
if (-not (Test-Path $CompatIncludeRoot)) {
    throw "memtier compat include root not found: $CompatIncludeRoot"
}
if (-not (Test-Path $MemcachedCompatIncludeRoot)) {
    throw "memcached compat include root not found: $MemcachedCompatIncludeRoot"
}

$VcpkgRoot = if ($env:VCPKG_ROOT) { $env:VCPKG_ROOT } else { "C:\vcpkg" }
$VcpkgInclude = Join-Path $VcpkgRoot "installed\x64-windows\include"
$VcpkgIncludeEvent = Join-Path $VcpkgRoot "installed\x64-windows\include\event2\event.h"
if (-not (Test-Path $VcpkgIncludeEvent)) {
    throw "libevent headers not found under vcpkg: $VcpkgIncludeEvent"
}

$TargetName = if ($TranslationUnit) {
    [IO.Path]::GetFileNameWithoutExtension($TranslationUnit)
} elseif ($ClientCpp) {
    "client"
} else {
    "memtier_benchmark"
}
$TargetSource = Join-Path $SourceRoot ($TargetName + ".cpp")
if (-not (Test-Path $TargetSource)) {
    throw "probe source not found: $TargetSource"
}

$VersionHeaderPath = Join-Path $SourceRoot "version.h"
if (-not (Test-Path $VersionHeaderPath)) {
    $gitSha = "00000000"
    $gitDirty = "0"
    try {
        $gitShaOutput = & git -C $SourceRoot rev-parse --short=8 HEAD 2>$null
        if ($LASTEXITCODE -eq 0 -and $gitShaOutput) {
            $gitSha = ($gitShaOutput | Select-Object -First 1).Trim()
        }
        & git -C $SourceRoot diff-index --quiet HEAD -- 2>$null
        if ($LASTEXITCODE -ne 0) {
            $gitDirty = "1"
        }
    } catch {
    }

    $versionHeader = @(
        "/* This file is automatically generated by probe_win_memtier_msvc.ps1 */"
        "#ifndef MEMTIER_VERSION_H"
        "#define MEMTIER_VERSION_H"
        ""
        "#define MEMTIER_GIT_SHA1 `"$gitSha`""
        "#define MEMTIER_GIT_DIRTY `"$gitDirty`""
        ""
        "#endif /* MEMTIER_VERSION_H */"
    )
    Set-Content -Path $VersionHeaderPath -Value $versionHeader -Encoding UTF8
}

$Stamp = Get-Date -Format "yyyyMMdd_HHmmss"
$ObjPath = Join-Path $OutDir ($Stamp + "_" + $TargetName + ".obj")
$LogPath = Join-Path $OutDir ($Stamp + "_" + $TargetName + "_clang_cl.log")

$Args = @(
    "/nologo",
    "/std:c++20",
    "/c",
    "/EHsc",
    "/I", $CompatIncludeRoot,
    "/I", $MemcachedCompatIncludeRoot,
    "/I", $SourceRoot,
    "/I", $VcpkgInclude,
    "/D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH",
    "/DNOMINMAX",
    "/D_CRT_SECURE_NO_WARNINGS",
    "/D_CRT_NONSTDC_NO_WARNINGS",
    "/DHAVE_CONFIG_H",
    "/FIpthread.h",
    "/FIassert.h",
    "/Fo$ObjPath",
    $TargetSource
)

$previousErrorActionPreference = $ErrorActionPreference
$ErrorActionPreference = "Continue"
$output = & $CompilerPath @Args 2>&1
$rc = $LASTEXITCODE
$ErrorActionPreference = $previousErrorActionPreference

$log = New-Object System.Collections.Generic.List[string]
$log.Add("compiler: $CompilerPath")
$log.Add("target: $TargetSource")
$log.Add("out_obj: $ObjPath")
$log.Add("command: " + ($Args -join " "))
$log.Add("rc: $rc")
$log.Add("")
foreach ($line in $output) {
    $log.Add($line.ToString())
}

Set-Content -Path $LogPath -Value $log -Encoding UTF8

Write-Host "Wrote log: $LogPath"

if ($rc -ne 0) {
    throw "memtier MSVC probe failed for $TargetName (see $LogPath)"
}

[pscustomobject]@{
    Target = $TargetName
    LogPath = $LogPath
    ObjPath = $ObjPath
}
