#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ARCH="auto"
OUT_DIR=""
ENABLE_LINUX_P43=0
LINUX_LOCAL2P=0
LINUX_LOCAL2P_TLS_PACKED=0
LINUX_LOCAL2P_TLS_INITIAL_EXEC=0
LINUX_LOCAL2P_DIRECT_ROUTE=0
LINUX_LOCAL2P_DIRECT_INIT=0
LINUX_LOCAL2P_NO_COOKIE=0
LINUX_LOCAL2P_NO_CAS=0
LINUX_LOCAL2P_OWNER_INBOX=0
LINUX_LOCAL2P_REMOTE_BATCH=0
LINUX_LOCAL2P_REMOTE_BATCH_CAP=16
LINUX_LOCAL2P_TLS_CAP=1
LINUX_LOCAL2P_GLOBAL_CAP=1024
LINUX_LOCAL2P_OBJECT_NODE=0
LINUX_LOCAL2P_SAME_OWNER_FAST_STATE=0
LINUX_LOCAL2P_ROUTE_COOKIE=0
LINUX_LOCAL2P_REUSE_STATE_ONLY=0
LINUX_LOCAL2P_SLIM_CHECK=0
LINUX_LOCAL2P_FAST_COOKIE=0
LINUX_LOCAL2P_FREE_FIRST=0
LINUX_LOCAL2P_TLS_FAST_RETURN=0
LINUX_LOCAL2P_EXACT_API=0
LINUX_LOCAL2P_SINGLE_SLOT_TLS=0
LINUX_LOCAL2P_SPEED_LINKFLAGS=0
LINUX_LOCAL2P_LOCAL_OVERFLOW_GLOBAL=0
LINUX_LOCAL2P_RETAIN_ARRAY=0
LINUX_P11_SPEED_CORE=0
LINUX_P25_BRIDGE_ATTR=0
LINUX_P25_BRIDGE_ATTR_NO_CAS=0
LINUX_P25_BRIDGE_ATTR_NO_COOKIE=0
LINUX_P25_BRIDGE_ATTR_READONLY_STATE=0
LINUX_P43_PREPARED_BRIDGE=1
LINUX_P43_UNSAFE_NO_LOOKUP=0
LINUX_P43_TRUST_FAST_LOOKUP=0
LINUX_P43_TRUST_WRAPPER_SOURCE=0
LINUX_P43_DECODED_RAW_LOOKUP=0
LINUX_P43_RAW_FAST_LOOKUP_ONLY=0
LINUX_P43_RAW_ALLOCATED_LOOKUP_ONLY=0
LINUX_P43_WRAPPER_TOKEN=0
LINUX_P43_WRAPPER_TOKEN_BRIDGE=0
TRACE_LANE=0
BUILD_PRELOAD_FULL=0
PRELOAD_FREE_MID_FIRST=0
PRELOAD_FREE_MIDPAGE_FIRST=0
PRELOAD_FREE_MIDPAGE_LARGE_FIRST=0
PRELOAD_FREE_LARGE_FIRST=0
PRELOAD_MIDPAGE_ALLOC_FIRST=0
PRELOAD_MIDPAGE_ALLOC_ABS_FIRST=0
PRELOAD_MIDPAGE_SUPERFAST=0
PRELOAD_MIDPAGE_TAGGED_FREE=0
PRELOAD_TLS_INITIAL_EXEC=0
PRELOAD_SPEED_LINKFLAGS=0
LINUX_OWNERHUB_R1=0
LINUX_OWNERHUB_R2=0
LINUX_OWNERHUB_R3=0
LINUX_SMALLFRONT_S1=0
LINUX_SMALLFRONT_REMOTE_BATCH_CAP=16
LINUX_SMALLFRONT_DRAIN_EMPTY_GATED=0
LINUX_SMALLFRONT_REMOTE_OUTBOX=0
LINUX_MIDPAGEFRONT_M2=0
LINUX_MIDPAGEFRONT_REMOTE_BATCH_CAP=16
LINUX_MIDPAGEFRONT_REGION_ARRAY=0
LINUX_MIDPAGEFRONT_REMOTE_SHADOW=0
LINUX_MIDPAGEFRONT_LOCAL_FAST_STATE=0
LINUX_MIDPAGEFRONT_TLS_REGION_CACHE=0
LINUX_MIDPAGEFRONT_TLS_HOT_SLOT=0
LINUX_MIDPAGEFRONT_LOCAL_ACTIVE_TRUST=0
LINUX_MIDPAGEFRONT_SLOT_SWITCH=0
LINUX_MIDPAGEFRONT_NODELESS_RUN=0
LINUX_MIDPAGEFRONT_NODELESS_STATS=0
LINUX_MIDPAGEFRONT_NODELESS_PTRCACHE=0
LINUX_MIDPAGEFRONT_UNSAFE_LOCAL_NOCHECK=0
LINUX_MIDPAGEFRONT_M4_MAGAZINE=0
LINUX_MIDPAGEFRONT_M4_REMOTE_PACKET=0
LINUX_MIDPAGEFRONT_M4_REMOTE_DRAIN_ON_HIT=0
LINUX_MIDPAGEFRONT_M4_REMOTE_DRAIN_HIT_INTERVAL=64
LINUX_MIDPAGEFRONT_M4_CROSS_DRAIN=0
LINUX_MIDPAGEFRONT_M4_UNSAFE_ALLOC_ELIDE=0
LINUX_MIDPAGEFRONT_M4_UNSAFE_PTR_MAG=0
LINUX_MIDPAGEFRONT_M4_UNSAFE_FREE_ELIDE=0
LINUX_MIDPAGEFRONT_M5_HIT_ONLY=0
LINUX_MIDPAGEFRONT_M6_DEFERRED_FREE=0
LINUX_MIDPAGEFRONT_M6_REMOTE_DEFERRED_FREE=0
LINUX_MIDPAGEFRONT_M6_REMOTE_FLUSH_ON_REFILL=1
LINUX_MIDPAGEFRONT_M6_RAW_CAP=64
LINUX_MIDPAGEFRONT_M7_REMOTE_TICKET=0
LINUX_MIDPAGEFRONT_M7_REMOTE_PAGE_CAP=64
LINUX_MIDPAGEFRONT_M8_OWNER_XFER=0
LINUX_MIDPAGEFRONT_M8_XFER_PAGE_CAP=64
LINUX_MIDPAGEFRONT_M9_BUDGET_DRAIN=0
LINUX_MIDPAGEFRONT_M10_REMOTE_SLOT_RING=0
LINUX_MIDPAGEFRONT_M11_REMOTE_DIRECT_CACHE=0
LINUX_MIDPAGEFRONT_PAGERUN=0
LINUX_MIDPAGEFRONT_PAGERUN_64K=0
LINUX_MIDPAGEFRONT_M4_FLAT_MAG_CAP=0
LINUX_MIDPAGEFRONT_M4_OVERFLOW_ARRAY=0
LINUX_MIDPAGEFRONT_WIDE_32K_CLASS=0
LINUX_MIDPAGEFRONT_COARSE_BANDS=0
LINUX_MIDPAGEFRONT_EMPTY_SLAB_RELEASE=0
LINUX_MIDPAGEFRONT_EMPTY_RELEASE_ON_REFILL=1
LINUX_MIDPAGEFRONT_EMPTY_RETAIN_CAP=64
LINUX_MIDPAGEFRONT_M4_STATS=0
LINUX_MIDFRONT_M1=0
LINUX_MIDFRONT_OWNER_FAST_STATE=0
LINUX_MIDFRONT_MAX_BYTES=65536
LINUX_MIDFRONT_REMOTE_BATCH_CAP=16
LINUX_MIDFRONT_REMOTE_OUTBOX=0
LINUX_MIDFRONT_REMOTE_OUTBOX_SLOTS=4
LINUX_MIDFRONT_REMOTE_RBUF=0
LINUX_MIDFRONT_REMOTE_RBUF_CAP=128
LINUX_MIDFRONT_REMOTE_RBUF_FLUSH_THRESHOLD=96
LINUX_MIDFRONT_OUTBOX_FLUSH_ON_MISS=0
LINUX_MIDFRONT_REMOTE_DIRECT_FREE_STATE=0
LINUX_MIDFRONT_REMOTE_TRUST_DRAIN_STATE=0
LINUX_MIDFRONT_LOOKUP_CACHE=0
LINUX_MIDFRONT_DRAIN_ALL_ON_MISS=0
LINUX_MIDFRONT_DRAIN_MASK_ON_MISS=0
LINUX_MIDFRONT_DRAIN_MASK_HIT_STOP=0
LINUX_MIDFRONT_DRAIN_TAKE_FIRST=0
LINUX_MIDFRONT_DRAIN_EMPTY_GATED=0
LINUX_MIDFRONT_REMOTE_GLOBAL_RECYCLE=0
LINUX_LARGEFRONT_L1=0
LINUX_LARGEFRONT_OWNER_FAST_STATE=0
LINUX_LARGEFRONT_OWNER_INBOX=0
LINUX_LARGEFRONT_REMOTE_BATCH=0
LINUX_LARGEFRONT_REMOTE_CHUNK_INBOX=0
LINUX_LARGEFRONT_DRAIN_TAKE_FIRST=0
LINUX_LARGEFRONT_DRAIN_TAKE_ONLY=0
LINUX_LARGEFRONT_DRAIN_POP_BUDGET=0
LINUX_LARGEFRONT_REMOTE_HOLD=0
LINUX_LARGEFRONT_REMOTE_HOLD_CAP=0
LINUX_LARGEFRONT_REMOTE_GLOBAL_128K=0
LINUX_LARGEFRONT_REMOTE_FIRST_128K=0
LINUX_LARGEFRONT_REMOTE_FIRST_GATED_128K=0
LINUX_LARGEFRONT_POLICY_L7=0
LINUX_LARGEFRONT_POLICY_L7_REMAINDER_LOCAL_THRESHOLD=32
LINUX_LARGEFRONT_POLICY_L8_SHADOW=0
LINUX_LARGEFRONT_POLICY_L8_HEAVY_SPANS=32
LINUX_LARGEFRONT_DRAIN_EMPTY_GATED=0
LINUX_LARGEFRONT_MAP_BASE_ONLY=0
LINUX_LARGEFRONT_REGION_MAP=0
LINUX_LARGEFRONT_REGION_BASE_FASTMAP=0
LINUX_LARGEFRONT_DIRECT_HEADER_LOOKUP=0
LINUX_LARGEFRONT_BASE_DIRECTMAP=0
LINUX_LARGEFRONT_LOWER_CLASSES=0
LINUX_LARGEFRONT_ADAPTIVE128=0
LINUX_LARGEFRONT_PAYLOAD_SCAVENGE=0
LINUX_LARGEFRONT_OBSERVE=0
LINUX_LARGEFRONT_POLICY_L0=0
LINUX_LARGEFRONT_POLICY_L1A=0
LINUX_LARGEFRONT_POLICY_L1B=0
LINUX_LARGEFRONT_REMOTE_BATCH_CAP=16
LINUX_LARGEFRONT_REMOTE_CHUNK_CAP=16
LINUX_LARGEFRONT_REMOTE_CHUNK_POOL_CAP=65536
LINUX_LARGEFRONT_SOURCE_BATCH_COUNT=16
LINUX_LARGEFRONT_SCAVENGE_LOCAL_CAP=4
LINUX_LARGEFRONT_ALLOC_DRAIN_LOCAL_BUDGET=0
HZ5_STANDALONE_EXACT_ONLY=1

source "${ROOT_DIR}/linux/hz5_build_usage.sh"

require_value() {
  local opt="$1"
  if [[ $# -lt 2 || -z "${2:-}" || "${2:-}" == --* ]]; then
    echo "missing value for ${opt}" >&2
    exit 1
  fi
}

source "${ROOT_DIR}/linux/hz5_build_profile_bases.sh"
source "${ROOT_DIR}/linux/hz5_build_arg_parser.sh"
hz5_parse_build_args "$@"

source "${ROOT_DIR}/linux/hz5_build_validate.sh"
hz5_validate_build_config

if [[ "$ARCH" == "auto" ]]; then
  case "$(uname -m)" in
    aarch64|arm64) ARCH="arm64" ;;
    x86_64|amd64) ARCH="x86_64" ;;
    *) ARCH="$(uname -m)" ;;
  esac
fi

HZ5_DIR="${ROOT_DIR}/hakozuna-hz5"
SOURCE_COMMIT="$(git -C "$ROOT_DIR" rev-parse HEAD)"
OUT_DIR="${OUT_DIR:-${HZ5_DIR}/out/linux/${ARCH}}"
LIB="${OUT_DIR}/libhakozuna_hz5_standalone.so"
PRELOAD_HYBRID_LIB="${OUT_DIR}/libhakozuna_hz5_preload_hybrid.so"
PRELOAD_FULL_LIB="${OUT_DIR}/libhakozuna_hz5_preload_full.so"
BENCH="${OUT_DIR}/bench_hz5_standalone_aligned64k"
REMOTE_BENCH="${OUT_DIR}/bench_hz5_standalone_remote64k"
RSS_BENCH="${OUT_DIR}/bench_hz5_standalone_rss_plateau"
MIXED_BENCH="${OUT_DIR}/bench_hz5_standalone_mixed_prelude"
SAFETY_BENCH="${OUT_DIR}/bench_hz5_standalone_safety"
MIDPAGE_DIRECT_BENCH="${OUT_DIR}/bench_hz5_midpage_direct"
GENERIC_BENCH="${ROOT_DIR}/bench/out/linux/${ARCH}/bench_aligned64k"
GENERIC_REMOTE_BENCH="${ROOT_DIR}/bench/out/linux/${ARCH}/bench_remote64k"
GENERIC_RSS_BENCH="${ROOT_DIR}/bench/out/linux/${ARCH}/bench_rss_plateau"
GENERIC_MIXED_BENCH="${ROOT_DIR}/bench/out/linux/${ARCH}/bench_mixed_prelude"
BUILD_CONFIG="${OUT_DIR}/hz5_build_config.env"
SPEED_LANE=1
if [[ "$TRACE_LANE" -eq 1 ]]; then
  SPEED_LANE=0
fi

mkdir -p "$OUT_DIR"

COMMON_FLAGS=(
  -O3
  -fPIC
  -Wall
  -Wextra
  -Wno-unused-parameter
  -Wno-unused-function
  -Wno-unused-variable
  -std=c11
  -D_GNU_SOURCE
  -DNDEBUG
  -DHZ5_DIAGNOSTIC_STATS=0
  -DBENCHLAB_HZ5_SPEED_LANE="${SPEED_LANE}"
  -DBENCHLAB_HZ5_TRACE_LANE="${TRACE_LANE}"
  -DBENCHLAB_HZ5_NO_HZ3_FALLBACK=1
  -DBENCHLAB_HZ5_STANDALONE_EXACT_ONLY="${HZ5_STANDALONE_EXACT_ONLY}"
  -DBENCHLAB_HZ5_P25_HZ4LOWPAGE64K_A8192=1
  -DBENCHLAB_HZ5_P25_STATS=0
  -DHZ5_P11_SPEED_CORE="${LINUX_P11_SPEED_CORE}u"
  -DHZ5_DESC_SOURCE_COMMIT=\"${SOURCE_COMMIT}\"
  -I"${HZ5_DIR}/include"
  -I"${HZ5_DIR}/contract"
  -I"${HZ5_DIR}/policy"
  -I"${HZ5_DIR}/route"
  -I"${HZ5_DIR}/wrapper"
  -I"${HZ5_DIR}/lowpage"
  -I"${HZ5_DIR}/fallback"
  -I"${HZ5_DIR}/smallfront"
  -I"${HZ5_DIR}/midpagefront"
  -I"${HZ5_DIR}/midfront"
  -I"${HZ5_DIR}/largefront"
  -I"${HZ5_DIR}/ownerhub"
)
SPEED_LINK_COMPILE_FLAGS=()
SHARED_LINK_FLAGS=()
if [[ "$LINUX_LOCAL2P_SPEED_LINKFLAGS" -eq 1 ||
      "$PRELOAD_SPEED_LINKFLAGS" -eq 1 ]]; then
  SPEED_LINK_COMPILE_FLAGS+=(
    -fno-semantic-interposition
    -fno-plt
    -fno-stack-protector
  )
  if [[ "$ARCH" == "x86_64" || "$ARCH" == "amd64" ]]; then
    SPEED_LINK_COMPILE_FLAGS+=(-fcf-protection=none)
  fi
  SHARED_LINK_FLAGS+=(-Wl,-Bsymbolic-functions)
fi
COMMON_FLAGS+=("${SPEED_LINK_COMPILE_FLAGS[@]}")

if [[ "$LINUX_P25_BRIDGE_ATTR" -eq 1 ]]; then
  COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_P25_BRIDGE_ATTR=1)
  if [[ "$LINUX_P25_BRIDGE_ATTR_NO_CAS" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_P25_BRIDGE_ATTR_NO_CAS=1)
  fi
  if [[ "$LINUX_P25_BRIDGE_ATTR_NO_COOKIE" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_P25_BRIDGE_ATTR_NO_COOKIE=1)
  fi
  if [[ "$LINUX_P25_BRIDGE_ATTR_READONLY_STATE" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_P25_BRIDGE_ATTR_READONLY_STATE=1)
  fi
fi

if [[ "$LINUX_LOCAL2P" -eq 1 ]]; then
  COMMON_FLAGS+=(
    -DBENCHLAB_HZ5_LINUX_LOCAL2P=1
    -DBENCHLAB_HZ5_LINUX_LOCAL2P_TLS_CAP="${LINUX_LOCAL2P_TLS_CAP}u"
    -DBENCHLAB_HZ5_LINUX_LOCAL2P_GLOBAL_CAP="${LINUX_LOCAL2P_GLOBAL_CAP}u"
  )
  if [[ "$LINUX_LOCAL2P_TLS_PACKED" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LOCAL2P_TLS_PACKED=1)
  fi
  if [[ "$LINUX_LOCAL2P_DIRECT_ROUTE" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LOCAL2P_DIRECT_ROUTE=1)
  fi
  if [[ "$LINUX_LOCAL2P_DIRECT_INIT" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LOCAL2P_DIRECT_INIT=1)
  fi
  if [[ "$LINUX_LOCAL2P_TLS_INITIAL_EXEC" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LOCAL2P_TLS_INITIAL_EXEC=1)
    COMMON_FLAGS+=(-ftls-model=initial-exec)
  fi
  if [[ "$LINUX_LOCAL2P_NO_COOKIE" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LOCAL2P_NO_COOKIE=1)
  fi
  if [[ "$LINUX_LOCAL2P_NO_CAS" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LOCAL2P_NO_CAS=1)
  fi
  if [[ "$LINUX_LOCAL2P_OWNER_INBOX" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LOCAL2P_OWNER_INBOX=1)
  fi
  if [[ "$LINUX_LOCAL2P_REMOTE_BATCH" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LOCAL2P_REMOTE_BATCH=1)
    COMMON_FLAGS+=(
      -DBENCHLAB_HZ5_LINUX_LOCAL2P_REMOTE_BATCH_CAP="${LINUX_LOCAL2P_REMOTE_BATCH_CAP}u"
    )
  fi
  if [[ "$LINUX_LOCAL2P_OBJECT_NODE" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LOCAL2P_OBJECT_NODE=1)
  fi
  if [[ "$LINUX_LOCAL2P_SAME_OWNER_FAST_STATE" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LOCAL2P_SAME_OWNER_FAST_STATE=1)
  fi
  if [[ "$LINUX_LOCAL2P_ROUTE_COOKIE" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LOCAL2P_ROUTE_COOKIE=1)
  fi
  if [[ "$LINUX_LOCAL2P_REUSE_STATE_ONLY" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LOCAL2P_REUSE_STATE_ONLY=1)
  fi
  if [[ "$LINUX_LOCAL2P_SLIM_CHECK" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LOCAL2P_SLIM_CHECK=1)
  fi
  if [[ "$LINUX_LOCAL2P_FAST_COOKIE" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LOCAL2P_FAST_COOKIE=1)
  fi
  if [[ "$LINUX_LOCAL2P_FREE_FIRST" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LOCAL2P_FREE_FIRST=1)
  fi
  if [[ "$LINUX_LOCAL2P_TLS_FAST_RETURN" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LOCAL2P_TLS_FAST_RETURN=1)
  fi
  if [[ "$LINUX_LOCAL2P_SINGLE_SLOT_TLS" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LOCAL2P_SINGLE_SLOT_TLS=1)
  fi
  if [[ "$LINUX_LOCAL2P_LOCAL_OVERFLOW_GLOBAL" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LOCAL2P_LOCAL_OVERFLOW_GLOBAL=1)
  fi
  if [[ "$LINUX_LOCAL2P_RETAIN_ARRAY" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LOCAL2P_RETAIN_ARRAY=1)
  fi
fi

if [[ "$ENABLE_LINUX_P43" -eq 1 ]]; then
  COMMON_FLAGS+=(
    -DBENCHLAB_HZ5_LINUX_P43_PORT=1
    -DBENCHLAB_HZ5_P43_SEGMENT_SLOTS=1
    -DBENCHLAB_HZ5_P43_FAST_LOOKUP=1
    -DBENCHLAB_HZ5_P43_LOCKLESS_LOOKUP=1
    -DBENCHLAB_HZ5_P43_SLOT_DECOMMIT=0
    -DBENCHLAB_HZ5_P43_PAGE_NOACCESS=0
  )
  if [[ "$LINUX_P43_PREPARED_BRIDGE" -eq 1 ]]; then
    COMMON_FLAGS+=(
      -DBENCHLAB_HZ5_P43_PREPARED_BRIDGE=1
      -DBENCHLAB_HZ5_P43_LOCKLESS_CONTRACT=1
    )
  fi
  if [[ "$LINUX_P43_UNSAFE_NO_LOOKUP" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_P43_UNSAFE_NO_LOOKUP=1)
  fi
  if [[ "$LINUX_P43_TRUST_FAST_LOOKUP" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_P43_TRUST_FAST_LOOKUP=1)
  fi
  if [[ "$LINUX_P43_TRUST_WRAPPER_SOURCE" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_P43_TRUST_WRAPPER_SOURCE=1)
  fi
  if [[ "$LINUX_P43_DECODED_RAW_LOOKUP" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_P43_DECODED_RAW_LOOKUP=1)
  fi
  if [[ "$LINUX_P43_RAW_FAST_LOOKUP_ONLY" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_P43_RAW_FAST_LOOKUP_ONLY=1)
  fi
  if [[ "$LINUX_P43_RAW_ALLOCATED_LOOKUP_ONLY" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_P43_RAW_ALLOCATED_LOOKUP_ONLY=1)
  fi
  if [[ "$LINUX_P43_WRAPPER_TOKEN" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_P43_WRAPPER_TOKEN=1)
  fi
  if [[ "$LINUX_P43_WRAPPER_TOKEN_BRIDGE" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_P43_WRAPPER_TOKEN_BRIDGE=1)
  fi
fi

if [[ "$LINUX_SMALLFRONT_S1" -eq 1 ]]; then
  COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_SMALLFRONT_S1=1)
  COMMON_FLAGS+=(
    -DHZ5_SMALLFRONT_REMOTE_BATCH_CAP="${LINUX_SMALLFRONT_REMOTE_BATCH_CAP}u"
  )
  if [[ "$LINUX_SMALLFRONT_DRAIN_EMPTY_GATED" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_SMALLFRONT_DRAIN_EMPTY_GATED=1)
  fi
  if [[ "$LINUX_SMALLFRONT_REMOTE_OUTBOX" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_SMALLFRONT_REMOTE_OUTBOX=1)
  fi
fi
if [[ "$LINUX_MIDPAGEFRONT_M2" -eq 1 ]]; then
  COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_M2=1)
  COMMON_FLAGS+=(
    -DHZ5_MIDPAGEFRONT_REMOTE_BATCH_CAP="${LINUX_MIDPAGEFRONT_REMOTE_BATCH_CAP}u"
  )
  if [[ "$LINUX_MIDPAGEFRONT_REGION_ARRAY" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_REGION_ARRAY=1)
  fi
  if [[ "$LINUX_MIDPAGEFRONT_REMOTE_SHADOW" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_REMOTE_SHADOW=1)
  fi
  if [[ "$LINUX_MIDPAGEFRONT_LOCAL_FAST_STATE" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_LOCAL_FAST_STATE=1)
  fi
  if [[ "$LINUX_MIDPAGEFRONT_TLS_REGION_CACHE" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_TLS_REGION_CACHE=1)
  fi
  if [[ "$LINUX_MIDPAGEFRONT_TLS_HOT_SLOT" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_TLS_HOT_SLOT=1)
  fi
  if [[ "$LINUX_MIDPAGEFRONT_LOCAL_ACTIVE_TRUST" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_LOCAL_ACTIVE_TRUST=1)
  fi
  if [[ "$LINUX_MIDPAGEFRONT_SLOT_SWITCH" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_SLOT_SWITCH=1)
  fi
  if [[ "$LINUX_MIDPAGEFRONT_NODELESS_RUN" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_NODELESS_RUN=1)
  fi
  if [[ "$LINUX_MIDPAGEFRONT_NODELESS_PTRCACHE" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_NODELESS_PTRCACHE=1)
  fi
  if [[ "$LINUX_MIDPAGEFRONT_NODELESS_STATS" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_NODELESS_STATS=1)
  fi
  if [[ "$LINUX_MIDPAGEFRONT_UNSAFE_LOCAL_NOCHECK" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_UNSAFE_LOCAL_NOCHECK=1)
  fi
  if [[ "$LINUX_MIDPAGEFRONT_M4_MAGAZINE" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_M4_MAGAZINE=1)
  fi
  if [[ "$LINUX_MIDPAGEFRONT_M4_REMOTE_PACKET" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_M4_REMOTE_PACKET=1)
  fi
  if [[ "$LINUX_MIDPAGEFRONT_M4_REMOTE_DRAIN_ON_HIT" -eq 1 ]]; then
    COMMON_FLAGS+=(
      -DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_M4_REMOTE_DRAIN_ON_HIT=1
      -DHZ5_MIDPAGEFRONT_REMOTE_DRAIN_HIT_INTERVAL="${LINUX_MIDPAGEFRONT_M4_REMOTE_DRAIN_HIT_INTERVAL}u"
    )
  fi
  if [[ "$LINUX_MIDPAGEFRONT_M4_CROSS_DRAIN" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_M4_CROSS_DRAIN=1)
  fi
  if [[ "$LINUX_MIDPAGEFRONT_M4_UNSAFE_ALLOC_ELIDE" -eq 1 ]]; then
    COMMON_FLAGS+=(
      -DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_M4_UNSAFE_ALLOC_ELIDE=1)
  fi
  if [[ "$LINUX_MIDPAGEFRONT_M4_UNSAFE_PTR_MAG" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_M4_UNSAFE_PTR_MAG=1)
  fi
  if [[ "$LINUX_MIDPAGEFRONT_M4_UNSAFE_FREE_ELIDE" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_M4_UNSAFE_FREE_ELIDE=1)
  fi
  if [[ "$LINUX_MIDPAGEFRONT_M5_HIT_ONLY" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_M5_HIT_ONLY=1)
  fi
  if [[ "$LINUX_MIDPAGEFRONT_M6_DEFERRED_FREE" -eq 1 ]]; then
    COMMON_FLAGS+=(
      -DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_M6_DEFERRED_FREE=1
    )
  fi
  if [[ "$LINUX_MIDPAGEFRONT_M6_REMOTE_DEFERRED_FREE" -eq 1 ]]; then
    COMMON_FLAGS+=(
      -DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_M6_REMOTE_DEFERRED_FREE=1
    )
    if [[ "$LINUX_MIDPAGEFRONT_M6_REMOTE_FLUSH_ON_REFILL" -eq 0 ]]; then
      COMMON_FLAGS+=(
        -DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_M6_REMOTE_FLUSH_ON_REFILL=0)
    fi
  fi
  if [[ "$LINUX_MIDPAGEFRONT_M6_DEFERRED_FREE" -eq 1 || \
        "$LINUX_MIDPAGEFRONT_M6_REMOTE_DEFERRED_FREE" -eq 1 ]]; then
    COMMON_FLAGS+=(
      -DHZ5_MIDPAGEFRONT_M6_RAW_CAP="${LINUX_MIDPAGEFRONT_M6_RAW_CAP}u"
    )
  fi
  if [[ "$LINUX_MIDPAGEFRONT_M7_REMOTE_TICKET" -eq 1 ]]; then
    COMMON_FLAGS+=(
      -DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_M7_REMOTE_TICKET=1
      -DHZ5_MIDPAGEFRONT_M6_RAW_CAP="${LINUX_MIDPAGEFRONT_M6_RAW_CAP}u"
      -DHZ5_MIDPAGEFRONT_M7_REMOTE_PAGE_CAP="${LINUX_MIDPAGEFRONT_M7_REMOTE_PAGE_CAP}u"
    )
  fi
  if [[ "$LINUX_MIDPAGEFRONT_M8_OWNER_XFER" -eq 1 ]]; then
    COMMON_FLAGS+=(
      -DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_M8_OWNER_XFER=1
      -DHZ5_MIDPAGEFRONT_M8_XFER_PAGE_CAP="${LINUX_MIDPAGEFRONT_M8_XFER_PAGE_CAP}u"
    )
  fi
  if [[ "$LINUX_MIDPAGEFRONT_M9_BUDGET_DRAIN" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_M9_BUDGET_DRAIN=1)
  fi
  if [[ "$LINUX_MIDPAGEFRONT_M10_REMOTE_SLOT_RING" -eq 1 ]]; then
    COMMON_FLAGS+=(
      -DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_M10_REMOTE_SLOT_RING=1
      -DHZ5_MIDPAGEFRONT_M6_RAW_CAP="${LINUX_MIDPAGEFRONT_M6_RAW_CAP}u"
    )
  fi
  if [[ "$LINUX_MIDPAGEFRONT_M11_REMOTE_DIRECT_CACHE" -eq 1 ]]; then
    COMMON_FLAGS+=(
      -DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_M11_REMOTE_DIRECT_CACHE=1
    )
  fi
  if [[ "$LINUX_MIDPAGEFRONT_PAGERUN" -eq 1 ]]; then
    COMMON_FLAGS+=(
      -DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_PAGERUN=1
    )
  fi
  if [[ "$LINUX_MIDPAGEFRONT_PAGERUN_64K" -eq 1 ]]; then
    COMMON_FLAGS+=(
      -DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_PAGERUN_64K=1
    )
  fi
  if [[ "$LINUX_MIDPAGEFRONT_M4_FLAT_MAG_CAP" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_M4_FLAT_MAG_CAP=1)
  fi
  if [[ "$LINUX_MIDPAGEFRONT_M4_OVERFLOW_ARRAY" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_M4_OVERFLOW_ARRAY=1)
  fi
  if [[ "$LINUX_MIDPAGEFRONT_WIDE_32K_CLASS" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_WIDE_32K_CLASS=1)
  fi
  if [[ "$LINUX_MIDPAGEFRONT_COARSE_BANDS" -ne 0 ]]; then
    COMMON_FLAGS+=(
      -DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_COARSE_BANDS="${LINUX_MIDPAGEFRONT_COARSE_BANDS}"
    )
  fi
  if [[ "$LINUX_MIDPAGEFRONT_EMPTY_SLAB_RELEASE" -eq 1 ]]; then
    COMMON_FLAGS+=(
      -DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_EMPTY_SLAB_RELEASE=1
      -DHZ5_MIDPAGEFRONT_EMPTY_RETAIN_CAP="${LINUX_MIDPAGEFRONT_EMPTY_RETAIN_CAP}u"
    )
    if [[ "$LINUX_MIDPAGEFRONT_EMPTY_RELEASE_ON_REFILL" -eq 0 ]]; then
      COMMON_FLAGS+=(
        -DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_EMPTY_RELEASE_ON_REFILL=0)
    fi
  fi
  if [[ "$LINUX_MIDPAGEFRONT_M4_STATS" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDPAGEFRONT_M4_STATS=1)
  fi
fi
if [[ "$LINUX_OWNERHUB_R1" -eq 1 ]]; then
  COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_OWNERHUB_R1=1)
fi
if [[ "$LINUX_OWNERHUB_R2" -eq 1 ]]; then
  COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_OWNERHUB_R2=1)
fi
if [[ "$LINUX_OWNERHUB_R3" -eq 1 ]]; then
  COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_OWNERHUB_R3=1)
fi
if [[ "$LINUX_MIDFRONT_M1" -eq 1 ]]; then
  COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDFRONT_M1=1)
  COMMON_FLAGS+=(
    -DHZ5_MIDFRONT_MAX_BYTES="${LINUX_MIDFRONT_MAX_BYTES}u"
    -DHZ5_MIDFRONT_REMOTE_BATCH_CAP="${LINUX_MIDFRONT_REMOTE_BATCH_CAP}u"
  )
  if [[ "$LINUX_MIDFRONT_OWNER_FAST_STATE" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDFRONT_OWNER_FAST_STATE=1)
  fi
  if [[ "$LINUX_MIDFRONT_DRAIN_ALL_ON_MISS" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDFRONT_DRAIN_ALL_ON_MISS=1)
  fi
  if [[ "$LINUX_MIDFRONT_DRAIN_MASK_ON_MISS" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDFRONT_DRAIN_MASK_ON_MISS=1)
  fi
  if [[ "$LINUX_MIDFRONT_DRAIN_MASK_HIT_STOP" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDFRONT_DRAIN_MASK_HIT_STOP=1)
  fi
  if [[ "$LINUX_MIDFRONT_DRAIN_TAKE_FIRST" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDFRONT_DRAIN_TAKE_FIRST=1)
  fi
  if [[ "$LINUX_MIDFRONT_DRAIN_EMPTY_GATED" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDFRONT_DRAIN_EMPTY_GATED=1)
  fi
  if [[ "$LINUX_MIDFRONT_REMOTE_GLOBAL_RECYCLE" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDFRONT_REMOTE_GLOBAL_RECYCLE=1)
  fi
  if [[ "$LINUX_MIDFRONT_REMOTE_OUTBOX" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDFRONT_REMOTE_OUTBOX=1)
    COMMON_FLAGS+=(
      -DHZ5_MIDFRONT_REMOTE_OUTBOX_SLOTS="${LINUX_MIDFRONT_REMOTE_OUTBOX_SLOTS}u"
    )
  fi
  if [[ "$LINUX_MIDFRONT_REMOTE_RBUF" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDFRONT_REMOTE_RBUF=1)
    COMMON_FLAGS+=(
      -DHZ5_MIDFRONT_REMOTE_RBUF_CAP="${LINUX_MIDFRONT_REMOTE_RBUF_CAP}u"
      -DHZ5_MIDFRONT_REMOTE_RBUF_FLUSH_THRESHOLD="${LINUX_MIDFRONT_REMOTE_RBUF_FLUSH_THRESHOLD}u"
    )
  fi
  if [[ "$LINUX_MIDFRONT_OUTBOX_FLUSH_ON_MISS" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDFRONT_OUTBOX_FLUSH_ON_MISS=1)
  fi
  if [[ "$LINUX_MIDFRONT_REMOTE_DIRECT_FREE_STATE" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDFRONT_REMOTE_DIRECT_FREE_STATE=1)
  fi
  if [[ "$LINUX_MIDFRONT_REMOTE_TRUST_DRAIN_STATE" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDFRONT_REMOTE_TRUST_DRAIN_STATE=1)
  fi
  if [[ "$LINUX_MIDFRONT_LOOKUP_CACHE" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_MIDFRONT_LOOKUP_CACHE=1)
  fi
fi
if [[ "$LINUX_LARGEFRONT_L1" -eq 1 ]]; then
  COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_L1=1)
  COMMON_FLAGS+=(
    -DHZ5_LARGEFRONT_SOURCE_BATCH_COUNT="${LINUX_LARGEFRONT_SOURCE_BATCH_COUNT}u"
    -DHZ5_LARGEFRONT_ALLOC_DRAIN_LOCAL_BUDGET="${LINUX_LARGEFRONT_ALLOC_DRAIN_LOCAL_BUDGET}u"
  )
  if [[ "$LINUX_LARGEFRONT_OWNER_FAST_STATE" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OWNER_FAST_STATE=1)
  fi
  if [[ "$LINUX_LARGEFRONT_OWNER_INBOX" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OWNER_INBOX=1)
  fi
  if [[ "$LINUX_LARGEFRONT_REMOTE_BATCH" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OWNER_INBOX=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_REMOTE_BATCH=1)
    COMMON_FLAGS+=(
      -DHZ5_LARGEFRONT_REMOTE_BATCH_CAP="${LINUX_LARGEFRONT_REMOTE_BATCH_CAP}u"
    )
  fi
  if [[ "$LINUX_LARGEFRONT_REMOTE_CHUNK_INBOX" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OWNER_INBOX=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_REMOTE_BATCH=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_REMOTE_CHUNK_INBOX=1)
    COMMON_FLAGS+=(
      -DHZ5_LARGEFRONT_REMOTE_CHUNK_CAP="${LINUX_LARGEFRONT_REMOTE_CHUNK_CAP}u"
      -DHZ5_LARGEFRONT_REMOTE_CHUNK_POOL_CAP="${LINUX_LARGEFRONT_REMOTE_CHUNK_POOL_CAP}u"
    )
  fi
  if [[ "$LINUX_LARGEFRONT_DRAIN_TAKE_FIRST" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OWNER_INBOX=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_DRAIN_TAKE_FIRST=1)
  fi
  if [[ "$LINUX_LARGEFRONT_DRAIN_TAKE_ONLY" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OWNER_INBOX=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_DRAIN_TAKE_FIRST=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_DRAIN_TAKE_ONLY=1)
  fi
  if [[ "$LINUX_LARGEFRONT_DRAIN_POP_BUDGET" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OWNER_INBOX=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_DRAIN_TAKE_FIRST=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_DRAIN_POP_BUDGET=1)
  fi
  if [[ "$LINUX_LARGEFRONT_REMOTE_HOLD" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OWNER_INBOX=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_DRAIN_TAKE_FIRST=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_REMOTE_HOLD=1)
    COMMON_FLAGS+=(
      -DHZ5_LARGEFRONT_REMOTE_HOLD_CAP="${LINUX_LARGEFRONT_REMOTE_HOLD_CAP}u"
    )
  fi
  if [[ "$LINUX_LARGEFRONT_REMOTE_GLOBAL_128K" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OWNER_INBOX=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_REMOTE_GLOBAL_128K=1)
  fi
  if [[ "$LINUX_LARGEFRONT_REMOTE_FIRST_128K" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OWNER_INBOX=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_DRAIN_TAKE_FIRST=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_REMOTE_FIRST_128K=1)
  fi
  if [[ "$LINUX_LARGEFRONT_REMOTE_FIRST_GATED_128K" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OWNER_INBOX=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_DRAIN_TAKE_FIRST=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_REMOTE_FIRST_GATED_128K=1)
  fi
  if [[ "$LINUX_LARGEFRONT_POLICY_L7" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OWNER_INBOX=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_DRAIN_TAKE_FIRST=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_POLICY_L7=1)
    COMMON_FLAGS+=(
      -DHZ5_LARGEFRONT_POLICY_L7_REMAINDER_LOCAL_THRESHOLD="${LINUX_LARGEFRONT_POLICY_L7_REMAINDER_LOCAL_THRESHOLD}u"
    )
  fi
  if [[ "$LINUX_LARGEFRONT_POLICY_L8_SHADOW" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OWNER_INBOX=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_DRAIN_TAKE_FIRST=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_POLICY_L0=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_POLICY_L8_SHADOW=1)
    COMMON_FLAGS+=(
      -DHZ5_LARGEFRONT_POLICY_L8_HEAVY_SPANS="${LINUX_LARGEFRONT_POLICY_L8_HEAVY_SPANS}u"
    )
  fi
  if [[ "$LINUX_LARGEFRONT_DRAIN_EMPTY_GATED" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OWNER_INBOX=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_DRAIN_EMPTY_GATED=1)
  fi
  if [[ "$LINUX_LARGEFRONT_MAP_BASE_ONLY" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OWNER_INBOX=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_MAP_BASE_ONLY=1)
  fi
  if [[ "$LINUX_LARGEFRONT_REGION_MAP" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OWNER_INBOX=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_REGION_MAP=1)
  fi
  if [[ "$LINUX_LARGEFRONT_REGION_BASE_FASTMAP" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OWNER_INBOX=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_REGION_MAP=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_REGION_BASE_FASTMAP=1)
  fi
  if [[ "$LINUX_LARGEFRONT_DIRECT_HEADER_LOOKUP" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_DIRECT_HEADER_LOOKUP=1)
  fi
  if [[ "$LINUX_LARGEFRONT_BASE_DIRECTMAP" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_BASE_DIRECTMAP=1)
  fi
  if [[ "$LINUX_LARGEFRONT_ADAPTIVE128" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OWNER_INBOX=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_REGION_MAP=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_DRAIN_TAKE_FIRST=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_ADAPTIVE128=1)
  fi
  if [[ "$LINUX_LARGEFRONT_PAYLOAD_SCAVENGE" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OWNER_INBOX=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_REGION_MAP=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_PAYLOAD_SCAVENGE=1)
    COMMON_FLAGS+=(
      -DHZ5_LARGEFRONT_SCAVENGE_LOCAL_CAP="${LINUX_LARGEFRONT_SCAVENGE_LOCAL_CAP}u"
    )
  fi
  if [[ "$LINUX_LARGEFRONT_OBSERVE" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OWNER_INBOX=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_REGION_MAP=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OBSERVE=1)
  fi
  if [[ "$LINUX_LARGEFRONT_POLICY_L0" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OWNER_INBOX=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_REGION_MAP=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_POLICY_L0=1)
  fi
  if [[ "$LINUX_LARGEFRONT_POLICY_L1A" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OWNER_INBOX=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_REGION_MAP=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_DRAIN_TAKE_FIRST=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_POLICY_L1A=1)
  fi
  if [[ "$LINUX_LARGEFRONT_POLICY_L1B" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_OWNER_INBOX=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_REGION_MAP=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_DRAIN_TAKE_FIRST=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_REMOTE_BATCH=1)
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_POLICY_L1B=1)
  fi
  if [[ "$LINUX_LARGEFRONT_LOWER_CLASSES" -eq 1 ]]; then
    COMMON_FLAGS+=(-DBENCHLAB_HZ5_LINUX_LARGEFRONT_LOWER_CLASSES=1)
  fi
fi

source "${ROOT_DIR}/linux/hz5_build_config_writer.sh"
hz5_write_build_config

if [[ "$PRELOAD_FREE_MID_FIRST" -eq 1 ]]; then
  COMMON_FLAGS+=(-DBENCHLAB_HZ5_PRELOAD_FREE_MID_FIRST=1)
fi
if [[ "$PRELOAD_FREE_MIDPAGE_FIRST" -eq 1 ]]; then
  COMMON_FLAGS+=(-DBENCHLAB_HZ5_PRELOAD_FREE_MIDPAGE_FIRST=1)
fi
if [[ "$PRELOAD_FREE_MIDPAGE_LARGE_FIRST" -eq 1 ]]; then
  COMMON_FLAGS+=(-DBENCHLAB_HZ5_PRELOAD_FREE_MIDPAGE_LARGE_FIRST=1)
fi
if [[ "$PRELOAD_FREE_LARGE_FIRST" -eq 1 ]]; then
  COMMON_FLAGS+=(-DBENCHLAB_HZ5_PRELOAD_FREE_LARGE_FIRST=1)
fi
if [[ "$PRELOAD_MIDPAGE_ALLOC_FIRST" -eq 1 ]]; then
  COMMON_FLAGS+=(-DBENCHLAB_HZ5_PRELOAD_MIDPAGE_ALLOC_FIRST=1)
fi
if [[ "$PRELOAD_MIDPAGE_ALLOC_ABS_FIRST" -eq 1 ]]; then
  COMMON_FLAGS+=(-DBENCHLAB_HZ5_PRELOAD_MIDPAGE_ALLOC_ABS_FIRST=1)
fi
if [[ "$PRELOAD_MIDPAGE_SUPERFAST" -eq 1 ]]; then
  COMMON_FLAGS+=(-DBENCHLAB_HZ5_PRELOAD_MIDPAGE_SUPERFAST=1)
fi
if [[ "$PRELOAD_MIDPAGE_TAGGED_FREE" -eq 1 ]]; then
  COMMON_FLAGS+=(-DBENCHLAB_HZ5_PRELOAD_MIDPAGE_TAGGED_FREE=1)
fi
if [[ "$PRELOAD_TLS_INITIAL_EXEC" -eq 1 ]]; then
  COMMON_FLAGS+=(-DBENCHLAB_HZ5_PRELOAD_TLS_INITIAL_EXEC=1)
  COMMON_FLAGS+=(-ftls-model=initial-exec)
fi

HZ5_SRCS=(
  "${HZ5_DIR}/api/hz5_api.c"
  "${HZ5_DIR}/contract/hz5_contract.c"
  "${HZ5_DIR}/core/hz5_segment.c"
  "${HZ5_DIR}/core/hz5_run.c"
  "${HZ5_DIR}/core/hz5_owner.c"
  "${HZ5_DIR}/core/hz5_remote.c"
  "${HZ5_DIR}/core/hz5_tcache.c"
  "${HZ5_DIR}/core/hz5_stats.c"
  "${HZ5_DIR}/policy/hz5_policy.c"
  "${HZ5_DIR}/policy/hz5_trace.c"
  "${HZ5_DIR}/route/hz5_route.c"
  "${HZ5_DIR}/ownerhub/hz5_ownerhub.c"
  "${HZ5_DIR}/smallfront/hz5_smallfront.c"
  "${HZ5_DIR}/midpagefront/hz5_midpagefront.c"
  "${HZ5_DIR}/midfront/hz5_midfront.c"
  "${HZ5_DIR}/largefront/hz5_largefront.c"
  "${HZ5_DIR}/wrapper/hz5_wrapper.c"
  "${HZ5_DIR}/lowpage/hz5_lowpage64.c"
  "${HZ5_DIR}/lowpage/hz5_lowpage64_os.c"
  "${HZ5_DIR}/lowpage/hz5_lowpage64_p43_segment.c"
  "${HZ5_DIR}/linux/hz5_linux_compat.c"
)

echo "[linux][hz5] arch: ${ARCH}"
echo "[linux][hz5] building library: ${LIB}"
gcc "${COMMON_FLAGS[@]}" -shared "${HZ5_SRCS[@]}" \
  "${SHARED_LINK_FLAGS[@]}" -pthread -ldl -o "$LIB"

echo "[linux][hz5] building preload hybrid library: ${PRELOAD_HYBRID_LIB}"
gcc "${COMMON_FLAGS[@]}" -shared \
  "${HZ5_SRCS[@]}" \
  "${HZ5_DIR}/preload/hz5_preload_hybrid.c" \
  "${SHARED_LINK_FLAGS[@]}" -pthread -ldl -o "$PRELOAD_HYBRID_LIB"

if [[ "$BUILD_PRELOAD_FULL" -eq 1 ]]; then
  echo "[linux][hz5] building preload full library: ${PRELOAD_FULL_LIB}"
  gcc "${COMMON_FLAGS[@]}" -shared \
    "${HZ5_SRCS[@]}" \
    "${HZ5_DIR}/preload/hz5_preload_full.c" \
    "${SHARED_LINK_FLAGS[@]}" -pthread -ldl -o "$PRELOAD_FULL_LIB"
fi

echo "[linux][hz5] building benchmark: ${BENCH}"
BENCH_ALIGNED_FLAGS=()
if [[ "$LINUX_LOCAL2P_EXACT_API" -eq 1 ]]; then
  BENCH_ALIGNED_FLAGS+=(-DBENCHLAB_HZ5_EXACT_LOCAL2P_API=1)
fi
gcc -O3 -Wall -Wextra -Werror -std=c11 -D_POSIX_C_SOURCE=200809L \
  "${SPEED_LINK_COMPILE_FLAGS[@]}" \
  "${BENCH_ALIGNED_FLAGS[@]}" \
  -I"${HZ5_DIR}/include" \
  "${ROOT_DIR}/bench/bench_hz5_standalone_aligned64k.c" \
  -L"${OUT_DIR}" -Wl,-rpath,"${OUT_DIR}" -lhakozuna_hz5_standalone \
  -pthread -o "$BENCH"

echo "[linux][hz5] building remote benchmark: ${REMOTE_BENCH}"
gcc -O3 -Wall -Wextra -Werror -std=c11 -D_POSIX_C_SOURCE=200809L \
  "${SPEED_LINK_COMPILE_FLAGS[@]}" \
  -I"${HZ5_DIR}/include" \
  "${ROOT_DIR}/bench/bench_hz5_standalone_remote64k.c" \
  -L"${OUT_DIR}" -Wl,-rpath,"${OUT_DIR}" -lhakozuna_hz5_standalone \
  -pthread -o "$REMOTE_BENCH"

echo "[linux][hz5] building RSS plateau benchmark: ${RSS_BENCH}"
gcc -O3 -Wall -Wextra -Werror -std=c11 -D_POSIX_C_SOURCE=200809L \
  "${SPEED_LINK_COMPILE_FLAGS[@]}" \
  -I"${HZ5_DIR}/include" \
  "${ROOT_DIR}/bench/bench_hz5_standalone_rss_plateau.c" \
  -L"${OUT_DIR}" -Wl,-rpath,"${OUT_DIR}" -lhakozuna_hz5_standalone \
  -pthread -o "$RSS_BENCH"

echo "[linux][hz5] building mixed prelude benchmark: ${MIXED_BENCH}"
gcc -O3 -Wall -Wextra -Werror -std=c11 -D_POSIX_C_SOURCE=200809L \
  "${SPEED_LINK_COMPILE_FLAGS[@]}" \
  -I"${HZ5_DIR}/include" \
  "${ROOT_DIR}/bench/bench_hz5_standalone_mixed_prelude.c" \
  -L"${OUT_DIR}" -Wl,-rpath,"${OUT_DIR}" -lhakozuna_hz5_standalone \
  -pthread -o "$MIXED_BENCH"

echo "[linux][hz5] building safety benchmark: ${SAFETY_BENCH}"
gcc "${COMMON_FLAGS[@]}" -Werror -D_POSIX_C_SOURCE=200809L \
  "${ROOT_DIR}/bench/bench_hz5_standalone_safety.c" \
  -L"${OUT_DIR}" -Wl,-rpath,"${OUT_DIR}" -lhakozuna_hz5_standalone \
  -pthread -o "$SAFETY_BENCH"

echo "[linux][hz5] building MidPage direct benchmark: ${MIDPAGE_DIRECT_BENCH}"
gcc -O3 -Wall -Wextra -Werror -std=c11 -D_POSIX_C_SOURCE=200809L \
  "${SPEED_LINK_COMPILE_FLAGS[@]}" \
  -I"${HZ5_DIR}/include" \
  -I"${HZ5_DIR}/midpagefront" \
  "${ROOT_DIR}/bench/bench_hz5_midpage_direct.c" \
  -L"${OUT_DIR}" -Wl,-rpath,"${OUT_DIR}" -lhakozuna_hz5_standalone \
  -pthread -o "$MIDPAGE_DIRECT_BENCH"

mkdir -p "$(dirname "$GENERIC_BENCH")"
echo "[linux][hz5] building generic aligned benchmark: ${GENERIC_BENCH}"
gcc -O3 -Wall -Wextra -Werror -std=c11 -D_POSIX_C_SOURCE=200809L \
  "${ROOT_DIR}/bench/bench_aligned64k.c" \
  -pthread -o "$GENERIC_BENCH"

echo "[linux][hz5] building generic remote benchmark: ${GENERIC_REMOTE_BENCH}"
gcc -O3 -Wall -Wextra -Werror -std=c11 -D_POSIX_C_SOURCE=200809L \
  "${ROOT_DIR}/bench/bench_remote64k.c" \
  -pthread -o "$GENERIC_REMOTE_BENCH"

echo "[linux][hz5] building generic RSS plateau benchmark: ${GENERIC_RSS_BENCH}"
gcc -O3 -Wall -Wextra -Werror -std=c11 -D_POSIX_C_SOURCE=200809L \
  "${ROOT_DIR}/bench/bench_rss_plateau.c" \
  -pthread -o "$GENERIC_RSS_BENCH"

echo "[linux][hz5] building generic mixed prelude benchmark: ${GENERIC_MIXED_BENCH}"
gcc -O3 -Wall -Wextra -Werror -std=c11 -D_POSIX_C_SOURCE=200809L \
  "${ROOT_DIR}/bench/bench_mixed_prelude.c" \
  -pthread -o "$GENERIC_MIXED_BENCH"

echo "[linux][hz5] done"
