#!/usr/bin/env bash
# Sourced by hz5_build_lowlevel_args.sh.

hz5_try_parse_exact_build_arg() {
  HZ5_PARSE_SHIFT=0

  case "$1" in
      --linux-local2p)
        LINUX_LOCAL2P=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-local2p-tls-packed)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_TLS_PACKED=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-local2p-initial-exec)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_TLS_INITIAL_EXEC=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-local2p-direct-route)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_DIRECT_ROUTE=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-local2p-direct-init)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_DIRECT_INIT=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-local2p-fast)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_TLS_PACKED=1
        LINUX_LOCAL2P_TLS_INITIAL_EXEC=1
        LINUX_LOCAL2P_DIRECT_ROUTE=1
        LINUX_LOCAL2P_DIRECT_INIT=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-local2p-no-cookie)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_NO_COOKIE=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-local2p-no-cas)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_NO_CAS=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-local2p-owner-inbox)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_TLS_PACKED=1
        LINUX_LOCAL2P_OWNER_INBOX=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-local2p-remote-batch)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_TLS_PACKED=1
        LINUX_LOCAL2P_TLS_INITIAL_EXEC=1
        LINUX_LOCAL2P_OWNER_INBOX=1
        LINUX_LOCAL2P_REMOTE_BATCH=1
        LINUX_LOCAL2P_DIRECT_ROUTE=1
        LINUX_LOCAL2P_DIRECT_INIT=1
        LINUX_LOCAL2P_OBJECT_NODE=1
        LINUX_LOCAL2P_SAME_OWNER_FAST_STATE=1
        LINUX_LOCAL2P_ROUTE_COOKIE=1
        LINUX_LOCAL2P_REUSE_STATE_ONLY=1
        LINUX_LOCAL2P_SLIM_CHECK=1
        LINUX_LOCAL2P_FAST_COOKIE=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-local2p-remote-batch-cap)
        require_value "$@"
        LINUX_LOCAL2P_REMOTE_BATCH_CAP="$2"
        HZ5_PARSE_SHIFT=2
        ;;
      --linux-local2p-tls-cap)
        require_value "$@"
        LINUX_LOCAL2P_TLS_CAP="$2"
        HZ5_PARSE_SHIFT=2
        ;;
      --linux-local2p-global-cap)
        require_value "$@"
        LINUX_LOCAL2P_GLOBAL_CAP="$2"
        HZ5_PARSE_SHIFT=2
        ;;
      --linux-local2p-object-node)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_TLS_PACKED=1
        LINUX_LOCAL2P_TLS_INITIAL_EXEC=1
        LINUX_LOCAL2P_DIRECT_ROUTE=1
        LINUX_LOCAL2P_DIRECT_INIT=1
        LINUX_LOCAL2P_OBJECT_NODE=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-local2p-same-owner-fast-state)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_TLS_PACKED=1
        LINUX_LOCAL2P_TLS_INITIAL_EXEC=1
        LINUX_LOCAL2P_DIRECT_ROUTE=1
        LINUX_LOCAL2P_DIRECT_INIT=1
        LINUX_LOCAL2P_OBJECT_NODE=1
        LINUX_LOCAL2P_SAME_OWNER_FAST_STATE=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-local2p-route-cookie)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_TLS_PACKED=1
        LINUX_LOCAL2P_TLS_INITIAL_EXEC=1
        LINUX_LOCAL2P_DIRECT_ROUTE=1
        LINUX_LOCAL2P_DIRECT_INIT=1
        LINUX_LOCAL2P_OBJECT_NODE=1
        LINUX_LOCAL2P_SAME_OWNER_FAST_STATE=1
        LINUX_LOCAL2P_ROUTE_COOKIE=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-local2p-reuse-state-only)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_TLS_PACKED=1
        LINUX_LOCAL2P_TLS_INITIAL_EXEC=1
        LINUX_LOCAL2P_DIRECT_ROUTE=1
        LINUX_LOCAL2P_DIRECT_INIT=1
        LINUX_LOCAL2P_OBJECT_NODE=1
        LINUX_LOCAL2P_SAME_OWNER_FAST_STATE=1
        LINUX_LOCAL2P_ROUTE_COOKIE=1
        LINUX_LOCAL2P_REUSE_STATE_ONLY=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-local2p-slim-check)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_TLS_PACKED=1
        LINUX_LOCAL2P_TLS_INITIAL_EXEC=1
        LINUX_LOCAL2P_DIRECT_ROUTE=1
        LINUX_LOCAL2P_DIRECT_INIT=1
        LINUX_LOCAL2P_OBJECT_NODE=1
        LINUX_LOCAL2P_SAME_OWNER_FAST_STATE=1
        LINUX_LOCAL2P_ROUTE_COOKIE=1
        LINUX_LOCAL2P_REUSE_STATE_ONLY=1
        LINUX_LOCAL2P_SLIM_CHECK=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-local2p-fast-cookie)
        enable_local2p_fast_cookie_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-local2p-free-first|--linux-local2p-freefirst-fastcookie)
        enable_local2p_fast_cookie_base
        LINUX_LOCAL2P_FREE_FIRST=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-local2p-tls-fast-return)
        enable_local2p_tls_fast_return_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-local2p-exact-api)
        enable_local2p_exact_api_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-local2p-single-slot-tls)
        enable_local2p_exact_api_base
        LINUX_LOCAL2P_SINGLE_SLOT_TLS=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-local2p-speed-linkflags)
        enable_local2p_speed_linkflags_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-local2p-rss-retain)
        enable_local2p_speed_linkflags_base
        LINUX_LOCAL2P_LOCAL_OVERFLOW_GLOBAL=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-local2p-retain-array)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_TLS_PACKED=1
        LINUX_LOCAL2P_RETAIN_ARRAY=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-p11-speed-core)
        LINUX_P11_SPEED_CORE=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-p25-bridge-attr)
        LINUX_P25_BRIDGE_ATTR=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-p25-bridge-attr-no-cas)
        LINUX_P25_BRIDGE_ATTR=1
        LINUX_P25_BRIDGE_ATTR_NO_CAS=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-p25-bridge-attr-no-cookie)
        LINUX_P25_BRIDGE_ATTR=1
        LINUX_P25_BRIDGE_ATTR_NO_COOKIE=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-p25-bridge-attr-readonly-state)
        LINUX_P25_BRIDGE_ATTR=1
        LINUX_P25_BRIDGE_ATTR_READONLY_STATE=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-p43)
        ENABLE_LINUX_P43=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-p43-no-prepared-bridge)
        ENABLE_LINUX_P43=1
        LINUX_P43_PREPARED_BRIDGE=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-p43-unsafe-no-lookup)
        ENABLE_LINUX_P43=1
        LINUX_P43_UNSAFE_NO_LOOKUP=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-p43-trust-fast-lookup)
        ENABLE_LINUX_P43=1
        LINUX_P43_TRUST_FAST_LOOKUP=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-p43-trust-wrapper-source)
        ENABLE_LINUX_P43=1
        LINUX_P43_TRUST_WRAPPER_SOURCE=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-p43-decoded-raw-lookup)
        ENABLE_LINUX_P43=1
        LINUX_P43_DECODED_RAW_LOOKUP=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-p43-decoded-raw-fastlookup)
        ENABLE_LINUX_P43=1
        LINUX_P43_DECODED_RAW_LOOKUP=1
        LINUX_P43_RAW_FAST_LOOKUP_ONLY=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-p43-decoded-raw-allocated)
        ENABLE_LINUX_P43=1
        LINUX_P43_DECODED_RAW_LOOKUP=1
        LINUX_P43_RAW_FAST_LOOKUP_ONLY=1
        LINUX_P43_RAW_ALLOCATED_LOOKUP_ONLY=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-p43-token)
        ENABLE_LINUX_P43=1
        LINUX_P43_WRAPPER_TOKEN=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-p43-token-bridge)
        ENABLE_LINUX_P43=1
        LINUX_P43_WRAPPER_TOKEN=1
        LINUX_P43_WRAPPER_TOKEN_BRIDGE=1
        HZ5_PARSE_SHIFT=1
        ;;
    *)
      return 1
      ;;
  esac

  return 0
}
