#!/usr/bin/env bash
# Sourced by build_linux_hz5_standalone.sh after defaults and profile helper functions are defined.
# Keep option parsing here so the build driver stays readable.
hz5_parse_build_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --linux-hz5-profile-pagerun64-main)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_base 2
        shift
        ;;
      --linux-hz5-profile-pagerun64-cross128)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_takefirst_base 2
        LINUX_LARGEFRONT_SOURCE_BATCH_COUNT=16
        shift
        ;;
      --linux-hz5-profile-pagerun64-large128|--linux-hz5-profile-large128-rss)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_large128_batch_base 4
        shift
        ;;
      --linux-hz5-profile-pagerun64-large128-batch8)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_large128_batch_base 8
        shift
        ;;
      --linux-hz5-profile-pagerun64-large128-batch16|--linux-hz5-profile-large128-source16)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_large128_batch_base 16
        shift
        ;;
      --linux-hz5-profile-pagerun64-large128-b16-drain1|--linux-hz5-profile-large128-r50-drain)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_large128_batch_base 16
        LINUX_LARGEFRONT_ALLOC_DRAIN_LOCAL_BUDGET=1
        shift
        ;;
      --linux-hz5-profile-pagerun64-large128-b16-takeonly)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_large128_batch_base 16
        LINUX_LARGEFRONT_DRAIN_TAKE_ONLY=1
        shift
        ;;
      --linux-hz5-profile-pagerun64-large128-b16-popbudget1)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_large128_batch_base 16
        LINUX_LARGEFRONT_ALLOC_DRAIN_LOCAL_BUDGET=1
        LINUX_LARGEFRONT_DRAIN_POP_BUDGET=1
        shift
        ;;
      --linux-hz5-profile-pagerun64-large128-b16-remotehold4)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_large128_batch_base 16
        LINUX_LARGEFRONT_DRAIN_TAKE_ONLY=1
        LINUX_LARGEFRONT_REMOTE_HOLD=1
        LINUX_LARGEFRONT_REMOTE_HOLD_CAP=4
        shift
        ;;
      --linux-hz5-profile-pagerun64-large128-b16-drain1-hold4|--linux-hz5-profile-large128-r50-hold)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_large128_batch_base 16
        LINUX_LARGEFRONT_ALLOC_DRAIN_LOCAL_BUDGET=1
        LINUX_LARGEFRONT_REMOTE_HOLD=1
        LINUX_LARGEFRONT_REMOTE_HOLD_CAP=4
        shift
        ;;
      --linux-hz5-profile-pagerun64-large128-b16-drain1-hold8|--linux-hz5-profile-large128-r50-hold8)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_large128_batch_base 16
        LINUX_LARGEFRONT_ALLOC_DRAIN_LOCAL_BUDGET=1
        LINUX_LARGEFRONT_REMOTE_HOLD=1
        LINUX_LARGEFRONT_REMOTE_HOLD_CAP=8
        shift
        ;;
      --linux-hz5-profile-large128-direct-header)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_large128_batch_base 16
        LINUX_LARGEFRONT_DIRECT_HEADER_LOOKUP=1
        shift
        ;;
      --linux-hz5-profile-large128-base-directmap)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_large128_batch_base 16
        LINUX_LARGEFRONT_BASE_DIRECTMAP=1
        shift
        ;;
      --linux-hz5-profile-large128-global-remote)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_large128_batch_base 16
        LINUX_LARGEFRONT_REMOTE_GLOBAL_128K=1
        shift
        ;;
      --linux-hz5-profile-large128-remote-first)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_large128_batch_base 16
        LINUX_LARGEFRONT_REMOTE_FIRST_128K=1
        shift
        ;;
      --linux-hz5-profile-large128-remote-first-gated)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_large128_batch_base 16
        LINUX_LARGEFRONT_REMOTE_FIRST_GATED_128K=1
        shift
        ;;
      --linux-hz5-profile-large128-chunk16)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_large128_batch_base 16
        LINUX_LARGEFRONT_REMOTE_BATCH=1
        LINUX_LARGEFRONT_REMOTE_BATCH_CAP=16
        LINUX_LARGEFRONT_REMOTE_CHUNK_INBOX=1
        LINUX_LARGEFRONT_REMOTE_CHUNK_CAP=16
        shift
        ;;
      --linux-hz5-profile-pagerun64-large128-b16-policy-l7|--linux-hz5-profile-large128-policy-l7)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_large128_batch_base 16
        LINUX_LARGEFRONT_ALLOC_DRAIN_LOCAL_BUDGET=1
        LINUX_LARGEFRONT_REMOTE_HOLD=1
        LINUX_LARGEFRONT_REMOTE_HOLD_CAP=4
        LINUX_LARGEFRONT_POLICY_L7=1
        LINUX_LARGEFRONT_POLICY_L7_REMAINDER_LOCAL_THRESHOLD=32
        shift
        ;;
      --linux-hz5-profile-large128-policy-l8-shadow)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_large128_batch_base 16
        LINUX_LARGEFRONT_ALLOC_DRAIN_LOCAL_BUDGET=1
        LINUX_LARGEFRONT_REMOTE_HOLD=1
        LINUX_LARGEFRONT_REMOTE_HOLD_CAP=4
        LINUX_LARGEFRONT_POLICY_L0=1
        LINUX_LARGEFRONT_POLICY_L8_SHADOW=1
        LINUX_LARGEFRONT_POLICY_L8_HEAVY_SPANS=32
        shift
        ;;
      --linux-hz5-profile-pagerun64-large128-b16-rb32)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_large128_batch16_rbatch_base 32
        shift
        ;;
      --linux-hz5-profile-pagerun64-large128-b16-rb64)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_large128_batch16_rbatch_base 64
        shift
        ;;
      --linux-hz5-profile-pagerun64-large128-policy-l0)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_policy_l0_base 2
        shift
        ;;
      --linux-hz5-profile-pagerun64-large128-policy-l1a)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_policy_l1a_base 2
        shift
        ;;
      --linux-hz5-profile-pagerun64-large128-policy-l1b)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_policy_l1b_base
        shift
        ;;
      --arch)
        require_value "$@"
        ARCH="$2"
        shift 2
        ;;
      --out-dir)
        require_value "$@"
        OUT_DIR="$2"
        shift 2
        ;;
      --linux-local2p)
        LINUX_LOCAL2P=1
        shift
        ;;
      --linux-local2p-tls-packed)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_TLS_PACKED=1
        shift
        ;;
      --linux-local2p-initial-exec)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_TLS_INITIAL_EXEC=1
        shift
        ;;
      --linux-local2p-direct-route)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_DIRECT_ROUTE=1
        shift
        ;;
      --linux-local2p-direct-init)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_DIRECT_INIT=1
        shift
        ;;
      --linux-local2p-fast)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_TLS_PACKED=1
        LINUX_LOCAL2P_TLS_INITIAL_EXEC=1
        LINUX_LOCAL2P_DIRECT_ROUTE=1
        LINUX_LOCAL2P_DIRECT_INIT=1
        shift
        ;;
      --linux-local2p-no-cookie)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_NO_COOKIE=1
        shift
        ;;
      --linux-local2p-no-cas)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_NO_CAS=1
        shift
        ;;
      --linux-local2p-owner-inbox)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_TLS_PACKED=1
        LINUX_LOCAL2P_OWNER_INBOX=1
        shift
        ;;
      --linux-local2p-remote-batch)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_TLS_PACKED=1
        LINUX_LOCAL2P_TLS_INITIAL_EXEC=1
        LINUX_LOCAL2P_OWNER_INBOX=1
        LINUX_LOCAL2P_REMOTE_BATCH=1
        LINUX_LOCAL2P_DIRECT_ROUTE=1
        LINUX_LOCAL2P_DIRECT_INIT=1
        LINUX_LOCAL2P_OBJECT_NODE=1
        LINUX_LOCAL2P_SAME_OWNER_FAST_STATE=1
        LINUX_LOCAL2P_ROUTE_COOKIE=1
        LINUX_LOCAL2P_REUSE_STATE_ONLY=1
        LINUX_LOCAL2P_SLIM_CHECK=1
        LINUX_LOCAL2P_FAST_COOKIE=1
        shift
        ;;
      --linux-local2p-remote-batch-cap)
        require_value "$@"
        LINUX_LOCAL2P_REMOTE_BATCH_CAP="$2"
        shift 2
        ;;
      --linux-local2p-tls-cap)
        require_value "$@"
        LINUX_LOCAL2P_TLS_CAP="$2"
        shift 2
        ;;
      --linux-local2p-global-cap)
        require_value "$@"
        LINUX_LOCAL2P_GLOBAL_CAP="$2"
        shift 2
        ;;
      --linux-local2p-object-node)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_TLS_PACKED=1
        LINUX_LOCAL2P_TLS_INITIAL_EXEC=1
        LINUX_LOCAL2P_DIRECT_ROUTE=1
        LINUX_LOCAL2P_DIRECT_INIT=1
        LINUX_LOCAL2P_OBJECT_NODE=1
        shift
        ;;
      --linux-local2p-same-owner-fast-state)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_TLS_PACKED=1
        LINUX_LOCAL2P_TLS_INITIAL_EXEC=1
        LINUX_LOCAL2P_DIRECT_ROUTE=1
        LINUX_LOCAL2P_DIRECT_INIT=1
        LINUX_LOCAL2P_OBJECT_NODE=1
        LINUX_LOCAL2P_SAME_OWNER_FAST_STATE=1
        shift
        ;;
      --linux-local2p-route-cookie)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_TLS_PACKED=1
        LINUX_LOCAL2P_TLS_INITIAL_EXEC=1
        LINUX_LOCAL2P_DIRECT_ROUTE=1
        LINUX_LOCAL2P_DIRECT_INIT=1
        LINUX_LOCAL2P_OBJECT_NODE=1
        LINUX_LOCAL2P_SAME_OWNER_FAST_STATE=1
        LINUX_LOCAL2P_ROUTE_COOKIE=1
        shift
        ;;
      --linux-local2p-reuse-state-only)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_TLS_PACKED=1
        LINUX_LOCAL2P_TLS_INITIAL_EXEC=1
        LINUX_LOCAL2P_DIRECT_ROUTE=1
        LINUX_LOCAL2P_DIRECT_INIT=1
        LINUX_LOCAL2P_OBJECT_NODE=1
        LINUX_LOCAL2P_SAME_OWNER_FAST_STATE=1
        LINUX_LOCAL2P_ROUTE_COOKIE=1
        LINUX_LOCAL2P_REUSE_STATE_ONLY=1
        shift
        ;;
      --linux-local2p-slim-check)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_TLS_PACKED=1
        LINUX_LOCAL2P_TLS_INITIAL_EXEC=1
        LINUX_LOCAL2P_DIRECT_ROUTE=1
        LINUX_LOCAL2P_DIRECT_INIT=1
        LINUX_LOCAL2P_OBJECT_NODE=1
        LINUX_LOCAL2P_SAME_OWNER_FAST_STATE=1
        LINUX_LOCAL2P_ROUTE_COOKIE=1
        LINUX_LOCAL2P_REUSE_STATE_ONLY=1
        LINUX_LOCAL2P_SLIM_CHECK=1
        shift
        ;;
      --linux-local2p-fast-cookie)
        enable_local2p_fast_cookie_base
        shift
        ;;
      --linux-local2p-free-first|--linux-local2p-freefirst-fastcookie)
        enable_local2p_fast_cookie_base
        LINUX_LOCAL2P_FREE_FIRST=1
        shift
        ;;
      --linux-local2p-tls-fast-return)
        enable_local2p_tls_fast_return_base
        shift
        ;;
      --linux-local2p-exact-api)
        enable_local2p_exact_api_base
        shift
        ;;
      --linux-local2p-single-slot-tls)
        enable_local2p_exact_api_base
        LINUX_LOCAL2P_SINGLE_SLOT_TLS=1
        shift
        ;;
      --linux-local2p-speed-linkflags)
        enable_local2p_speed_linkflags_base
        shift
        ;;
      --linux-local2p-rss-retain)
        enable_local2p_speed_linkflags_base
        LINUX_LOCAL2P_LOCAL_OVERFLOW_GLOBAL=1
        shift
        ;;
      --linux-local2p-retain-array)
        LINUX_LOCAL2P=1
        LINUX_LOCAL2P_TLS_PACKED=1
        LINUX_LOCAL2P_RETAIN_ARRAY=1
        shift
        ;;
      --linux-p11-speed-core)
        LINUX_P11_SPEED_CORE=1
        shift
        ;;
      --linux-p25-bridge-attr)
        LINUX_P25_BRIDGE_ATTR=1
        shift
        ;;
      --linux-p25-bridge-attr-no-cas)
        LINUX_P25_BRIDGE_ATTR=1
        LINUX_P25_BRIDGE_ATTR_NO_CAS=1
        shift
        ;;
      --linux-p25-bridge-attr-no-cookie)
        LINUX_P25_BRIDGE_ATTR=1
        LINUX_P25_BRIDGE_ATTR_NO_COOKIE=1
        shift
        ;;
      --linux-p25-bridge-attr-readonly-state)
        LINUX_P25_BRIDGE_ATTR=1
        LINUX_P25_BRIDGE_ATTR_READONLY_STATE=1
        shift
        ;;
      --linux-p43)
        ENABLE_LINUX_P43=1
        shift
        ;;
      --linux-p43-no-prepared-bridge)
        ENABLE_LINUX_P43=1
        LINUX_P43_PREPARED_BRIDGE=0
        shift
        ;;
      --linux-p43-unsafe-no-lookup)
        ENABLE_LINUX_P43=1
        LINUX_P43_UNSAFE_NO_LOOKUP=1
        shift
        ;;
      --linux-p43-trust-fast-lookup)
        ENABLE_LINUX_P43=1
        LINUX_P43_TRUST_FAST_LOOKUP=1
        shift
        ;;
      --linux-p43-trust-wrapper-source)
        ENABLE_LINUX_P43=1
        LINUX_P43_TRUST_WRAPPER_SOURCE=1
        shift
        ;;
      --linux-p43-decoded-raw-lookup)
        ENABLE_LINUX_P43=1
        LINUX_P43_DECODED_RAW_LOOKUP=1
        shift
        ;;
      --linux-p43-decoded-raw-fastlookup)
        ENABLE_LINUX_P43=1
        LINUX_P43_DECODED_RAW_LOOKUP=1
        LINUX_P43_RAW_FAST_LOOKUP_ONLY=1
        shift
        ;;
      --linux-p43-decoded-raw-allocated)
        ENABLE_LINUX_P43=1
        LINUX_P43_DECODED_RAW_LOOKUP=1
        LINUX_P43_RAW_FAST_LOOKUP_ONLY=1
        LINUX_P43_RAW_ALLOCATED_LOOKUP_ONLY=1
        shift
        ;;
      --linux-p43-token)
        ENABLE_LINUX_P43=1
        LINUX_P43_WRAPPER_TOKEN=1
        shift
        ;;
      --linux-p43-token-bridge)
        ENABLE_LINUX_P43=1
        LINUX_P43_WRAPPER_TOKEN=1
        LINUX_P43_WRAPPER_TOKEN_BRIDGE=1
        shift
        ;;
      --linux-preload-full)
        BUILD_PRELOAD_FULL=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-smallfront-s1)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-smallfront-remote-batch-cap)
        require_value "$@"
        LINUX_SMALLFRONT_REMOTE_BATCH_CAP="$2"
        shift 2
        ;;
      --linux-smallfront-drain-empty-gated)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_SMALLFRONT_DRAIN_EMPTY_GATED=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-smallfront-remote-outbox)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_SMALLFRONT_REMOTE_OUTBOX=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-hz5-general-region-outbox)
        enable_general_region_outbox_base
        shift
        ;;
      --linux-hz5-general-directfree)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_SMALLFRONT_REMOTE_OUTBOX=1
        LINUX_SMALLFRONT_REMOTE_BATCH_CAP=8
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_OWNER_FAST_STATE=1
        LINUX_MIDFRONT_REMOTE_BATCH_CAP=16
        LINUX_MIDFRONT_REMOTE_DIRECT_FREE_STATE=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_OWNER_FAST_STATE=1
        LINUX_LARGEFRONT_REGION_MAP=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-hz5-general-midfirst)
        BUILD_PRELOAD_FULL=1
        PRELOAD_FREE_MID_FIRST=1
        LINUX_SMALLFRONT_S1=1
        LINUX_SMALLFRONT_REMOTE_OUTBOX=1
        LINUX_SMALLFRONT_REMOTE_BATCH_CAP=8
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_OWNER_FAST_STATE=1
        LINUX_MIDFRONT_REMOTE_BATCH_CAP=16
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_OWNER_FAST_STATE=1
        LINUX_LARGEFRONT_REGION_MAP=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-hz5-general-midcache)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_SMALLFRONT_REMOTE_OUTBOX=1
        LINUX_SMALLFRONT_REMOTE_BATCH_CAP=8
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_OWNER_FAST_STATE=1
        LINUX_MIDFRONT_REMOTE_BATCH_CAP=16
        LINUX_MIDFRONT_LOOKUP_CACHE=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_OWNER_FAST_STATE=1
        LINUX_LARGEFRONT_REGION_MAP=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-hz5-general-midrbuf)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_SMALLFRONT_REMOTE_OUTBOX=1
        LINUX_SMALLFRONT_REMOTE_BATCH_CAP=8
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_OWNER_FAST_STATE=1
        LINUX_MIDFRONT_REMOTE_BATCH_CAP=16
        LINUX_MIDFRONT_REMOTE_RBUF=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_OWNER_FAST_STATE=1
        LINUX_LARGEFRONT_REGION_MAP=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-hz5-general-routesplit)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_SMALLFRONT_REMOTE_OUTBOX=1
        LINUX_SMALLFRONT_REMOTE_BATCH_CAP=8
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_OWNER_FAST_STATE=1
        LINUX_MIDFRONT_REMOTE_BATCH_CAP=16
        LINUX_MIDFRONT_MAX_BYTES=4096
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_OWNER_FAST_STATE=1
        LINUX_LARGEFRONT_REGION_MAP=1
        LINUX_LARGEFRONT_LOWER_CLASSES=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-hz5-general-midpage)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_SMALLFRONT_REMOTE_OUTBOX=1
        LINUX_SMALLFRONT_REMOTE_BATCH_CAP=8
        LINUX_MIDPAGEFRONT_M2=1
        LINUX_MIDPAGEFRONT_REMOTE_BATCH_CAP=16
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_OWNER_FAST_STATE=1
        LINUX_MIDFRONT_REMOTE_BATCH_CAP=16
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_OWNER_FAST_STATE=1
        LINUX_LARGEFRONT_REGION_MAP=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-hz5-general-midpage-region)
        enable_midpage_region_base
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow)
        enable_midpage_region_shadow_base
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-frontfirst)
        enable_midpage_region_shadow_base
        PRELOAD_FREE_MIDPAGE_FIRST=1
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-tlscache)
        enable_midpage_region_shadow_base
        LINUX_MIDPAGEFRONT_TLS_REGION_CACHE=1
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-hotslot)
        enable_midpage_region_shadow_base
        LINUX_MIDPAGEFRONT_TLS_HOT_SLOT=1
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-activetrust)
        enable_midpage_region_shadow_base
        LINUX_MIDPAGEFRONT_LOCAL_ACTIVE_TRUST=1
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-allocfirst)
        enable_midpage_shadow_allocfirst_base
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-localunsafe)
        enable_midpage_shadow_allocfirst_base
        LINUX_MIDPAGEFRONT_UNSAFE_LOCAL_NOCHECK=1
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4mag)
        enable_midpage_m4mag_base
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet)
        enable_midpage_m4packet_base
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst)
        enable_midpage_m4packet_freefirst_base
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink)
        enable_midpage_m4packet_freefirst_tlslink_base
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-allocelide)
        enable_midpage_m4packet_freefirst_tlslink_allocelide_base
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-ptrmag)
        enable_midpage_m4packet_freefirst_tlslink_ptrmag_base
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-absalloc)
        enable_midpage_m4packet_freefirst_tlslink_absalloc_base
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-regcache)
        enable_midpage_m4packet_freefirst_tlslink_regcache_base
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-slotswitch)
        enable_midpage_m4packet_freefirst_tlslink_slotswitch_base
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-superfast)
        enable_midpage_m4packet_freefirst_tlslink_superfast_base
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-superfast-freeelide)
        enable_midpage_m4packet_freefirst_tlslink_superfast_freeelide_base
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-m5hit)
        enable_midpage_m4packet_freefirst_tlslink_m5hit_base
        shift
        ;;
      --linux-hz5-general-midpage-m6-deferred-free-direct)
        enable_midpage_m6_deferred_free_direct_base
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-flatcap)
        enable_midpage_m4packet_freefirst_tlslink_flatcap_base
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-overarray)
        enable_midpage_m4packet_freefirst_tlslink_overarray_base
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-wide32k)
        enable_midpage_m4packet_freefirst_tlslink_wide32k_base
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band4-16-32)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_base 1
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band4-8-16-32)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_base 4
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band4-8-32)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_base 5
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_base 2
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rssgov)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rssgov_base 2
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_base 2
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m6remote)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_base 2
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m7ticket)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m7ticket_base 2
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m6remote-m8xfer)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_m8xfer_base 2
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m6remote-m9budget)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_m9budget_base 2
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m10slot)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m10slot_base 2
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m6remote-m11direct)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_m11direct_base 2
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m6remote-pagerun)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun_base 2
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m6remote-pagerun64)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_base 2
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m6remote-pagerun64-takefirst)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_takefirst_base 2
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m6remote-pagerun64-adaptive128)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_adaptive128_base 2
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m6remote-pagerun64-scavenge)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_scavenge_base 2
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m6remote-pagerun64-observe)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_observe_base 2
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-drainhit)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_drainhit_base 2
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-16-32)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_base 6
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-16-32-rssgov)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rssgov_base 6
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-16-32-rsscheckpoint)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_base 6
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-16-32-rsscheckpoint-drainhit)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_drainhit_base 6
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band16-32)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_base 3
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-tagfree)
        enable_midpage_m4packet_freefirst_tlslink_tagfree_base
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-m4stats)
        enable_midpage_m4packet_freefirst_tlslink_m4stats_base
        shift
        ;;
      --linux-midpagefront-m6-raw-cap)
        require_value "$@"
        LINUX_MIDPAGEFRONT_M6_RAW_CAP="$2"
        shift 2
        ;;
      --linux-midpagefront-m6-deferred-free)
        LINUX_MIDPAGEFRONT_M6_DEFERRED_FREE=1
        shift
        ;;
      --linux-midpagefront-m6-remote-deferred-free)
        LINUX_MIDPAGEFRONT_M6_REMOTE_DEFERRED_FREE=1
        shift
        ;;
      --linux-midpagefront-m6-remote-no-refill-flush)
        LINUX_MIDPAGEFRONT_M6_REMOTE_FLUSH_ON_REFILL=0
        shift
        ;;
      --linux-midpagefront-m7-remote-ticket)
        LINUX_MIDPAGEFRONT_M7_REMOTE_TICKET=1
        shift
        ;;
      --linux-midpagefront-m7-remote-page-cap)
        require_value "$@"
        LINUX_MIDPAGEFRONT_M7_REMOTE_PAGE_CAP="$2"
        shift 2
        ;;
      --linux-midpagefront-m8-owner-xfer)
        LINUX_MIDPAGEFRONT_M8_OWNER_XFER=1
        shift
        ;;
      --linux-midpagefront-m8-xfer-page-cap)
        require_value "$@"
        LINUX_MIDPAGEFRONT_M8_XFER_PAGE_CAP="$2"
        shift 2
        ;;
      --linux-midpagefront-m9-budget-drain)
        LINUX_MIDPAGEFRONT_M9_BUDGET_DRAIN=1
        shift
        ;;
      --linux-midpagefront-m10-remote-slot-ring)
        LINUX_MIDPAGEFRONT_M10_REMOTE_SLOT_RING=1
        shift
        ;;
      --linux-midpagefront-m11-remote-direct-cache)
        LINUX_MIDPAGEFRONT_M11_REMOTE_DIRECT_CACHE=1
        shift
        ;;
      --linux-midpagefront-pagerun)
        LINUX_MIDPAGEFRONT_PAGERUN=1
        shift
        ;;
      --linux-midpagefront-pagerun-64k)
        LINUX_MIDPAGEFRONT_PAGERUN_64K=1
        shift
        ;;
      --linux-midpagefront-m4-remote-drain-hit-interval)
        require_value "$@"
        LINUX_MIDPAGEFRONT_M4_REMOTE_DRAIN_HIT_INTERVAL="$2"
        shift 2
        ;;
      --linux-midpagefront-empty-slab-release)
        LINUX_MIDPAGEFRONT_EMPTY_SLAB_RELEASE=1
        shift
        ;;
      --linux-midpagefront-empty-release-checkpoint)
        LINUX_MIDPAGEFRONT_EMPTY_SLAB_RELEASE=1
        LINUX_MIDPAGEFRONT_EMPTY_RELEASE_ON_REFILL=0
        shift
        ;;
      --linux-midpagefront-empty-retain-cap)
        require_value "$@"
        LINUX_MIDPAGEFRONT_EMPTY_RETAIN_CAP="$2"
        shift 2
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-routefree)
        enable_midpage_m4packet_routefree_base
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-crossdrain)
        enable_midpage_m4packet_crossdrain_base
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-slotswitch)
        enable_midpage_shadow_allocfirst_base
        LINUX_MIDPAGEFRONT_SLOT_SWITCH=1
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-tlslink)
        enable_midpage_shadow_allocfirst_base
        PRELOAD_TLS_INITIAL_EXEC=1
        PRELOAD_SPEED_LINKFLAGS=1
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-tlsie)
        enable_midpage_shadow_allocfirst_base
        PRELOAD_TLS_INITIAL_EXEC=1
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-linkonly)
        enable_midpage_shadow_allocfirst_base
        PRELOAD_SPEED_LINKFLAGS=1
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-nodeless)
        enable_midpage_nodeless_base
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-nodeless-ptrcache)
        enable_midpage_nodeless_base
        LINUX_MIDPAGEFRONT_NODELESS_PTRCACHE=1
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-nodeless-stats)
        enable_midpage_nodeless_base
        LINUX_MIDPAGEFRONT_NODELESS_STATS=1
        shift
        ;;
      --linux-hz5-general-midpage-region-shadow-nodeless-ptrcache-stats)
        enable_midpage_nodeless_base
        LINUX_MIDPAGEFRONT_NODELESS_PTRCACHE=1
        LINUX_MIDPAGEFRONT_NODELESS_STATS=1
        shift
        ;;
      --linux-hz5-general-midpage-region-frontfirst)
        BUILD_PRELOAD_FULL=1
        PRELOAD_FREE_MIDPAGE_FIRST=1
        LINUX_SMALLFRONT_S1=1
        LINUX_SMALLFRONT_REMOTE_OUTBOX=1
        LINUX_SMALLFRONT_REMOTE_BATCH_CAP=8
        LINUX_MIDPAGEFRONT_M2=1
        LINUX_MIDPAGEFRONT_REGION_ARRAY=1
        LINUX_MIDPAGEFRONT_REMOTE_BATCH_CAP=16
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_OWNER_FAST_STATE=1
        LINUX_MIDFRONT_REMOTE_BATCH_CAP=16
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_OWNER_FAST_STATE=1
        LINUX_LARGEFRONT_REGION_MAP=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-hz5-general-midoutbox)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_SMALLFRONT_REMOTE_OUTBOX=1
        LINUX_SMALLFRONT_REMOTE_BATCH_CAP=8
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_OWNER_FAST_STATE=1
        LINUX_MIDFRONT_REMOTE_BATCH_CAP=16
        LINUX_MIDFRONT_REMOTE_OUTBOX=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_OWNER_FAST_STATE=1
        LINUX_LARGEFRONT_REGION_MAP=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-hz5-general-midoutbox-flush)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_SMALLFRONT_REMOTE_OUTBOX=1
        LINUX_SMALLFRONT_REMOTE_BATCH_CAP=8
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_OWNER_FAST_STATE=1
        LINUX_MIDFRONT_REMOTE_BATCH_CAP=16
        LINUX_MIDFRONT_REMOTE_OUTBOX=1
        LINUX_MIDFRONT_OUTBOX_FLUSH_ON_MISS=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_OWNER_FAST_STATE=1
        LINUX_LARGEFRONT_REGION_MAP=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-ownerhub-r1)
        BUILD_PRELOAD_FULL=1
        LINUX_OWNERHUB_R1=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-ownerhub-r2)
        BUILD_PRELOAD_FULL=1
        LINUX_OWNERHUB_R2=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-ownerhub-r3)
        BUILD_PRELOAD_FULL=1
        LINUX_OWNERHUB_R3=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-midfront-m1)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-midpagefront-m2)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDPAGEFRONT_M2=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-midpagefront-region-array)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDPAGEFRONT_M2=1
        LINUX_MIDPAGEFRONT_REGION_ARRAY=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-midpagefront-remote-shadow)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDPAGEFRONT_M2=1
        LINUX_MIDPAGEFRONT_REMOTE_SHADOW=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-midpagefront-local-fast-state)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDPAGEFRONT_M2=1
        LINUX_MIDPAGEFRONT_LOCAL_FAST_STATE=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-midpagefront-tls-region-cache)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDPAGEFRONT_M2=1
        LINUX_MIDPAGEFRONT_REGION_ARRAY=1
        LINUX_MIDPAGEFRONT_TLS_REGION_CACHE=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-midpagefront-tls-hot-slot)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDPAGEFRONT_M2=1
        LINUX_MIDPAGEFRONT_TLS_HOT_SLOT=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-midpagefront-local-active-trust)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDPAGEFRONT_M2=1
        LINUX_MIDPAGEFRONT_LOCAL_ACTIVE_TRUST=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-midpagefront-remote-batch-cap)
        require_value "$@"
        LINUX_MIDPAGEFRONT_REMOTE_BATCH_CAP="$2"
        shift 2
        ;;
      --linux-midfront-owner-fast-state)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_OWNER_FAST_STATE=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-midfront-max-bytes)
        require_value "$@"
        LINUX_MIDFRONT_MAX_BYTES="$2"
        shift 2
        ;;
      --linux-midfront-remote-batch-cap)
        require_value "$@"
        LINUX_MIDFRONT_REMOTE_BATCH_CAP="$2"
        shift 2
        ;;
      --linux-midfront-remote-outbox)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_REMOTE_OUTBOX=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-midfront-remote-outbox-slots)
        require_value "$@"
        LINUX_MIDFRONT_REMOTE_OUTBOX_SLOTS="$2"
        shift 2
        ;;
      --linux-midfront-remote-rbuf)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_REMOTE_RBUF=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-midfront-remote-rbuf-cap)
        require_value "$@"
        LINUX_MIDFRONT_REMOTE_RBUF_CAP="$2"
        shift 2
        ;;
      --linux-midfront-remote-rbuf-threshold)
        require_value "$@"
        LINUX_MIDFRONT_REMOTE_RBUF_FLUSH_THRESHOLD="$2"
        shift 2
        ;;
      --linux-midfront-outbox-flush-on-miss)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_REMOTE_OUTBOX=1
        LINUX_MIDFRONT_OUTBOX_FLUSH_ON_MISS=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-midfront-remote-direct-free-state)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_REMOTE_DIRECT_FREE_STATE=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-midfront-remote-trust-drain-state)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_REMOTE_DIRECT_FREE_STATE=1
        LINUX_MIDFRONT_REMOTE_TRUST_DRAIN_STATE=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-midfront-lookup-cache)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_LOOKUP_CACHE=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-midfront-drain-all-on-miss)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_DRAIN_ALL_ON_MISS=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-midfront-drain-mask-on-miss)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_DRAIN_MASK_ON_MISS=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-midfront-drain-mask-hit-stop)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_DRAIN_MASK_ON_MISS=1
        LINUX_MIDFRONT_DRAIN_MASK_HIT_STOP=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-midfront-drain-take-first)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_DRAIN_TAKE_FIRST=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-midfront-drain-empty-gated)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_DRAIN_EMPTY_GATED=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-midfront-remote-global-recycle)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_REMOTE_GLOBAL_RECYCLE=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-largefront-l1)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-largefront-owner-fast-state)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_FAST_STATE=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-largefront-owner-inbox)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-largefront-remote-batch)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_REMOTE_BATCH=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-largefront-remote-batch-cap)
        require_value "$@"
        LINUX_LARGEFRONT_REMOTE_BATCH_CAP="$2"
        shift 2
        ;;
      --linux-largefront-source-batch-count)
        require_value "$@"
        LINUX_LARGEFRONT_SOURCE_BATCH_COUNT="$2"
        BUILD_PRELOAD_FULL=1
        shift 2
        ;;
      --linux-largefront-alloc-drain-local-budget)
        require_value "$@"
        LINUX_LARGEFRONT_ALLOC_DRAIN_LOCAL_BUDGET="$2"
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift 2
        ;;
      --linux-largefront-drain-take-first)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_DRAIN_TAKE_FIRST=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-largefront-drain-empty-gated)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_DRAIN_EMPTY_GATED=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-largefront-map-base-only)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_MAP_BASE_ONLY=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-largefront-region-map)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_REGION_MAP=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-largefront-adaptive128)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_REGION_MAP=1
        LINUX_LARGEFRONT_DRAIN_TAKE_FIRST=1
        LINUX_LARGEFRONT_ADAPTIVE128=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-largefront-payload-scavenge)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_REGION_MAP=1
        LINUX_LARGEFRONT_PAYLOAD_SCAVENGE=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-largefront-observe)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_REGION_MAP=1
        LINUX_LARGEFRONT_OBSERVE=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-largefront-policy-l0)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_REGION_MAP=1
        LINUX_LARGEFRONT_POLICY_L0=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-largefront-policy-l1a)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_REGION_MAP=1
        LINUX_LARGEFRONT_DRAIN_TAKE_FIRST=1
        LINUX_LARGEFRONT_POLICY_L1A=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-largefront-policy-l1b)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_REGION_MAP=1
        LINUX_LARGEFRONT_DRAIN_TAKE_FIRST=1
        LINUX_LARGEFRONT_REMOTE_BATCH=1
        LINUX_LARGEFRONT_POLICY_L1B=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --linux-largefront-scavenge-local-cap)
        require_value "$@"
        LINUX_LARGEFRONT_SCAVENGE_LOCAL_CAP="$2"
        shift 2
        ;;
      --linux-largefront-lower-classes)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_LOWER_CLASSES=1
        HZ5_STANDALONE_EXACT_ONLY=0
        shift
        ;;
      --trace-lane)
        TRACE_LANE=1
        shift
        ;;
      --help|-h)
        usage
        exit 0
        ;;
      *)
        echo "unknown option: $1" >&2
        usage >&2
        exit 1
        ;;
    esac
  done
}
