#!/usr/bin/env bash
# Sourced by hz5_build_lowlevel_args.sh.

hz5_try_parse_midpage_build_arg() {
  HZ5_PARSE_SHIFT=0

  case "$1" in
      --linux-preload-full)
        BUILD_PRELOAD_FULL=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-smallfront-s1)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-smallfront-remote-batch-cap)
        require_value "$@"
        LINUX_SMALLFRONT_REMOTE_BATCH_CAP="$2"
        HZ5_PARSE_SHIFT=2
        ;;
      --linux-smallfront-drain-empty-gated)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_SMALLFRONT_DRAIN_EMPTY_GATED=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-smallfront-remote-outbox)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_SMALLFRONT_REMOTE_OUTBOX=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-region-outbox)
        enable_general_region_outbox_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-directfree)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_SMALLFRONT_REMOTE_OUTBOX=1
        LINUX_SMALLFRONT_REMOTE_BATCH_CAP=8
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_OWNER_FAST_STATE=1
        LINUX_MIDFRONT_REMOTE_BATCH_CAP=16
        LINUX_MIDFRONT_REMOTE_DIRECT_FREE_STATE=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_OWNER_FAST_STATE=1
        LINUX_LARGEFRONT_REGION_MAP=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midfirst)
        BUILD_PRELOAD_FULL=1
        PRELOAD_FREE_MID_FIRST=1
        LINUX_SMALLFRONT_S1=1
        LINUX_SMALLFRONT_REMOTE_OUTBOX=1
        LINUX_SMALLFRONT_REMOTE_BATCH_CAP=8
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_OWNER_FAST_STATE=1
        LINUX_MIDFRONT_REMOTE_BATCH_CAP=16
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_OWNER_FAST_STATE=1
        LINUX_LARGEFRONT_REGION_MAP=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midcache)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_SMALLFRONT_REMOTE_OUTBOX=1
        LINUX_SMALLFRONT_REMOTE_BATCH_CAP=8
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_OWNER_FAST_STATE=1
        LINUX_MIDFRONT_REMOTE_BATCH_CAP=16
        LINUX_MIDFRONT_LOOKUP_CACHE=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_OWNER_FAST_STATE=1
        LINUX_LARGEFRONT_REGION_MAP=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midrbuf)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_SMALLFRONT_REMOTE_OUTBOX=1
        LINUX_SMALLFRONT_REMOTE_BATCH_CAP=8
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_OWNER_FAST_STATE=1
        LINUX_MIDFRONT_REMOTE_BATCH_CAP=16
        LINUX_MIDFRONT_REMOTE_RBUF=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_OWNER_FAST_STATE=1
        LINUX_LARGEFRONT_REGION_MAP=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-routesplit)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_SMALLFRONT_REMOTE_OUTBOX=1
        LINUX_SMALLFRONT_REMOTE_BATCH_CAP=8
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_OWNER_FAST_STATE=1
        LINUX_MIDFRONT_REMOTE_BATCH_CAP=16
        LINUX_MIDFRONT_MAX_BYTES=4096
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_OWNER_FAST_STATE=1
        LINUX_LARGEFRONT_REGION_MAP=1
        LINUX_LARGEFRONT_LOWER_CLASSES=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_SMALLFRONT_REMOTE_OUTBOX=1
        LINUX_SMALLFRONT_REMOTE_BATCH_CAP=8
        LINUX_MIDPAGEFRONT_M2=1
        LINUX_MIDPAGEFRONT_REMOTE_BATCH_CAP=16
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_OWNER_FAST_STATE=1
        LINUX_MIDFRONT_REMOTE_BATCH_CAP=16
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_OWNER_FAST_STATE=1
        LINUX_LARGEFRONT_REGION_MAP=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region)
        enable_midpage_region_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow)
        enable_midpage_region_shadow_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-frontfirst)
        enable_midpage_region_shadow_base
        PRELOAD_FREE_MIDPAGE_FIRST=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-tlscache)
        enable_midpage_region_shadow_base
        LINUX_MIDPAGEFRONT_TLS_REGION_CACHE=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-hotslot)
        enable_midpage_region_shadow_base
        LINUX_MIDPAGEFRONT_TLS_HOT_SLOT=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-activetrust)
        enable_midpage_region_shadow_base
        LINUX_MIDPAGEFRONT_LOCAL_ACTIVE_TRUST=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-allocfirst)
        enable_midpage_shadow_allocfirst_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-localunsafe)
        enable_midpage_shadow_allocfirst_base
        LINUX_MIDPAGEFRONT_UNSAFE_LOCAL_NOCHECK=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4mag)
        enable_midpage_m4mag_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet)
        enable_midpage_m4packet_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst)
        enable_midpage_m4packet_freefirst_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink)
        enable_midpage_m4packet_freefirst_tlslink_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-allocelide)
        enable_midpage_m4packet_freefirst_tlslink_allocelide_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-ptrmag)
        enable_midpage_m4packet_freefirst_tlslink_ptrmag_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-absalloc)
        enable_midpage_m4packet_freefirst_tlslink_absalloc_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-regcache)
        enable_midpage_m4packet_freefirst_tlslink_regcache_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-slotswitch)
        enable_midpage_m4packet_freefirst_tlslink_slotswitch_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-superfast)
        enable_midpage_m4packet_freefirst_tlslink_superfast_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-superfast-freeelide)
        enable_midpage_m4packet_freefirst_tlslink_superfast_freeelide_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-m5hit)
        enable_midpage_m4packet_freefirst_tlslink_m5hit_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-m6-deferred-free-direct)
        enable_midpage_m6_deferred_free_direct_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-flatcap)
        enable_midpage_m4packet_freefirst_tlslink_flatcap_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-overarray)
        enable_midpage_m4packet_freefirst_tlslink_overarray_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-wide32k)
        enable_midpage_m4packet_freefirst_tlslink_wide32k_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band4-16-32)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_base 1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band4-8-16-32)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_base 4
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band4-8-32)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_base 5
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_base 2
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rssgov)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rssgov_base 2
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_base 2
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m6remote)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_base 2
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m7ticket)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m7ticket_base 2
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m6remote-m8xfer)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_m8xfer_base 2
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m6remote-m9budget)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_m9budget_base 2
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m10slot)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m10slot_base 2
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m6remote-m11direct)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_m11direct_base 2
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m6remote-pagerun)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun_base 2
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m6remote-pagerun64)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_base 2
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m6remote-pagerun64-takefirst)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_takefirst_base 2
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m6remote-pagerun64-adaptive128)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_adaptive128_base 2
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m6remote-pagerun64-scavenge)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_scavenge_base 2
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-m6remote-pagerun64-observe)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_m6remote_pagerun64_observe_base 2
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-32-rsscheckpoint-drainhit)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_drainhit_base 2
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-16-32)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_base 6
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-16-32-rssgov)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rssgov_base 6
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-16-32-rsscheckpoint)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_base 6
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band8-16-32-rsscheckpoint-drainhit)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_rsscheckpoint_drainhit_base 6
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-band16-32)
        enable_midpage_m4packet_freefirst_tlslink_coarse_bands_base 3
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-tagfree)
        enable_midpage_m4packet_freefirst_tlslink_tagfree_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-freefirst-tlslink-m4stats)
        enable_midpage_m4packet_freefirst_tlslink_m4stats_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midpagefront-m6-raw-cap)
        require_value "$@"
        LINUX_MIDPAGEFRONT_M6_RAW_CAP="$2"
        HZ5_PARSE_SHIFT=2
        ;;
      --linux-midpagefront-m6-deferred-free)
        LINUX_MIDPAGEFRONT_M6_DEFERRED_FREE=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midpagefront-m6-remote-deferred-free)
        LINUX_MIDPAGEFRONT_M6_REMOTE_DEFERRED_FREE=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midpagefront-m6-remote-no-refill-flush)
        LINUX_MIDPAGEFRONT_M6_REMOTE_FLUSH_ON_REFILL=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midpagefront-m7-remote-ticket)
        LINUX_MIDPAGEFRONT_M7_REMOTE_TICKET=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midpagefront-m7-remote-page-cap)
        require_value "$@"
        LINUX_MIDPAGEFRONT_M7_REMOTE_PAGE_CAP="$2"
        HZ5_PARSE_SHIFT=2
        ;;
      --linux-midpagefront-m8-owner-xfer)
        LINUX_MIDPAGEFRONT_M8_OWNER_XFER=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midpagefront-m8-xfer-page-cap)
        require_value "$@"
        LINUX_MIDPAGEFRONT_M8_XFER_PAGE_CAP="$2"
        HZ5_PARSE_SHIFT=2
        ;;
      --linux-midpagefront-m9-budget-drain)
        LINUX_MIDPAGEFRONT_M9_BUDGET_DRAIN=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midpagefront-m10-remote-slot-ring)
        LINUX_MIDPAGEFRONT_M10_REMOTE_SLOT_RING=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midpagefront-m11-remote-direct-cache)
        LINUX_MIDPAGEFRONT_M11_REMOTE_DIRECT_CACHE=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midpagefront-pagerun)
        LINUX_MIDPAGEFRONT_PAGERUN=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midpagefront-pagerun-64k)
        LINUX_MIDPAGEFRONT_PAGERUN_64K=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midpagefront-m4-remote-drain-hit-interval)
        require_value "$@"
        LINUX_MIDPAGEFRONT_M4_REMOTE_DRAIN_HIT_INTERVAL="$2"
        HZ5_PARSE_SHIFT=2
        ;;
      --linux-midpagefront-empty-slab-release)
        LINUX_MIDPAGEFRONT_EMPTY_SLAB_RELEASE=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midpagefront-empty-release-checkpoint)
        LINUX_MIDPAGEFRONT_EMPTY_SLAB_RELEASE=1
        LINUX_MIDPAGEFRONT_EMPTY_RELEASE_ON_REFILL=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midpagefront-empty-retain-cap)
        require_value "$@"
        LINUX_MIDPAGEFRONT_EMPTY_RETAIN_CAP="$2"
        HZ5_PARSE_SHIFT=2
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-routefree)
        enable_midpage_m4packet_routefree_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-m4packet-crossdrain)
        enable_midpage_m4packet_crossdrain_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-slotswitch)
        enable_midpage_shadow_allocfirst_base
        LINUX_MIDPAGEFRONT_SLOT_SWITCH=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-tlslink)
        enable_midpage_shadow_allocfirst_base
        PRELOAD_TLS_INITIAL_EXEC=1
        PRELOAD_SPEED_LINKFLAGS=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-tlsie)
        enable_midpage_shadow_allocfirst_base
        PRELOAD_TLS_INITIAL_EXEC=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-linkonly)
        enable_midpage_shadow_allocfirst_base
        PRELOAD_SPEED_LINKFLAGS=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-nodeless)
        enable_midpage_nodeless_base
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-nodeless-ptrcache)
        enable_midpage_nodeless_base
        LINUX_MIDPAGEFRONT_NODELESS_PTRCACHE=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-nodeless-stats)
        enable_midpage_nodeless_base
        LINUX_MIDPAGEFRONT_NODELESS_STATS=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-shadow-nodeless-ptrcache-stats)
        enable_midpage_nodeless_base
        LINUX_MIDPAGEFRONT_NODELESS_PTRCACHE=1
        LINUX_MIDPAGEFRONT_NODELESS_STATS=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midpage-region-frontfirst)
        BUILD_PRELOAD_FULL=1
        PRELOAD_FREE_MIDPAGE_FIRST=1
        LINUX_SMALLFRONT_S1=1
        LINUX_SMALLFRONT_REMOTE_OUTBOX=1
        LINUX_SMALLFRONT_REMOTE_BATCH_CAP=8
        LINUX_MIDPAGEFRONT_M2=1
        LINUX_MIDPAGEFRONT_REGION_ARRAY=1
        LINUX_MIDPAGEFRONT_REMOTE_BATCH_CAP=16
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_OWNER_FAST_STATE=1
        LINUX_MIDFRONT_REMOTE_BATCH_CAP=16
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_OWNER_FAST_STATE=1
        LINUX_LARGEFRONT_REGION_MAP=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
    *)
      return 1
      ;;
  esac

  return 0
}
