#!/usr/bin/env bash
# Sourced by hz5_build_lowlevel_args.sh.

hz5_try_parse_frontend_build_arg() {
  HZ5_PARSE_SHIFT=0

  case "$1" in
      --linux-hz5-general-midoutbox)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_SMALLFRONT_REMOTE_OUTBOX=1
        LINUX_SMALLFRONT_REMOTE_BATCH_CAP=8
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_OWNER_FAST_STATE=1
        LINUX_MIDFRONT_REMOTE_BATCH_CAP=16
        LINUX_MIDFRONT_REMOTE_OUTBOX=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_OWNER_FAST_STATE=1
        LINUX_LARGEFRONT_REGION_MAP=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-hz5-general-midoutbox-flush)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_SMALLFRONT_REMOTE_OUTBOX=1
        LINUX_SMALLFRONT_REMOTE_BATCH_CAP=8
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_OWNER_FAST_STATE=1
        LINUX_MIDFRONT_REMOTE_BATCH_CAP=16
        LINUX_MIDFRONT_REMOTE_OUTBOX=1
        LINUX_MIDFRONT_OUTBOX_FLUSH_ON_MISS=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_OWNER_FAST_STATE=1
        LINUX_LARGEFRONT_REGION_MAP=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-ownerhub-r1)
        BUILD_PRELOAD_FULL=1
        LINUX_OWNERHUB_R1=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-ownerhub-r2)
        BUILD_PRELOAD_FULL=1
        LINUX_OWNERHUB_R2=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-ownerhub-r3)
        BUILD_PRELOAD_FULL=1
        LINUX_OWNERHUB_R3=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midfront-m1)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midpagefront-m2)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDPAGEFRONT_M2=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midpagefront-region-array)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDPAGEFRONT_M2=1
        LINUX_MIDPAGEFRONT_REGION_ARRAY=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midpagefront-remote-shadow)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDPAGEFRONT_M2=1
        LINUX_MIDPAGEFRONT_REMOTE_SHADOW=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midpagefront-local-fast-state)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDPAGEFRONT_M2=1
        LINUX_MIDPAGEFRONT_LOCAL_FAST_STATE=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midpagefront-tls-region-cache)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDPAGEFRONT_M2=1
        LINUX_MIDPAGEFRONT_REGION_ARRAY=1
        LINUX_MIDPAGEFRONT_TLS_REGION_CACHE=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midpagefront-tls-hot-slot)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDPAGEFRONT_M2=1
        LINUX_MIDPAGEFRONT_TLS_HOT_SLOT=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midpagefront-local-active-trust)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDPAGEFRONT_M2=1
        LINUX_MIDPAGEFRONT_LOCAL_ACTIVE_TRUST=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midpagefront-remote-batch-cap)
        require_value "$@"
        LINUX_MIDPAGEFRONT_REMOTE_BATCH_CAP="$2"
        HZ5_PARSE_SHIFT=2
        ;;
      --linux-midfront-owner-fast-state)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_OWNER_FAST_STATE=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midfront-max-bytes)
        require_value "$@"
        LINUX_MIDFRONT_MAX_BYTES="$2"
        HZ5_PARSE_SHIFT=2
        ;;
      --linux-midfront-remote-batch-cap)
        require_value "$@"
        LINUX_MIDFRONT_REMOTE_BATCH_CAP="$2"
        HZ5_PARSE_SHIFT=2
        ;;
      --linux-midfront-remote-outbox)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_REMOTE_OUTBOX=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midfront-remote-outbox-slots)
        require_value "$@"
        LINUX_MIDFRONT_REMOTE_OUTBOX_SLOTS="$2"
        HZ5_PARSE_SHIFT=2
        ;;
      --linux-midfront-remote-rbuf)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_REMOTE_RBUF=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midfront-remote-rbuf-cap)
        require_value "$@"
        LINUX_MIDFRONT_REMOTE_RBUF_CAP="$2"
        HZ5_PARSE_SHIFT=2
        ;;
      --linux-midfront-remote-rbuf-threshold)
        require_value "$@"
        LINUX_MIDFRONT_REMOTE_RBUF_FLUSH_THRESHOLD="$2"
        HZ5_PARSE_SHIFT=2
        ;;
      --linux-midfront-outbox-flush-on-miss)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_REMOTE_OUTBOX=1
        LINUX_MIDFRONT_OUTBOX_FLUSH_ON_MISS=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midfront-remote-direct-free-state)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_REMOTE_DIRECT_FREE_STATE=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midfront-remote-trust-drain-state)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_REMOTE_DIRECT_FREE_STATE=1
        LINUX_MIDFRONT_REMOTE_TRUST_DRAIN_STATE=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midfront-lookup-cache)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_LOOKUP_CACHE=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midfront-drain-all-on-miss)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_DRAIN_ALL_ON_MISS=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midfront-drain-mask-on-miss)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_DRAIN_MASK_ON_MISS=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midfront-drain-mask-hit-stop)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_DRAIN_MASK_ON_MISS=1
        LINUX_MIDFRONT_DRAIN_MASK_HIT_STOP=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midfront-drain-take-first)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_DRAIN_TAKE_FIRST=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midfront-drain-empty-gated)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_DRAIN_EMPTY_GATED=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-midfront-remote-global-recycle)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_MIDFRONT_REMOTE_GLOBAL_RECYCLE=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-largefront-l1)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-largefront-owner-fast-state)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_FAST_STATE=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-largefront-owner-inbox)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-largefront-remote-batch)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_REMOTE_BATCH=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-largefront-remote-batch-cap)
        require_value "$@"
        LINUX_LARGEFRONT_REMOTE_BATCH_CAP="$2"
        HZ5_PARSE_SHIFT=2
        ;;
      --linux-largefront-source-batch-count)
        require_value "$@"
        LINUX_LARGEFRONT_SOURCE_BATCH_COUNT="$2"
        BUILD_PRELOAD_FULL=1
        HZ5_PARSE_SHIFT=2
        ;;
      --linux-largefront-alloc-drain-local-budget)
        require_value "$@"
        LINUX_LARGEFRONT_ALLOC_DRAIN_LOCAL_BUDGET="$2"
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=2
        ;;
      --linux-largefront-drain-take-first)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_DRAIN_TAKE_FIRST=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-largefront-drain-empty-gated)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_DRAIN_EMPTY_GATED=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-largefront-map-base-only)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_MAP_BASE_ONLY=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-largefront-region-map)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_REGION_MAP=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-largefront-adaptive128)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_REGION_MAP=1
        LINUX_LARGEFRONT_DRAIN_TAKE_FIRST=1
        LINUX_LARGEFRONT_ADAPTIVE128=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-largefront-payload-scavenge)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_REGION_MAP=1
        LINUX_LARGEFRONT_PAYLOAD_SCAVENGE=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-largefront-observe)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_REGION_MAP=1
        LINUX_LARGEFRONT_OBSERVE=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-largefront-policy-l0)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_REGION_MAP=1
        LINUX_LARGEFRONT_POLICY_L0=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-largefront-drain-bulk-local)
        LINUX_LARGEFRONT_DRAIN_BULK_LOCAL=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-largefront-drain-trust-remote-state)
        LINUX_LARGEFRONT_DRAIN_TRUST_REMOTE_STATE=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-largefront-transfer128)
        LINUX_LARGEFRONT_TRANSFER128=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-largefront-transfer128-consumer-shard)
        LINUX_LARGEFRONT_TRANSFER128=1
        LINUX_LARGEFRONT_TRANSFER128_CONSUMER_SHARD=1
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-largefront-policy-l1a)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_REGION_MAP=1
        LINUX_LARGEFRONT_DRAIN_TAKE_FIRST=1
        LINUX_LARGEFRONT_POLICY_L1A=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-largefront-policy-l1b)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_OWNER_INBOX=1
        LINUX_LARGEFRONT_REGION_MAP=1
        LINUX_LARGEFRONT_DRAIN_TAKE_FIRST=1
        LINUX_LARGEFRONT_REMOTE_BATCH=1
        LINUX_LARGEFRONT_POLICY_L1B=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --linux-largefront-scavenge-local-cap)
        require_value "$@"
        LINUX_LARGEFRONT_SCAVENGE_LOCAL_CAP="$2"
        HZ5_PARSE_SHIFT=2
        ;;
      --linux-largefront-lower-classes)
        BUILD_PRELOAD_FULL=1
        LINUX_SMALLFRONT_S1=1
        LINUX_MIDFRONT_M1=1
        LINUX_LARGEFRONT_L1=1
        LINUX_LARGEFRONT_LOWER_CLASSES=1
        HZ5_STANDALONE_EXACT_ONLY=0
        HZ5_PARSE_SHIFT=1
        ;;
      --trace-lane)
        TRACE_LANE=1
        HZ5_PARSE_SHIFT=1
        ;;
    *)
      return 1
      ;;
  esac

  return 0
}
